import { describe,it,expect } from 'vitest';
import { curriculum,learningTrails } from '../data/curriculum';
import { allConceptLinks as conceptLinks } from './conceptGraph';
import { activationValue,activationDerivative,initialNetwork,networkBatch,networkStep,type NetworkParameters } from './learningMath';
import { lowerBound,sortedWithCount,traverseGraph,shortestPaths,topK,kmp,kruskal,csModels } from './csModels';

describe('Authored expansions and meaningful connections cover the whole atlas',()=>{
 it('every topic has an explicit expansion and appears in an explained learning flow',()=>{for(const t of curriculum){expect(t.expansion!.formula.length).toBeGreaterThan(20);expect(t.expansion!.explanation.length).toBeGreaterThan(20);expect(learningTrails.some(trail=>trail.steps.some(s=>s.id===t.id))).toBe(true);expect(conceptLinks.some(l=>l.from===t.id||l.to===t.id)).toBe(true);}});
 it('all directed links point to real notes and provide a reason',()=>{const ids=new Set(curriculum.map(t=>t.id));for(const link of conceptLinks){expect(ids.has(link.from)).toBe(true);expect(ids.has(link.to)).toBe(true);expect(link.from).not.toBe(link.to);expect(link.explanation.length).toBeGreaterThan(10);}});
 it('display neighbors are not falsely required prerequisites',()=>{expect(curriculum.find(t=>t.id==='activation')!.prerequisites).toEqual(['derivatives']);expect(curriculum.find(t=>t.id==='probability')!.prerequisites).toEqual([]);});
});
describe('Analytic activation derivatives and actual training',()=>{
 it.each([0,1,2,3,4,5])('activation %i agrees with independent central differences away from corners',mode=>{for(const x of [-4,-1,-.2,.2,1,4]){const h=1e-5,finite=(activationValue(mode,x+h)-activationValue(mode,x-h))/(2*h);expect(activationDerivative(mode,x)).toBeCloseTo(finite,7);}});
 it('keeps undefined corner derivatives distinct from chosen implementation gradients',()=>{expect(activationDerivative(0,0)).toBeNull();expect(activationDerivative(1,0)).toBeNull();expect(activationDerivative(3,0)).toBe(.25);expect(activationDerivative(5,0)).toBe(.5);});
 it('all seven batch gradients agree with finite differences',()=>{const p=initialNetwork(),g=networkBatch(p).gradient,epsilon=1e-5;for(const key of ['w1','b1','w2','b2'] as const){const count=key==='b2'?1:2;for(let i=0;i<count;i++){const left=structuredClone(p),right=structuredClone(p);if(key==='b2'){left.b2-=epsilon;right.b2+=epsilon;}else{left[key][i]-=epsilon;right[key][i]+=epsilon;}const gradient=key==='b2'?g.b2:g[key][i];expect(gradient).toBeCloseTo((networkBatch(right).loss-networkBatch(left).loss)/(2*epsilon),8);}}});
 it('updates all parameters using the mean batch gradient',()=>{const p=initialNetwork(),g=networkBatch(p).gradient,next=networkStep(p,.15);expect(next.b2).toBeCloseTo(p.b2-.15*g.b2,12);for(const key of ['w1','w2','b1'] as const)next[key].forEach((value,i)=>expect(value).toBeCloseTo(p[key][i]-.15*g[key][i],12));expect(networkBatch(next).loss).toBeLessThan(networkBatch(p).loss);});
 it('twenty modest steps lower loss and a large rate can increase it',()=>{let p:NetworkParameters=initialNetwork();const before=networkBatch(p).loss;for(let i=0;i<20;i++)p=networkStep(p,.15);expect(networkBatch(p).loss).toBeLessThan(before);expect(networkBatch(networkStep(initialNetwork(),2)).loss).toBeGreaterThan(before);});
});
describe('CS algorithms preserve their invariants',()=>{
 it('lower_bound partitions sorted arrays including duplicates and absent values',()=>{for(const xs of [[],[1],[1,1,3,5],[1,3,5,7]])for(const target of [-1,1,2,8]){const {index}=lowerBound(xs,target);expect(xs.slice(0,index).every(x=>x<target)).toBe(true);expect(xs.slice(index).every(x=>x>=target)).toBe(true);}});
 it('both sorts match a numeric reference including negative and duplicate values',()=>{for(const a of [[4,1,3,2],[1,1,-2,8],[],[3]])for(const merge of [false,true])expect(sortedWithCount(a,merge).values).toEqual(a.slice().sort((a,b)=>a-b));});
 it('BFS obtains minimum hops and DFS visits the same connected nodes',()=>{expect(traverseGraph(0,false).distance).toEqual([0,1,1,2,3,2]);expect(traverseGraph(0,true).order.slice().sort()).toEqual([0,1,2,3,4,5]);});
 it('all three shortest-path methods agree with the independent path formula',()=>{for(let w=1;w<=10;w++)for(const method of [0,1,2])expect(shortestPaths(w,method).distance).toEqual([0,2,Math.min(8,2+w),Math.min(9,3+w)]);});
 it('heap Top-k matches full sorting and keeps each parent no larger than children',()=>{for(const xs of [[4,1,8,3,6,2,9,5],[1,1,-2,4,4]])for(let k=1;k<=xs.length;k++){const r=topK(xs,k);expect(r.values).toEqual(xs.slice().sort((a,b)=>b-a).slice(0,k));r.heap.forEach((x,i)=>{if(i)expect(r.heap[Math.floor((i-1)/2)]).toBeLessThanOrEqual(x);});}});
 it('KMP finds the same overlapping positions as independent naive matching',()=>{for(const text of ['ababa','aaaaa','abc','ab'.repeat(10)+'a'])for(const pattern of ['aba','aa','b','ababa']){const expected=Array.from({length:text.length},(_,i)=>i).filter(i=>text.slice(i,i+pattern.length)===pattern);expect(kmp(text,pattern).matches).toEqual(expected);}});
 it('Kruskal forms one component with V−1 edges and expected minimum cost',()=>{for(let w=1;w<=8;w++){const r=kruskal(w);expect(r.chosen).toHaveLength(3);expect(new Set(r.parent).size).toBe(1);expect(r.cost).toBe(3+Math.min(3,w));}});
 it('positive-subset pruning changes visits while preserving every solution',()=>{const model=csModels['cs-backtracking'];for(let size=1;size<=8;size++)for(const target of [0,3,10]){const a=model.calculate({size,target,prune:0}),b=model.calculate({size,target,prune:1});expect(a.metrics[1].value).toBe(b.metrics[1].value);expect(b.metrics[0].value!).toBeLessThanOrEqual(a.metrics[0].value!);expect(a.metrics[0].value).toBe(2**(size+1)-1);}});
});
