import { c, choice, m, n, type LessonModel } from './lessonModelTypes';
const base = (title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});

export function lowerBound(xs:number[], target:number) { let lo=0,hi=xs.length,comparisons=0;const trace:string[]=[];while(lo<hi){const mid=Math.floor((lo+hi)/2);comparisons++;trace.push(`[${lo},${hi}) mid=${mid}, a[mid]=${xs[mid]}`);if(xs[mid]<target)lo=mid+1;else hi=mid;}return{index:lo,comparisons,trace}; }
export function sortedWithCount(xs:number[], merge:boolean) {
 let comparisons=0;const sort=(a:number[]):number[]=>{if(a.length<2)return a.slice();const mid=Math.floor(a.length/2),l=sort(a.slice(0,mid)),r=sort(a.slice(mid));let i=0,j=0;const out:number[]=[];while(i<l.length&&j<r.length){comparisons++;out.push(l[i]<=r[j]?l[i++]:r[j++]);}return out.concat(l.slice(i),r.slice(j));};
 if(merge)return{values:sort(xs),comparisons};const values=xs.slice();for(let i=1;i<values.length;i++){const key=values[i];let j=i-1;while(j>=0){comparisons++;if(values[j]<=key)break;values[j+1]=values[j];j--;}values[j+1]=key;}return{values,comparisons};
}
export const graphEdges:[[number,number],... [number,number][]]=[[0,1],[0,2],[1,3],[2,3],[3,4],[2,5]];
export function traverseGraph(start:number,dfs:boolean) {
 const adj=Array.from({length:6},()=>[] as number[]);for(const [u,v] of graphEdges){adj[u].push(v);adj[v].push(u);}
 const seen=new Set([start]),distance=Array(6).fill(-1) as number[],order:number[]=[];distance[start]=0;
 if(dfs){const stack=[{node:start,next:0}];order.push(start);while(stack.length){const frame=stack.at(-1)!;if(frame.next>=adj[frame.node].length){stack.pop();continue;}const v=adj[frame.node][frame.next++];if(seen.has(v))continue;seen.add(v);distance[v]=distance[frame.node]+1;order.push(v);stack.push({node:v,next:0});}}
 else {const queue=[start];let head=0;while(head<queue.length){const u=queue[head++];order.push(u);for(const v of adj[u])if(!seen.has(v)){seen.add(v);distance[v]=distance[u]+1;queue.push(v);}}}
 return{order,distance};
}
export function shortestPaths(weight:number,method:number) { const edges=[[0,1,2],[1,2,weight],[0,2,8],[2,3,1],[1,3,9]],d=[0,Infinity,Infinity,Infinity];let checks=0;
 if(method===0){const done=new Set<number>();for(let step=0;step<4;step++){let u=-1;for(let i=0;i<4;i++)if(!done.has(i)&&(u<0||d[i]<d[u]))u=i;done.add(u);for(const [a,b,w] of edges)if(a===u){checks++;d[b]=Math.min(d[b],d[a]+w);}}}
 else if(method===1){for(let step=0;step<3;step++)for(const [u,v,w] of edges){checks++;d[v]=Math.min(d[v],d[u]+w);}}
 else {const matrix=Array.from({length:4},(_,i)=>Array.from({length:4},(_,j)=>i===j?0:Infinity));for(const [u,v,w] of edges)matrix[u][v]=w;for(let k=0;k<4;k++)for(let i=0;i<4;i++)for(let j=0;j<4;j++){checks++;matrix[i][j]=Math.min(matrix[i][j],matrix[i][k]+matrix[k][j]);}return{distance:matrix[0],checks};}return{distance:d,checks};
}
export function topK(xs:number[],k:number) { const heap:number[]=[];let comparisons=0;const down=()=>{let i=0;while(i*2+1<heap.length){let j=i*2+1;if(j+1<heap.length){comparisons++;if(heap[j+1]<heap[j])j++;}comparisons++;if(heap[i]<=heap[j])break;[heap[i],heap[j]]=[heap[j],heap[i]];i=j;}};for(const x of xs){if(heap.length<k){heap.push(x);let i=heap.length-1;while(i>0){const p=Math.floor((i-1)/2);comparisons++;if(heap[p]<=heap[i])break;[heap[p],heap[i]]=[heap[i],heap[p]];i=p;}}else{comparisons++;if(x>heap[0]){heap[0]=x;down();}}}return{values:heap.slice().sort((a,b)=>b-a),heap,comparisons}; }
export function kmp(text:string,pattern:string) { const prefix=Array(pattern.length).fill(0) as number[];for(let i=1,j=0;i<pattern.length;i++){while(j>0&&pattern[i]!==pattern[j])j=prefix[j-1];if(pattern[i]===pattern[j])j++;prefix[i]=j;}const matches:number[]=[];let comparisons=0;for(let i=0,j=0;i<text.length;i++){while(j>0){comparisons++;if(text[i]===pattern[j])break;j=prefix[j-1];}if(j===0)comparisons++;if(text[i]===pattern[j])j++;if(j===pattern.length){matches.push(i-j+1);j=prefix[j-1];}}return{matches,prefix,comparisons}; }
export function kruskal(lastWeight:number) {const edges=[[0,1,1],[1,2,2],[2,3,3],[0,3,lastWeight],[0,2,4]].sort((a,b)=>a[2]-b[2]),parent=[0,1,2,3],size=[1,1,1,1];const find=(v:number):number=>parent[v]===v?v:(parent[v]=find(parent[v]));let cost=0;const chosen:number[][]=[];for(const [u,v,w] of edges){let a=find(u),b=find(v);if(a===b)continue;if(size[a]<size[b])[a,b]=[b,a];parent[b]=a;size[a]+=size[b];cost+=w;chosen.push([u,v,w]);}return{cost,chosen,parent:parent.map((_,i)=>find(i))};}
export const csModels:Record<string,LessonModel>={
 'cs-complexity':base('입력 크기와 증가율','계수·장치·메모리 지연을 제외한 대표 연산 수 함수입니다. n log₂n은 실제 정렬 비교 횟수가 아닙니다.',[c('size','입력 n',128,2,1024,1)],p=>({metrics:[m('선형 n',p.size),m('n log₂n',p.size*Math.log2(p.size)),m('제곱 n²',p.size**2)],steps:[`log₂n=${n(Math.log2(p.size))}`,`n log₂n=${n(p.size*Math.log2(p.size))}`,`n²=${p.size**2}`],bars:[{label:'n',value:p.size},{label:'n log₂n',value:p.size*Math.log2(p.size)},{label:'n²',value:p.size**2}]}),'가로축 n을 바꾸어 증가율을 보세요. 동일 Big-O의 구현도 실제 시간은 다를 수 있습니다.'),
 'cs-structures':base('배열 조회와 선형 검색','a=[1,…,n], 찾는 값은 n. 배열 인덱스 조회와 앞에서부터 검색의 값 검사 횟수만 셉니다. 해시는 구현하지 않습니다.',[c('size','배열 길이 n',8,1,64,1)],p=>({metrics:[m('인덱스 값 조회',1),m('선형 검색 값 검사',p.size),m('배열 저장 원소',p.size)],steps:[`a=[1,…,${p.size}]`,`a[n−1]=${p.size}: 주소로 한 원소 조회`,`선형 검색은 앞에서 ${p.size}개 값을 비교합니다.`]}),'같은 값을 찾더라도 인덱스를 알고 있는지에 따라 필요한 작업이 달라집니다.'),
 'cs-sorting':base('정렬의 실제 비교 횟수','배열은 1…n의 정순·역순. 원소 간 크기 비교만 세며 복사·할당 시간은 제외합니다.',[c('size','배열 길이 n',8,2,32,1),choice('order','입력 순서',1,['정순','역순']),choice('method','정렬 방식',1,['삽입정렬','병합정렬'])],p=>{const xs=Array.from({length:p.size},(_,i)=>p.order?p.size-i:i+1),r=sortedWithCount(xs,Boolean(p.method));return{metrics:[m('실제 비교',r.comparisons),m('길이',xs.length)],steps:[`입력=[${xs.join(',')}]`,p.method?'분할 → 각 절반 정렬 → 두 목록 병합':'왼쪽 정렬 구간으로 다음 원소 삽입',`결과=[${r.values.join(',')}]`,`크기 비교 ${r.comparisons}회`],matrix:{name:'입력 / 정렬 결과',values:[xs,r.values]}};},'정순에서 삽입정렬의 비교가 줄어듭니다. 평균·최악 복잡도와 한 입력의 횟수를 구별하세요.'),
 'cs-binary-search':base('lower_bound 후보 구간','배열 [1,3,…,2n−1]에서 target 이상인 첫 위치. 없는 경우 n을 반환합니다.',[c('size','배열 길이',8,1,32,1),c('target','찾을 값',8,0,65,1)],p=>{const xs=Array.from({length:p.size},(_,i)=>2*i+1),r=lowerBound(xs,p.target);return{metrics:[m('삽입 인덱스',r.index),m('실제 비교',r.comparisons),m('해당 값',xs[r.index]??null)],steps:['구간은 [lo,hi), hi는 배열 길이입니다.',...r.trace,`종료 lo=hi=${r.index}; 값 ${xs[r.index]??'없음'}`]};},'끝보다 큰 값을 찾으면 배열 길이가 나옵니다. 불변식은 왼쪽 제외 영역의 값이 target보다 작다는 것입니다.'),
 'cs-prefix-window':base('구간 합과 고정 창','a=[1,…,8], [l,r) 구간과 길이 r−l의 모든 연속 창. l<r을 만족하도록 끝을 보정합니다.',[c('left','왼쪽 l',1,0,7,1),c('right','오른쪽 r 요청',4,1,8,1)],p=>{const l=p.left,r=Math.max(l+1,p.right),a=[1,2,3,4,5,6,7,8],prefix=[0];a.forEach(x=>prefix.push(prefix.at(-1)!+x));const width=r-l,windows=a.slice(0,9-width).map((_,i)=>prefix[i+width]-prefix[i]);return{metrics:[m('실제 오른쪽 r',r),m('구간 합',prefix[r]-prefix[l]),m('최대 창 합',Math.max(...windows))],steps:[`P=[${prefix.join(',')}]`,`사용 구간 [${l},${r}), 길이 ${width}`,`P[r]−P[l]=${prefix[r]}−${prefix[l]}=${prefix[r]-prefix[l]}`],matrix:{name:'각 시작 위치의 창 합',values:[windows]}};},'r 요청≤l이면 r=l+1로 보정됩니다. 전처리 O(n) 이후 구간 합은 두 값의 차로 계산됩니다.'),
 'cs-backtracking':base('선택 트리와 가지치기','양수 1…n의 부분집합 합. 합이 목표보다 큰 노드를 중단합니다. 실제 방문 노드와 해의 수를 셉니다.',[c('size','원소 수 n',5,1,12,1),c('target','목표 합',6,0,40,1),choice('prune','가지치기',1,['끔','켬'])],p=>{let visits=0,solutions=0;const walk=(i:number,sum:number)=>{visits++;if(p.prune&&sum>p.target)return;if(i>p.size){if(sum===p.target)solutions++;return;}walk(i+1,sum);walk(i+1,sum+i);};walk(1,0);return{metrics:[m('방문 노드',visits),m('가능한 해',solutions),m('전체 부분집합',2**p.size)],steps:[`입력 [1,…,${p.size}], 목표 ${p.target}`,'각 원소를 제외 / 포함하는 두 가지 선택을 재귀 호출합니다.',`방문 ${visits}회, 해 ${solutions}개`],warning:'합 초과 가지치기는 모든 입력이 양수인 이 예제에서만 사용합니다.'};},'가지치기를 꺼도 해의 수는 같습니다. 방문 노드는 줄어들지만 최악의 경우 여전히 지수적입니다.'),
 'cs-graph':base('큐·스택과 방문 순서','무방향 간선 0–1,0–2,1–3,2–3,3–4,2–5. DFS 거리 표시는 탐색 트리 깊이이며 최단 거리가 아닙니다.',[c('start','시작 노드',0,0,5,1),choice('method','탐색 방식',0,['BFS 큐','DFS 스택'])],p=>{const r=traverseGraph(p.start,Boolean(p.method));return{metrics:[m('방문 노드',r.order.length),m('노드 4의 거리·깊이',r.distance[4])],steps:[`시작 ${p.start}: 발견 즉시 방문 표시`,p.method?'마지막으로 넣은 노드를 먼저 꺼냅니다.':'처음 넣은 노드를 먼저 꺼냅니다.',`방문 순서 [${r.order.join(',')}]`],matrix:{name:p.method?'노드별 DFS 트리 깊이':'노드별 BFS 최소 hop',values:[r.distance]}};},'같은 그래프에서 방문 순서와 경로가 달라집니다. 가중치가 없을 때 BFS의 거리만 최단 hop을 보장합니다.'),
 'cs-shortest-path':base('relaxation으로 경로 개선','방향 간선 0→1:2,1→2:w,0→2:8,2→3:1,1→3:9. 모든 간선은 양수여서 세 알고리즘이 같은 거리를 구합니다.',[c('weight','1→2 비용 w',3,1,10,1),choice('method','알고리즘',0,['Dijkstra','Bellman–Ford','Floyd–Warshall'])],p=>{const r=shortestPaths(p.weight,p.method);return{metrics:[m('0→2 최단 비용',r.distance[2]),m('0→3 최단 비용',r.distance[3]),m('relaxation 검사',r.checks)],steps:[`직접 0→2=8, 경유 0→1→2=${2+p.weight}`,`d[2]=min(8,2+w)=${r.distance[2]}`,`0번에서 각 노드까지 [${r.distance.join(',')}]`],matrix:{name:'0번에서 최단 비용',values:[r.distance]}};},'이 Dijkstra는 작은 배열로 다음 노드를 선택하며 힙 최적화는 하지 않습니다. 검사 횟수가 실제 실행 시간은 아닙니다.'),
 'cs-greedy':base('먼저 끝나는 활동 선택','활동 [0,2],[1,3],[2,4],[3,5],[4,e]. 끝 시각으로 정렬하고 충돌하지 않는 활동을 선택합니다. 끝=다음 시작이면 허용합니다.',[c('end','마지막 활동 종료 e',6,5,9,1)],p=>{const intervals=[[0,2],[1,3],[2,4],[3,5],[4,p.end]].sort((a,b)=>a[1]-b[1]);let end=-Infinity;const chosen=intervals.filter(([s,e])=>{if(s<end)return false;end=e;return true;});return{metrics:[m('선택 활동 수',chosen.length),m('마지막 종료',end)],steps:['끝나는 순서로 정렬합니다.','직전 선택의 종료보다 빠른 시작은 제외합니다.',`선택=${chosen.map(a=>`[${a}]`).join(' ')}`],matrix:{name:'선택 활동 시작·종료',values:chosen}};},'최적해의 첫 활동을 가장 일찍 끝나는 활동으로 바꿔도 뒤의 선택을 잃지 않는 교환 논증을 읽어보세요.'),
 'cs-dp':base('중복 호출에서 상태 재사용으로','Fibonacci F₀=0,F₁=1. 재귀 호출 수는 C₀=C₁=1,Cₙ=1+Cₙ₋₁+Cₙ₋₂로 정확히 계산합니다.',[c('size','상태 n',10,2,35,1)],p=>{const f=[0,1],calls=[1,1];for(let i=2;i<=p.size;i++){f[i]=f[i-1]+f[i-2];calls[i]=1+calls[i-1]+calls[i-2];}return{metrics:[m('Fₙ',f[p.size]),m('단순 재귀 호출 수',calls[p.size]),m('DP 덧셈 수',p.size-1)],steps:['F₀=0,F₁=1 초기화',`각 i=2…${p.size}에서 이전 두 결과를 더합니다.`,`F=[${f.join(',')}]`],matrix:{name:'상태별 Fibonacci',values:[f]}};},'값과 계산 횟수는 서로 다른 곡선입니다. 두 이전 값만 보관하면 추가 공간은 O(1)이 됩니다.'),
 'cs-union-find':base('Kruskal의 사이클 검사','4개 노드, 간선 (0,1,1),(1,2,2),(2,3,3),(0,3,w),(0,2,4). Union by size와 path compression을 씁니다.',[c('weight','0–3 비용 w',5,1,8,1)],p=>{const r=kruskal(p.weight);return{metrics:[m('MST 총 비용',r.cost),m('선택 간선 수',r.chosen.length)],steps:['간선 비용 오름차순 정렬','서로 다른 대표인 두 노드만 연결합니다.',`선택=${r.chosen.map(a=>`(${a})`).join(' ')}`,`비용 합=${r.cost}`],matrix:{name:'선택 간선 u,v,비용',values:r.chosen}};},'연결 그래프의 신장 트리는 V−1개 간선입니다. Union–Find는 최단 거리를 계산하는 자료구조가 아닙니다.'),
 'cs-heap-topk':base('크기 k의 min-heap','점수 [4,1,8,3,6,2,9,5]를 차례로 넣습니다. 마지막 정렬의 비교는 힙 비교 횟수에서 제외합니다.',[c('k','후보 k',3,1,8,1)],p=>{const r=topK([4,1,8,3,6,2,9,5],p.k);return{metrics:[m('후보 수',r.heap.length),m('후보 중 최솟값',r.heap[0]),m('힙 값 비교',r.comparisons)],steps:[`최대 ${p.k}개 유지`,`가득 차면 루트보다 큰 값으로 교체 후 아래로 이동합니다.`,`힙 배열 [${r.heap.join(',')}]`,`큰 순서 결과 [${r.values.join(',')}]`],matrix:{name:'Top-k 큰 순서',values:[r.values]}};},'힙 배열 전체는 정렬되어 있지 않습니다. 루트만 현재 후보의 최솟값이며 Top-k 토큰 선택에 같은 원리를 씁니다.'),
 'cs-strings':base('KMP의 겹치는 일치','텍스트=(ab를 n번 반복)+a, 패턴 aba 또는 ababa. prefix table은 패턴만으로 한 번 계산합니다.',[c('size','ab 반복 n',4,1,20,1),choice('pattern','패턴',0,['aba','ababa'])],p=>{const text='ab'.repeat(p.size)+'a',pattern=p.pattern?'ababa':'aba',r=kmp(text,pattern);return{metrics:[m('일치 수',r.matches.length),m('검색 문자 비교',r.comparisons),m('텍스트 길이',text.length)],steps:[`텍스트 ${text}, 패턴 ${pattern}`,`prefix=[${r.prefix.join(',')}]`,`시작 인덱스=[${r.matches.join(',')}]`],matrix:{name:'prefix table',values:[r.prefix]}};},'일치 이후 j를 0으로만 초기화하면 겹치는 일치를 놓칠 수 있습니다. Trie와 KMP는 다른 문제를 해결합니다.'),
 'cs-compute-graph':base('분기 그래프의 gradient 합','u=x²,v=ax,L=u+v. 두 경로가 x로 합쳐지는 스칼라 DAG이며 연산 노드를 수동으로 계산합니다.',[c('x','입력 x',2,-4,4),c('a','선형 경로 a',3,-4,4)],p=>({metrics:[m('L',p.x**2+p.a*p.x),m('dL/dx',2*p.x+p.a),m('dL/da',p.x)],steps:[`forward: u=${n(p.x**2)},v=${n(p.a*p.x)}`,`합 L=${n(p.x**2+p.a*p.x)}`,'backward: ∂L/∂u=∂L/∂v=1',`x로 두 경로를 합산: 2x+a=${n(2*p.x+p.a)}`],bars:[{label:'제곱 경로 gradient',value:2*p.x},{label:'선형 경로 gradient',value:p.a}]}),'x가 두 연산에 쓰여도 gradient는 마지막 경로로 덮어쓰지 않고 합산합니다. 위상 순서는 순환 없는 의존성에 적용합니다.'),
 'cs-matrix-compute':base('FLOPs와 타일 저장량','정사각 n×n 곱, 타일 t×t는 min(t,n). A·B·C 타일을 FP32로 동시에 보관하는 이상화된 저장량입니다. 커널·실행 시간은 측정하지 않습니다.',[c('size','행렬 n',16,2,128,1),c('tile','타일 t 요청',8,1,32,1)],p=>{const t=Math.min(p.tile,p.size);return{metrics:[m('곱셈',p.size**3),m('정확한 덧셈',p.size**2*(p.size-1)),m('근사 FLOPs',2*p.size**3),m('세 타일 bytes',3*t*t*4)],steps:[`각 출력은 n개 곱, n−1개 합`,`출력 ${p.size**2}개: 곱 ${p.size**3}, 합 ${p.size**2*(p.size-1)}`,`실제 t=${t}, 세 타일=3×t²×4=${3*t*t*4}bytes`],warning:'타일 크기만으로 가속을 보장하지 않습니다. 경계 처리·공유 메모리·대역폭·장치별 커널이 실제 속도를 결정합니다.'};},'타일링은 수학적 결과와 FLOPs를 바꾸지 않고 데이터를 재사용하는 순서를 바꿉니다.'),
};
