import { c, choice, m, n, average, type LessonModel } from './lessonModelTypes';
import { convSize, softmax } from './math';
const model=(title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});
export function fitPolynomial(xs:number[],ys:number[],degree:number){
  const size=degree+1,rows=Array.from({length:size},(_,i)=>Array.from({length:size+1},(_,j)=>j===size?xs.reduce((s,x,k)=>s+x**i*ys[k],0):xs.reduce((s,x)=>s+x**(i+j),0)));
  for(let i=0;i<size;i++){let pivot=i;for(let k=i+1;k<size;k++)if(Math.abs(rows[k][i])>Math.abs(rows[pivot][i]))pivot=k;[rows[i],rows[pivot]]=[rows[pivot],rows[i]];const div=rows[i][i];for(let j=i;j<=size;j++)rows[i][j]/=div;for(let k=0;k<size;k++)if(k!==i){const ratio=rows[k][i];for(let j=i;j<=size;j++)rows[k][j]-=ratio*rows[i][j];}}
  const coefficients=rows.map(row=>row[size]);return{coefficients,predict:(x:number)=>coefficients.reduce((s,w,i)=>s+w*x**i,0)};
}
export const designModels:Record<string,LessonModel>={
  'learning-paradigms':model('학습 신호는 어디에서 올까요?','자료 10건 중 n건에 사람이 붙인 정답이 있습니다. 자기지도는 각 문장에서 하나의 숨긴 목표, 강화학습은 각 경로에서 보상 하나를 얻는 단순 예제입니다. 신호의 개수가 품질을 뜻하지는 않습니다.',[c('labels','사람 정답이 있는 건수',3,0,10,1),choice('kind','학습 방식',0,['지도','비지도','자기지도','준지도','강화'])],p=>{const human=p.kind===0||p.kind===3?p.labels:0,internal=p.kind===2?10:p.kind===3?10-p.labels:0,reward=p.kind===4?10:0;return{metrics:[m('사람 정답 신호',human),m('자료 자체의 목표 신호',internal),m('환경 보상 신호',reward)],steps:[`입력 자료는 10건, 사람이 준 정답 ${p.labels}건`,`지도: 사람 정답 쌍 / 비지도: 별도의 목표 레이블 없이 구조 탐색`,`자기지도: 자료에서 목표를 구성 / 준지도: 레이블과 무레이블을 결합`,`강화: 행동의 결과인 환경 보상. 비지도학습의 하위 분류가 아닙니다.`]};},'학습 방식은 모델 구조가 아니라 목표 신호가 어디서 오는지로 구분합니다.'),
  'tensor-axes':model('같은 표에서 평균을 낼 축 선택','입력 [[1,2,3],[4,5,x]]를 [B=2,D=3]으로 해석합니다. Batch 축 평균은 feature별 평균, Feature 축 평균은 표본별 평균입니다.',[c('x','마지막 값',6,-2,10),choice('axis','평균 축',0,['dim=0: Batch','dim=1: Feature'])],p=>{const out=p.axis?[(1+2+3)/3,(4+5+p.x)/3]:[(1+4)/2,(2+5)/2,(3+p.x)/2];return{metrics:[m('출력 길이',out.length),m('첫 평균',out[0])],steps:['입력 shape=[2,3]',p.axis?'각 표본의 feature 3개를 평균합니다.':'각 feature의 표본 2개를 평균합니다.',`출력=[${out.map(n)}], shape=[${out.length}]`,'keepdim=True라면 줄어든 축을 크기 1로 남겨 방송 연산에 사용할 수 있습니다.'],matrix:{name:'입력 표: 행 Batch, 열 Feature',values:[[1,2,3],[4,5,p.x]]}};},'어느 축을 없애는지 먼저 말한 뒤 연산을 선택하세요.'),
  'shape-design':model('Conv→Pool→Flatten의 차원 추적','입력 [1,3,H,H], Conv 16채널 K=3 stride1 padding P, Pool K=2 stride2, Linear 128. 정사각 이미지·Bias 포함입니다.',[c('h','입력 H',32,8,64,1),c('padding','Conv padding',1,0,2,1)],p=>{const conv=convSize(p.h,3,1,p.padding),pool=convSize(conv,2,2,0),flat=16*pool**2,linear=flat*128+128;return{metrics:[m('Conv 공간 크기',conv),m('Pool 공간 크기',pool),m('Flatten feature',flat),m('Linear 파라미터',linear)],steps:[`Conv H=floor((${p.h}+2×${p.padding}−3)/1+1)=${conv}`,`Pool H=floor((${conv}−2)/2+1)=${pool}`,`Flatten=16×${pool}×${pool}=${flat}`,`Linear(${flat},128) params=${flat}×128+128=${linear}`]};},'padding 하나를 바꾸면 뒤의 Linear 파라미터까지 바뀝니다. 아래 편집기에서 레이어를 추가하고 skip 연결도 확인할 수 있습니다.'),
  'model-cost':model('가중치 밖의 학습 저장량','P백만 개의 FP32 파라미터, 같은 크기 FP32 Gradient, Adam 이동평균 두 개. 활성값은 A백만 FP32 원소로 별도 입력합니다. 피크 메모리·임시값·master weight·할당자 여유는 제외합니다.',[c('p','파라미터 백만 개',1,.1,20,.1),c('a','저장 활성값 백만 개',1,0,20,.1),choice('training','계산 모드',0,['학습: grad·Adam 포함','가중치와 활성값만'])],p=>{const weight=p.p*1e6*4/2**20,activ=p.a*1e6*4/2**20,total=weight*(p.training?1:4)+activ;return{metrics:[m('가중치',weight,'MiB'),m('Gradient+Adam 상태',p.training?0:3*weight,'MiB'),m('활성값',activ,'MiB'),m('항목 합계',total,'MiB')],steps:[`가중치=P×10⁶×4 bytes=${n(weight)}MiB`,`학습이면 Gradient 1배+Adam 상태 2배를 더합니다.`,`활성값=A×10⁶×4 bytes=${n(activ)}MiB`,`항목 합=${n(total)}MiB. 실제 GPU peak와 같다고 보장하지 않습니다.`]};},'Batch·시퀀스 길이는 활성값 비용을 바꾸지만 모델 가중치 수는 그대로일 수 있습니다.'),
  'curse-dimensionality':model('공간을 채우는 데 필요한 격자 수','축마다 k칸을 놓는 정육면체 격자, N개의 점을 균등하게 배치하는 평균 밀도 계산입니다. 실제 자료의 내재 차원·거리 분포는 따로 고려합니다.',[c('d','차원 D',2,1,8,1),c('k','축당 칸 수',10,2,10,1),c('n','표본 수 N',1000,100,10000,100)],p=>{const cells=p.k**p.d;return{metrics:[m('전체 격자 칸',cells),m('칸당 평균 표본',p.n/cells),m('격자 수 log10',Math.log10(cells))],steps:[`1차원은 ${p.k}칸`,`D축의 조합 수=kᴰ=${p.k}^${p.d}=${cells}`,`칸당 평균=N/kᴰ=${n(p.n/cells)}`,'빈 공간이 많아지면 가까운 이웃을 찾는 데 더 많은 자료가 필요할 수 있습니다. 실제 점이 낮은 차원 구조에 놓이면 이 계산은 과대 추정일 수 있습니다.']};},'차원을 한 단계씩 올려보세요. 레이어 shape를 맞추는 문제와 통계적으로 공간을 채우는 문제는 다릅니다.'),
  initialization:model('연결 수에 맞춘 초기 분산','독립·평균 0인 입력과 weight의 근사 분산 계산입니다. He는 ReLU의 절반 제곱 모멘트 효과, Xavier는 선형에 가까운 대칭 활성화를 가정합니다. 실제 학습 안정성을 보장하지 않습니다.',[c('in','Fan-in',100,10,1000,10),c('out','Fan-out',100,10,1000,10),choice('kind','초기화',0,['He 정규','Xavier 정규','고정 std=1'])],p=>{const v=p.kind===0?2/p.in:p.kind===1?2/(p.in+p.out):1,pre=p.in*v,post=p.kind===0?pre/2:pre;return{metrics:[m('Weight 분산',v),m('Weight 표준편차',Math.sqrt(v)),m('활성화 전 제곱 모멘트',pre),m('가정한 활성화 후 제곱 모멘트',post)],steps:[`weight 분산=${n(v)}`,`표준편차=√분산=${n(Math.sqrt(v))}`,`입력 분산 1일 때 합의 분산≈fan_in×Var(W)=${n(pre)}`,p.kind===0?'대칭 입력 ReLU의 출력 제곱 모멘트는 절반 ≈1. 평균이 0이 아니므로 이것을 그대로 분산이라고 부르지 않습니다.':'활성화에 따른 변화는 별도이며 이 결과는 선형 단계의 분산입니다.']};},'고정 std=1과 fan-in에 맞춘 std를 비교하세요. 깊은 층에서 반복될 때 차이가 커질 수 있습니다.'),
  'training-stability':model('Gradient 방향을 유지하는 Norm clipping','gradient g=[3,4], clip norm c. 별도로 동일 scalar Jacobian j가 L층 반복될 때의 곱을 계산합니다. 실제 네트워크의 Jacobian은 행렬입니다.',[c('clip','최대 Gradient norm',2,.1,8,.1),c('j','층당 Jacobian 배율',1.2,.1,2,.1),c('layers','층 수',5,1,20,1)],p=>{const scale=Math.min(1,p.clip/5),clipped=[3*scale,4*scale];return{metrics:[m('Clipping 전 norm',5),m('Clipping 후 norm',Math.hypot(...clipped)),m('반복 미분 배율',p.j**p.layers)],steps:['||[3,4]||=√(9+16)=5',`곱할 비율=min(1,c/5)=${n(scale)}`,`새 gradient=[${clipped.map(n)}]`,`scalar 연쇄 곱=${n(p.j)}^${p.layers}=${n(p.j**p.layers)}. 1보다 작으면 반복 소실, 크면 반복 증폭`],matrix:{name:'행: 원래 Gradient / Clip Gradient',values:[[3,4],clipped]}};},'clipping은 업데이트에 쓰는 Gradient를 제한합니다. 초기화·Residual·정규화·학습률을 대신하는 만능 해결책은 아닙니다.'),
  optimizers:model('같은 Gradient에 다른 갱신 규칙','w=2,g=4, 이전 momentum=2, Adam 1·2차 상태=0. β₁=0.9, β₂=0.999, Adam의 첫 step 편향 보정. 같은 초기 조건의 단일 update를 비교합니다.',[c('rate','학습률 η',.1,0,.5,.01),c('decay','AdamW decay λ',.01,0,.5,.01),choice('kind','업데이트',0,['SGD','Momentum β=0.9','AdamW 첫 step'])],p=>{const velocity=.9*2+4,adamM=.1*4,adamV=.001*16,update=p.kind===0?4:p.kind===1?velocity:(adamM/(1-.9))/(Math.sqrt(adamV/(1-.999))+1e-8),next=2-p.rate*update-(p.kind===2?p.rate*p.decay*2:0);return{metrics:[m('업데이트 방향·크기',update),m('다음 w',next)],steps:['현재 w=2, 현재 gradient=4',p.kind===0?'SGD는 gradient 4를 그대로 사용':p.kind===1?`Momentum v=0.9×2+4=${n(velocity)}`:'Adam m=0.4,v=0.016 → 첫 step 보정 m̂=4,v̂=16',`w새=2−η×${n(update)}${p.kind===2?'−ηλ×2':''}=${n(next)}`,'Momentum은 기존 상태가 있고 AdamW는 첫 step입니다. 숫자 비교를 성능 우열로 해석하지 않습니다.']};},'AdamW의 decay를 바꿔보세요. 이 항은 적응적 Gradient 분모로 나누지 않고 별도로 적용됩니다.'),
  'learning-rate':model('학습률 경로가 만드는 실제 반복','L=x²/2, x초기=2, 12 step. 고정률 또는 4 step warmup 뒤 선형 감소를 선택합니다. 특정 함수의 결정적 경로입니다.',[c('rate','기준 학습률',.5,0,2.5,.05),choice('schedule','스케줄',0,['고정','4 step warmup 후 선형 감소'])],p=>{let x=2;const history=[x],rates:number[]=[];for(let t=1;t<=12;t++){const rate=p.rate*(p.schedule?(t<=4?t/4:(12-t)/8):1);rates.push(rate);x-=rate*x;history.push(x);}return{metrics:[m('최종 x',x),m('최종 손실',x*x/2),m('마지막 학습률',rates.at(-1)!)],steps:['Gradient는 x. 따라서 매 step x새=(1−ηₜ)x',`학습률 경로=[${rates.map(n)}]`,`x 경로=[${history.map(n)}]`,'고정률 0<η<2이면 이 함수에서 |x|가 감소합니다. 일반 모델의 한계값으로 사용하지 마세요.'],bars:rates.map((value,i)=>({label:`step ${i+1} η`,value}))};},'학습률 2에서 진동하고 2.1에서는 발산하는 모습을 비교하세요.'),
  'numerical-stability':model('큰 Logit에서 직접 exp와 안정 계산','logits [s,s+1]. JavaScript는 float64 계산이며 FP16/BF16 하드웨어 동작을 시뮬레이션하지 않습니다. 같은 상수 이동에 확률은 불변입니다.',[c('shift','공통 이동 s',1000,0,1000,10)],p=>{const z=[p.shift,p.shift+1],probs=softmax(z),direct=Math.exp(z[1]),lse=p.shift+1+Math.log1p(Math.exp(-1));return{metrics:[m('안정 첫 확률',probs[0]),m('안정 둘째 확률',probs[1]),m('LogSumExp',lse),m('직접 exp(s+1)',Number.isFinite(direct)?direct:null)],steps:[`logits=[${z}]`,`최대값 ${z[1]}을 빼면 [−1,0]`,`확률=[${probs.map(n)}]`,`LogSumExp=max+log(exp(−1)+1)=${n(lse)}`],warning:Number.isFinite(direct)?undefined:'직접 exp는 overflow했습니다. 최댓값을 뺀 계산은 유한한 확률을 유지합니다.'};},'공통 이동을 바꿔도 확률은 같습니다. AMP의 손실 스케일링은 이 Softmax 안정화와 별개의 연산 범위 관리입니다.'),
  generalization:model('훈련 점과 새 점의 오차를 직접 계산','진짜 함수 y=x². 훈련 x=[−1,−⅓,⅓,1]에 잡음 [0,+a,−a,0]를 추가합니다. 최소제곱으로 다항식을 fit하고 잡음 없는 새 위치 21개에서 평가합니다.',[choice('degree','다항식 차수',2,['0','1','2','3']),c('noise','훈련 잡음 크기 a',.4,0,1,.05)],p=>{const xs=[-1,-1/3,1/3,1],ys=xs.map((x,i)=>x*x+([0,1,-1,0][i])*p.noise),fit=fitPolynomial(xs,ys,p.degree),train=average(xs.map((x,i)=>(fit.predict(x)-ys[i])**2)),testXs=Array.from({length:21},(_,i)=>-1+(i+.5)*2/21),test=average(testXs.map(x=>(fit.predict(x)-x*x)**2));return{metrics:[m('훈련 MSE',train),m('새 점 MSE',test),m('새 점−훈련 gap',test-train)],steps:[`훈련 정답=[${ys.map(n)}]`,`최소제곱 계수(상수부터)=[${fit.coefficients.map(n)}]`,`훈련 오차=${n(train)}, 별도 21개 위치 오차=${n(test)}`,'새 점의 정답은 잡음 없는 x²입니다. 실제 일반화 오차와 같은 분포의 독립 평가를 구분해야 합니다.'],matrix:{name:'행: 훈련 x / 관측 y / 모델 예측',values:[xs,ys,xs.map(fit.predict)]}};},'잡음을 넣은 뒤 차수 2와 3을 비교하세요. 훈련 오차 0이 새 위치에서도 좋은가요?'),
  'validation-leakage':model('평균을 어디에서 fit했나요?','훈련 [0,2], 검증 [v,v+2]. 평균을 빼는 전처리. 자료 전체 fit과 train-only fit의 차이만 보여주며 평가 성능을 만들어내지 않습니다.',[c('v','검증 첫 값',10,0,20,1),choice('fit','평균 fit 대상',0,['훈련만','훈련+검증: 누수'])],p=>{const mean=p.fit?(2+2*p.v+2)/4:1,train=[-mean,2-mean],valid=[p.v-mean,p.v+2-mean];return{metrics:[m('사용 평균',mean),m('변환 훈련 평균',average(train)),m('변환 검증 평균',average(valid))],steps:['훈련 평균=(0+2)/2=1',`검증=[${p.v},${p.v+2}]`,`fit한 평균=${n(mean)}`,`훈련 변환=[${train.map(n)}], 검증 변환=[${valid.map(n)}]`],warning:p.fit?'평균에 검증 자료가 들어갔습니다. fold마다 전처리를 해당 훈련 자료에서 다시 fit해야 합니다.':undefined};},'검증 값만 바꿔보세요. train-only 전처리의 평균은 변하지 않아야 합니다.'),
  'metrics-imbalance':model('혼동행렬에서 지표를 읽기','이진 결과 TP,FP,FN,TN을 직접 입력합니다. 분모가 0인 지표는 미정의로 표시하며 여기서 임계값을 직접 시뮬레이션하지 않습니다.',[c('tp','TP',8,0,30,1),c('fp','FP',2,0,30,1),c('fn','FN',4,0,30,1),c('tn','TN',16,0,100,1)],p=>{const total=p.tp+p.fp+p.fn+p.tn;return{metrics:[m('Accuracy',total?(p.tp+p.tn)/total:null),m('Precision',p.tp+p.fp?p.tp/(p.tp+p.fp):null),m('Recall',p.tp+p.fn?p.tp/(p.tp+p.fn):null),m('F1',2*p.tp+p.fp+p.fn?2*p.tp/(2*p.tp+p.fp+p.fn):null)],steps:[`전체=${total}`,`Precision=TP/(TP+FP)=${p.tp}/(${p.tp}+${p.fp})`,`Recall=TP/(TP+FN)=${p.tp}/(${p.tp}+${p.fn})`,`F1=2TP/(2TP+FP+FN)`],matrix:{name:'행: 실제 양성/음성, 열: 예측 양성/음성',values:[[p.tp,p.fn],[p.fp,p.tn]]}};},'TN을 크게 늘려도 Recall은 같지만 Accuracy는 바뀝니다. 지표가 답하는 질문을 구분하세요.'),
  'calibration-debugging':model('확률과 실제 양성 비율을 비교하기','100개 표본 모두 양성 확률 p를 예측했습니다. 이 집단에서 실제 양성 s개. 이진 확률 보정과 Brier 점수를 계산합니다.',[c('p','예측 양성 확률',.9,.01,.99,.01),c('s','실제 양성 수',60,0,100,1)],p=>{const freq=p.s/100,brier=freq*(1-p.p)**2+(1-freq)*p.p**2;return{metrics:[m('관측 양성 비율',freq),m('확률−관측 차이',p.p-freq),m('Brier 점수',brier)],steps:[`관측 빈도=s/100=${n(freq)}`,`양성 표본 오차=(p−1)²=${n((p.p-1)**2)}`,`음성 표본 오차=p²=${n(p.p**2)}`,`Brier=빈도×양성오차+(1−빈도)×음성오차=${n(brier)}`],bars:[{label:'예측 p',value:p.p},{label:'관측 빈도',value:freq}]};},'예측 확률이 관측 빈도와 같아도 개별 결과의 Brier가 0인 것은 아닙니다.'),
  'transfer-learning':model('고정할 파라미터와 Module 모드','Backbone 100만 개, head H천 개. requires_grad 설정과 Backbone의 eval을 별도로 선택합니다. 전체 모델에서 gradient가 필요한 계산 경로는 별도입니다.',[c('h','Head 천 개',10,1,100,1),choice('freeze','Backbone 업데이트',0,['Freeze','학습 허용']),choice('mode','Backbone 모드',0,['eval','train'])],p=>({metrics:[m('전체 파라미터',1e6+p.h*1000),m('학습 가능한 파라미터',(p.freeze?1e6:0)+p.h*1000),m('Backbone BN running 통계 갱신',Number(p.mode===1))],steps:['Backbone 파라미터=1,000,000개',`Head=${p.h*1000}개, 학습 허용`,`Backbone requires_grad=${Boolean(p.freeze)} → 업데이트 대상 ${p.freeze?1000000:0}개`,`Backbone ${p.mode?'train: BN 통계가 갱신될 수 있음':'eval: BN은 저장 통계를 사용'}. Freeze와 모드는 별도입니다.`]}),'freeze 상태에서 train을 선택해 보세요. weight를 고정해도 running buffer가 바뀔 수 있습니다.'),
};
