import { c, choice, m, n, average, variance, sigmoid, random, type LessonModel } from './lessonModelTypes';
import { convSize, gelu, layerNorm, softmax } from './math';
import { initialGan, ganLoss, ganStep } from './experiments';
const base = (title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});
export const dlModels:Record<string,LessonModel> = {
 'neural-network':base('한 뉴런의 순전파와 역전파','x→z=xw+1→sigmoid→L=(h−1)²/2. 목표1의 한 뉴런 예제입니다.',[c('x','입력 x',2,-3,3),c('w','가중치 w',1,-3,3)],p=>{const z=p.x*p.w+1,h=sigmoid(z),g=(h-1)*h*(1-h)*p.x;return{metrics:[m('출력 h',h),m('손실',(h-1)**2/2),m('가중치 Gradient',g)],steps:[`z=xw+1=${n(z)}`,`h=σ(z)=${n(h)}`,`∂L/∂h=h−1=${n(h-1)}`,`∂L/∂w=(h−1)h(1−h)x=${n(g)}`]};},'큰 양의 z에서 출력은 1에 가깝고 Gradient는 작습니다. 입력 x=0이면 w의 Gradient가 어떻게 되는지 보세요.'),
 activation:base('비선형 함수의 값과 미분','입력 x에 선택한 원소별 함수를 적용합니다. GELU는 tanh 근사, 변화율은 중앙차분입니다.',[c('x','입력 x',1,-5,5),choice('mode','활성화',0,['ReLU','Leaky ReLU','tanh','Sigmoid','GELU','SiLU'])],p=>{const functions=[(x:number)=>Math.max(0,x),(x:number)=>x>=0?x:.1*x,Math.tanh,sigmoid,gelu,(x:number)=>x*sigmoid(x)],f=functions[p.mode],y=f(p.x),g=(f(p.x+1e-4)-f(p.x-1e-4))/2e-4;return{metrics:[m('함수 출력',y),m('국소 미분',p.x===0&&p.mode<2?null:g)],steps:[`입력=${n(p.x)},출력=${n(y)}`,`국소 미분 ≈ [φ(x+h)−φ(x−h)]/(2h)=${n(g)}`,'h=0.0001. ReLU 계열의 0은 좌우 기울기가 달라 정확 미분이 없습니다.']};},'같은 x에서 함수와 미분을 비교하고 포화 영역으로 옮겨보세요.'),
 softmax:base('후보가 서로 경쟁하는 확률','세 logit [z,1,0],정답은 첫 후보. τ는 양수입니다.',[c('z','첫 logit',2,-4,5),c('temp','온도 τ',1,.1,3)],p=>{const ps=softmax([p.z,1,0],p.temp);return{metrics:[m('첫 후보 확률',ps[0]),m('정답 손실',-Math.log(ps[0])),m('확률 합',ps.reduce((a,b)=>a+b,0))],steps:[`점수/온도=[${[p.z,1,0].map(v=>n(v/p.temp))}]`,'최댓값을 빼 지수값을 안정적으로 계산합니다.',`정규화 확률=[${ps.map(n)}]`,`손실=−log p첫=${n(-Math.log(ps[0]))}`],bars:ps.map((value,i)=>({label:`후보 ${i+1}`,value}))};},'첫 점수를 올리면 다른 후보의 확률도 바뀝니다. 온도는 순서가 아니라 집중도를 바꿉니다.'),
 'linear-embedding':base('변환과 표 조회의 파라미터 수','Linear는 Bias 사용, Embedding은 별도 bias 없음. 입력 길이 5, 배치 크기 2를 가정합니다.',[c('input','Linear 입력 feature',4,1,32,1),c('out','출력·Embedding D',3,1,32,1),c('vocab','어휘 V',10,2,100,1)],p=>({metrics:[m('Linear 파라미터',p.input*p.out+p.out),m('Embedding 파라미터',p.vocab*p.out),m('Embedding 출력 원소',2*5*p.out)],steps:[`Linear:${p.input}×${p.out}+${p.out}`,`Embedding 표:${p.vocab}행×${p.out}열`,'정수 ID [2,5]를 조회합니다.',`출력 [2,5,${p.out}],표의 크기는 길이 5와 무관합니다.`]}),'입력 길이와 어휘 수를 다른 축으로 구분하고 계산기에서 feature를 바꿔보세요.'),
 'tensor-connections':base('Reshape·Concat·Add의 조건','배치 크기 2, 표현 A=[2,a],B=[2,b]. Concat은 축 1, Add는 정확한 shape 일치을 요구합니다.',[c('a','A feature',12,1,32,1),c('b','B feature',5,1,32,1),c('target','Reshape 목표 feature',12,1,32,1)],p=>({metrics:[m('A 원소 수',2*p.a),m('Concat feature',p.a+p.b),m('Add 가능',p.a===p.b?1:0),m('Reshape 가능',p.a===p.target?1:0)],steps:[`A [2,${p.a}],B [2,${p.b}]`,`Concat [2,${p.a+p.b}]`,p.a===p.b?'Add는 같은 위치의 값을 더합니다.':'Add 불일치:다른 feature 수',p.a===p.target?'배치를 유지한 목표 shape의 원소 수가 같습니다.':'배치를 유지한 Reshape의 원소 수가 달라 불가'],warning:p.a!==p.b?'B feature를 A와 맞추면 Add 조건이 바뀝니다.':undefined}),'다른 연결 연산은 다른 크기 조건을 가집니다. 허용 여부1·0은 값의 의미가 올바른지까지 보장하지 않습니다.'),
 cnn:base('작은 커널의 실제 곱과 공간 크기','1채널의 입력 창 [[1,2,3],[0,1,2],[2,0,1]],커널 [[w,0,−w],[w,0,−w],[w,0,−w]]. 슬라이더 하나로 커널의 여러 값을 함께 조절하는 예제입니다. 일반 Conv의 9개 weight와 bias는 독립 파라미터입니다. 공간 크기는 정사각 Conv2d, K=3, D=1.',[c('w','커널 배율 w',1,-2,2),c('height','입력 공간 H',7,3,32,1),c('stride','Stride S',1,1,3,1),c('pad','Padding P',0,0,2,1)],p=>{const h=convSize(p.height,3,p.stride,p.pad),kernel=[[p.w,0,-p.w],[p.w,0,-p.w],[p.w,0,-p.w]],out=-3*p.w;return{metrics:[m('창의 곱합',out),m('출력 높이',h),m('1입력·1출력 파라미터',10)],steps:[`왼 열 가중합=(1+0+2)×${n(p.w)}`,`오른 열 가중합=(3+2+1)×${n(-p.w)}`,`합=${n(out)}. 모든 공간에서 같은 커널을 씁니다.`,`Hout=floor((${p.height}+2×${p.pad}−3)/${p.stride})+1=${h}`],matrix:{name:'실제 적용 커널',values:kernel}};},'커널값은 출력값을 바꾸고 Stride·Padding은 출력 위치 수를 바꿉니다.'),
 'pooling-upsampling':base('최대·평균과 보간','창 [[1,2],[3,x]]. Nearest·linear는 끝점 1과 x 사이 중간값을 비교합니다.',[c('x','창 마지막 값',4,-4,8),choice('mode','집계',0,['Max','Average'])],p=>{const xs=[1,2,3,p.x],max=Math.max(...xs),mean=average(xs);return{metrics:[m('선택한 Pool 출력',p.mode===0?max:mean),m('Max',max),m('Average',mean),m('선형 중간 보간',(1+p.x)/2)],steps:[`창=[${xs.map(n)}]`,`Max=${n(max)},Average=합/4=${n(mean)}`,`Nearest의 중간 선택은 좌표 규칙에 의존, Linear 중간=${n((1+p.x)/2)}`,'집계로 잃은 각각의 원래 값은 확대만으로 돌아오지 않습니다.'],matrix:{name:'입력 창',values:[[1,2],[3,p.x]]}};},'x를 큰 값으로 바꾸면 Max는 그 하나에 의존하고 Average는 모든 원소에 의존합니다.'),
 normalization:base('같은 벡터의 LayerNorm과 RMSNorm','x=[1,2,x₃],γ=1,β=0,ε=10⁻⁵. 아래 표는 선택한 토큰 내 feature 정규화입니다.',[c('x','세 번째 feature',3,-5,5),choice('mode','정규화',0,['LayerNorm','RMSNorm'])],p=>{const xs=[1,2,p.x],rms=Math.sqrt(average(xs.map(x=>x*x))+1e-5),ln=layerNorm(xs),out=p.mode===0?ln.output:xs.map(x=>x/rms);return{metrics:[m('입력 평균',ln.mean),m('입력 분산',ln.variance),m('출력 평균',average(out)),m('출력 분산',variance(out))],steps:[`μ=${n(ln.mean)},σ²=${n(ln.variance)}`,p.mode===0?'LayerNorm:평균을 빼고 √(분산+ε)로 나눕니다.':`RMSNorm:평균을 빼지 않고 RMS=${n(rms)}로 나눕니다.`,`출력=[${out.map(n)}]`],matrix:{name:'행1:입력 / 행2:정규화',values:[xs,out]}};},'LayerNorm은 평균을 0으로 옮기지만 RMSNorm은 그렇지 않습니다. BatchNorm의 축 차이는 본문과 아래 추가 설명을 연결하세요.'),
 dropout:base('한 마스크와 반복 평균','값 x를 갖는 원소 8개에 원소별 inverted dropout. 같은 seed는 같은 난수열,새 seed는 다른 마스크입니다.',[c('x','입력값',2,-4,4),c('p','제거 확률',.5,0,.9,.05),c('seed','마스크 seed',7,1,40,1),choice('mode','모드',0,['train','eval'])],p=>{const rng=random(p.seed),out=Array.from({length:8},()=>p.mode? p.x:rng()<p.p?0:p.x/(1-p.p));const empirical=average(Array.from({length:1000},()=>p.mode?p.x:rng()<p.p?0:p.x/(1-p.p)));return{metrics:[m('이 8개 평균',average(out)),m('이론 기대값',p.x),m('1000회 평균',empirical)],steps:[`유지 확률=${n(1-p.p)},살아남은 값=${n(p.x/(1-p.p))}`,p.mode?'eval:무작위 제거 없이 입력 그대로':'train:마스크마다 0 또는 확대값',`출력=[${out.map(n)}]`,'반복 평균과 한 번 출력은 다릅니다.'],matrix:{name:'8개 Dropout 출력',values:[out]}};},'제거율·seed·모드를 바꾸어 기대값 보존과 한 번의 변동을 구분해 보세요.'),
 'rnn-lstm-gru':base('반복 상태와 LSTM cell 게이트','스칼라 RNN 5시점, 입력 [1,0,0,0,0],h₀=0. 별도의 LSTM c 갱신은 c이전=2, 후보=1을 가정.',[c('w','재귀 가중치 Wₕ',.5,-2,2),c('forget','망각 게이트 f',.8,0,1,.05),c('input','입력 게이트 i',.1,0,1,.05)],p=>{let h=0;const hs=[1,0,0,0,0].map(x=>h=Math.tanh(x+p.w*h));return{metrics:[m('마지막 RNN 상태',h),m('LSTM 새 cell',2*p.forget+p.input)],steps:['h₀=0, 각 시점 h=tanh(x+Wₕh이전)',`h 경로=[${hs.map(n)}]`,`LSTM cell=2f+1i=${n(2*p.forget+p.input)}`,'LSTM cell 예제는 RNN 경로와 별도의 게이트 계산입니다.'],matrix:{name:'RNN 시간별 상태',values:[hs]}};},'재귀 가중치가 작은 경우 상태가 줄고 게이트 f=1,i=0에서는 cell을 그대로 보존합니다.'),
 gnn:base('이웃 집계와 메시지 전달','노드값 [1,2,x],중앙은 첫 노드. 이웃 1 또는 2개를 선택해 mean/sum 집계 후 ReLU.',[c('x','두 번째 이웃 값',4,-4,8),choice('count','연결',1,['첫 이웃만','두 이웃']),choice('mode','집계',0,['평균','합'])],p=>{const neigh=p.count?[2,p.x]:[2],agg=p.mode?neigh.reduce((a,b)=>a+b,0):average(neigh),out=Math.max(0,1+agg);return{metrics:[m('이웃 집계',agg),m('새 중앙 표현',out),m('이웃 수',neigh.length)],steps:[`연결된 이웃=[${neigh.map(n)}]`,`집계=${n(agg)}`,`자신 1+이웃=${n(1+agg)}`,`ReLU 출력=${n(out)}`],matrix:{name:'자신과 이웃 feature',values:[[1,2,p.x]]}};},'연결을 끊으면 그 이웃의 값이 중앙 표현에 미치는 영향도 사라집니다.'),
 autoencoder:base('평균 병목으로 압축·복원','선형 Encoder z=(x₁+x₂)/2,Decoder[z,z]. 정해진 병목의 정보손실을 보여주며 신경망을 학습하지 않습니다.',[c('x','첫 성분',1,-4,4),c('y','둘째 성분',2,-4,4),c('noise','입력 잡음',0,-2,2)],p=>{const z=(p.x+p.noise+p.y)/2,recon=[z,z],loss=((p.x-z)**2+(p.y-z)**2)/2;return{metrics:[m('잠재 z',z),m('복원 MSE',loss)],steps:[`손상입력=[${n(p.x+p.noise)},${n(p.y)}]`,`Encoder평균=${n(z)}`,`Decoder 복원=[${n(z)},${n(z)}]`,`깨끗한 목표와 MSE=${n(loss)}`],matrix:{name:'행1:원본 / 행2:복원',values:[[p.x,p.y],recon]}};},'두 성분 차이가 커지면 평균만 남긴 병목의 오차가 커집니다. 잡음은 입력에만 더해집니다.'),
 vae:base('재매개화와 Gaussian KL','1차원 q=N(μ,σ²), prior=N(0,1). ε는 주어진 표준잡음 한 표본이며 Decoder 복원 학습은 별도입니다.',[c('mean','평균 μ',1,-3,3),c('std','표준편차 σ',2,.1,3),c('noise','잡음 표본 ε',.5,-3,3)],p=>{const z=p.mean+p.std*p.noise,kl=(p.mean**2+p.std**2-1-Math.log(p.std**2))/2;return{metrics:[m('잠재 표본 z',z),m('prior와 KL',kl),m('∂z/∂μ',1),m('∂z/∂σ',p.noise)],steps:[`분산=σ²=${n(p.std**2)}`,`z=μ+σε=${n(z)}`,`KL=(μ²+σ²−1−lnσ²)/2=${n(kl)}`,'ε를 고정하면 μ·σ로 미분할 수 있습니다.']};},'μ=0,σ=1에서 KL이 0입니다. σ와 σ²를 구분하세요.'),
 gan:base('교대 Gradient 업데이트','고정한 잡음 7개·진짜 표본 7개의 1차원 선형 GAN. 각 라운드는 D 이후 G를 한 번씩 업데이트합니다.',[c('rounds','학습 라운드',0,0,40,1),c('rate','학습률',.1,.01,.3,.01)],p=>{let state=initialGan();for(let i=0;i<p.rounds;i++){state=ganStep(state,'d',p.rate);state=ganStep(state,'g',p.rate);}const d=ganLoss(state);return{metrics:[m('D 손실',d.dLoss),m('G 손실',d.gLoss),m('생성 평균',state.mean),m('생성 스케일',state.scale)],steps:[`D 업데이트: ${p.rounds}회,G 업데이트: ${p.rounds}회`,`G(z)=${n(state.mean)}+${n(state.scale)}z`,`D(x)=sigmoid(${n(state.a)}x+${n(state.b)})`,'상대 모델이 바뀌면 두 목적함수가 함께 움직이며 단조 감소를 보장하지 않습니다.'],matrix:{name:'행1:진짜 / 행2:생성표본',values:[d.real,d.fake]}};},'라운드를 늘리며 두 손실과 생성 표본을 함께 확인하세요. 아래 추가 실험에서는 G·D를 따로 갱신할 수 있습니다.'),
 'gan-stability':base('mode 누락과 제한된 critic','실제 [-2,2],생성 [−m,m]또는 한 mode [m,m]. f(x)=a x이며 |a|≤1. 이 선형 critic은 같은 평균의 분포 차이를 구별하지 못합니다.',[c('mean','생성 위치 m',2,0,3),choice('collapse','생성 분포',1,['양쪽 mode','한 mode']),c('a','critic 기울기 a',-1,-1,1)],p=>{const fake=p.collapse?[p.mean,p.mean]:[-p.mean,p.mean],gap=-p.a*average(fake);return{metrics:[m('critic 평균차',gap),m('생성 평균',average(fake)),m('생성 분산',variance(fake))],steps:['실제mean=0,variance=4',`생성=[${fake.map(n)}]`,`Ereal f−Efake f=${n(gap)}`,'선형 critic만으로 Wasserstein 최적값을 구한 것은 아닙니다.'],matrix:{name:'행1:실제 / 행2:생성',values:[[-2,2],fake]}};},'생성 m=0에서 같은 평균을 보세요. 선형 평균 차이 0이 완전한 분포 일치를 뜻하지 않습니다.'),
 diffusion:base('원본·잡음의 혼합과 한 시점 복원','x₀=1,ε=−1. ᾱ>0이며 예측 잡음 ε̂로 원본을 대수적으로 추정합니다. 학습한 생성 샘플러가 아닙니다.',[c('alpha','누적 신호 ᾱ',.64,.01,1,.01),c('pred','예측 잡음 ε̂',-.8,-2,2)],p=>{const signal=Math.sqrt(p.alpha),noise=Math.sqrt(1-p.alpha),xt=signal-noise,recon=(xt-noise*p.pred)/signal;return{metrics:[m('잡음 입력 xₜ',xt),m('추정 원본',recon),m('잡음 MSE',(p.pred+1)**2)],steps:[`신호계수=${n(signal)},잡음계수=${n(noise)}`,`xₜ=${n(signal)}×1+${n(noise)}×(−1)=${n(xt)}`,`x̂₀=(xₜ−잡음계수×ε̂)/신호계수=${n(recon)}`]};},'ε̂=−1이면 정확한 잡음을 알아 원본 1을 복구합니다. 낮은 ᾱ에서는 예측 오차가 증폭됩니다.'),
 'contrastive-learning':base('positive와 negative의 경쟁','후보 둘의 유사도 logits, 첫 후보가 positive. 전체 SimCLR 배치·학습은 아닙니다.',[c('pos','Positive 점수',2,-2,4),c('neg','Negative 점수',1,-2,4),c('temp','온도 τ',1,.1,2)],p=>{const ps=softmax([p.pos,p.neg],p.temp);return{metrics:[m('Positive 확률',ps[0]),m('InfoNCE 손실',-Math.log(ps[0]))],steps:[`온도 적용 점수=[${n(p.pos/p.temp)},${n(p.neg/p.temp)}]`,`Positive 확률=${n(ps[0])}`,`손실=−log Positive=${n(-Math.log(ps[0]))}`],bars:ps.map((value,i)=>({label:i?'negative':'positive',value}))};},'Positive가 낮은 상태에서 온도를 낮추면 어떤 손실이 되는지 비교하세요.'),
 'masked-learning':base('loss에 포함되는 위치','4개 위치의 target 확률[p,0.8,0.5,0.8]. 앞 두 위치만 가리거나 뒤 두 위치만 가립니다. 실제 언어 모델은 아닙니다.',[c('p','첫 정답 확률',.8,.05,.95,.05),choice('mask','가린 위치',1,['앞 두 위치','뒤 두 위치','전부'])],p=>{const ps=[p.p,.8,.5,.8],mask=p.mask===0?[1,1,0,0]:p.mask===1?[0,0,1,1]:[1,1,1,1],losses=ps.map((v,i)=>mask[i]*-Math.log(v)),count=mask.reduce((a,b)=>a+b,0),loss=losses.reduce((a,b)=>a+b,0);return{metrics:[m('손실 합',loss),m('유효 위치 평균',loss/count),m('유효 위치 수',count)],steps:[`mask=[${mask}]`,`위치 손실=[${losses.map(n)}]`,`평균=합/${count}=${n(loss/count)}`],matrix:{name:'행1:확률 / 행2:mask / 행3:위치 손실',values:[ps,mask,losses]}};},'mask=0인 첫 위치의 확률을 바꿔도 loss가 변하지 않습니다. 입력 문맥 제거와 loss 제외는 다릅니다.'),
};
