import { c, choice, m, n, average, sigmoid, type LessonModel } from './lessonModelTypes';
import { softmax } from './math';
import { cosine, retrieve } from './experiments';
const model=(title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});
export function samplingDistribution(z:number[],temperature:number,k:number,topP:number){
  const probs=softmax(z,temperature),rank=probs.map((v,i)=>({v,i})).sort((a,b)=>b.v-a.v).slice(0,k);let total=0;
  const keep=rank.filter((v,i)=>{const accepted=i===0||total<topP;total+=v.v;return accepted;});const denom=keep.reduce((s,v)=>s+v.v,0);
  return probs.map((_,i)=>{const v=keep.find(v=>v.i===i);return v?v.v/denom:0;});
}
export const llmModels:Record<string,LessonModel>={
  'llm-basics':model('연속된 토큰의 조건부 확률','선택한 세 토큰의 조건부 확률 [0.8,0.5,p]. 실제 언어 모델이 아닌, 주어진 확률을 곱하는 계산입니다.',[c('p','세 번째 토큰 확률',.25,.01,1,.01),c('vocab','어휘 크기 V',10,3,100,1),c('length','문맥 길이 T',4,1,16,1)],p=>{const ps=[.8,.5,p.p],joint=ps.reduce((a,b)=>a*b,1);return{metrics:[m('세 토큰 결합 확률',joint),m('평균 음의 log 확률',-average(ps.map(Math.log))),m('Logit 원소 수 B=1',p.vocab*p.length)],steps:[`P(선택한 순서)=0.8×0.5×${n(p.p)}=${n(joint)}`,`로그에서는 log0.8+log0.5+logp=${n(Math.log(joint))}`,`[1,T,V]=[1,${p.length},${p.vocab}], 원소 ${p.length*p.vocab}개`,`각 위치의 V 후보는 확률 합이 1. 시퀀스 확률과 후보 확률을 구분합니다.`],bars:ps.map((value,i)=>({label:`선택 토큰 ${i+1} 확률`,value}))};},'길이를 곱해 텐서 크기를 구하는 계산과 조건부 확률을 곱하는 계산은 다른 의미입니다.'),
  'llm-generation':model('온도와 후보 제한 후 재정규화','logits [2,1,0,−1], Top-k 이후 원래 분포의 누적 확률로 Top-p를 적용합니다. 구현에 따라 필터 결합 순서가 달라질 수 있습니다.',[c('temp','온도 τ',1,.1,3,.1),c('k','Top-k',4,1,4,1),c('top','Top-p',1,.1,1,.01)],p=>{const base=softmax([2,1,0,-1],p.temp),probs=samplingDistribution([2,1,0,-1],p.temp,p.k,p.top),entropy=-probs.reduce((s,v)=>s+(v?v*Math.log(v):0),0);return{metrics:[m('첫 후보 확률',probs[0]),m('남은 후보 수',probs.filter(v=>v>0).length),m('샘플링 엔트로피',entropy)],steps:[`온도 적용 확률=[${base.map(n)}]`,`높은 순서로 최대 ${p.k}개를 남깁니다.`,`최소 한 후보, 누적 확률 ${n(p.top)}에 도달하는 후보까지 포함`,`다시 합 1로 정규화=[${probs.map(n)}]`],bars:probs.map((value,i)=>({label:`후보 ${i+1}`,value}))};},'최상위 후보가 Top-p를 이미 넘으면 한 후보만 남습니다. 온도는 새로운 지식을 만들지 않습니다.'),
  prompting:model('문맥 예산을 실제로 배분하기','문맥 한도 4096. 지시·예시·질문·예약 출력은 각각 입력하는 토큰 수이며 실제 토크나이저 실행은 아닙니다.',[c('instruction','지시 토큰',300,0,1200,10),c('examples','예시 토큰',500,0,1600,10),c('question','질문 토큰',100,0,1000,10),c('output','예약 출력',500,0,2000,10)],p=>{const used=p.instruction+p.examples+p.question+p.output,remaining=4096-used;return{metrics:[m('자료에 남는 예산',Math.max(0,remaining),'토큰'),m('초과량',Math.max(0,-remaining),'토큰')],steps:[`지시+예시+질문=${used-p.output}토큰`,`예약 출력=${p.output}토큰`,`자료 예산=4096−${used}=${remaining}`,remaining<0?'문맥 한도를 초과하므로 입력이나 출력 예산을 줄여야 합니다.':'남은 범위 안에서 자료를 선택해야 합니다.'],bars:[{label:'지시',value:p.instruction},{label:'예시',value:p.examples},{label:'질문',value:p.question},{label:'출력 예약',value:p.output}],warning:remaining<0?'한도 초과. 음수 예산으로 자료를 포함할 수 없습니다.':undefined};},'예시를 늘리는 것이 항상 유리한 것은 아닙니다. 근거 자료와 출력 공간을 함께 확보해야 합니다.'),
  cot:model('다수결과 검산을 분리하기','문제 3×4의 후보 답 [12,12,a]. 풀이를 생성하는 모델은 없으며 정답 12로 최종 후보를 검산합니다.',[c('answer','세 번째 답 a',15,0,24,1),choice('first','첫 두 후보',0,['12,12','15,15'])],p=>{const a=p.first?15:12,answers=[a,a,p.answer],majority=a,correct=answers.filter(v=>v===12).length;return{metrics:[m('다수결 답',majority),m('정답 후보 수',correct),m('다수결 검산 통과',Number(majority===3*4))],steps:[`후보 답=[${answers}]`,`같은 답이 2개인 ${majority}를 다수결로 선택`,`독립 검산: 3×4=12`,`다수 답과 검산 비교: ${majority===12?'일치':'불일치'}. 일관성과 정답은 별개입니다.`],bars:answers.map((value,i)=>({label:`후보 ${i+1} 답`,value}))};},'첫 두 답을 모두 틀리게 바꿔보세요. 그럴듯한 중간 풀이와 다수결만으로 검증을 대신할 수 없습니다.'),
  'llm-training':model('손실 마스크가 포함하는 위치','네 위치의 정답 확률 [0.4,0.6,p,p]. 앞 두 위치는 지시, 뒤 두 위치는 응답으로 가정합니다. 선택 위치의 평균 손실을 계산합니다.',[c('p','응답 정답 확률',.8,.01,.99,.01),choice('mask','학습 대상',1,['전체 위치: 사전학습 예','응답만: SFT 예'])],p=>{const probs=[.4,.6,p.p,p.p],mask=p.mask?[0,0,1,1]:[1,1,1,1],losses=probs.map((v,i)=>-Math.log(v)*mask[i]),count=mask.reduce((a,b)=>a+b,0);return{metrics:[m('평균 토큰 손실',losses.reduce((a,b)=>a+b,0)/count),m('손실 대상 토큰',count)],steps:[`정답 확률=[${probs.map(n)}]`,`손실 mask=[${mask}]`,`가중 토큰 손실=[${losses.map(n)}]`,`합/유효 위치 수=${n(losses.reduce((a,b)=>a+b,0)/count)}. 본문의 합 손실과 reduction을 구분합니다.`],matrix:{name:'행: 확률 / mask / 손실 기여',values:[probs,mask,losses]}};},'마스크 0인 위치는 이 손실에 직접 포함되지 않지만, 응답 계산의 문맥으로 사용될 수 있습니다.'),
  'llm-finetuning':model('저랭크 보정의 파라미터 수','정사각 W [D,D] 하나, Bias 없음. LoRA B[D,r]와 A[r,D]. 기반 가중치 저장만의 이론적 양자화 크기이며 메타데이터·활성값·gradient·상태는 제외합니다.',[c('d','기반 차원 D',4096,256,8192,256),c('r','LoRA rank r',8,1,64,1),choice('bits','기반 저장 정밀도',0,['4 bit','16 bit','32 bit'])],p=>{const full=p.d**2,adapter=2*p.d*p.r,bits=[4,16,32][p.bits];return{metrics:[m('전체 행렬 파라미터',full),m('어댑터 파라미터',adapter),m('어댑터 / 전체',adapter/full),m('기반 저장',full*bits/8/2**20,'MiB')],steps:[`기반 W=${p.d}×${p.d}=${full}개`,`B와 A 합=${p.d}×${p.r}+${p.r}×${p.d}=${adapter}개`,`BA 결과 shape=[${p.d},${p.d}]로 W와 더할 수 있습니다.`,`기반 저장=${full}×${bits}/8 bytes. 학습 가능한 어댑터 비용은 별도입니다.`]};},'rank를 늘릴 때 학습 파라미터가 어떻게 늘어나는지 봅시다. QLoRA가 모델 전체를 4-bit로 학습한다는 뜻은 아닙니다.'),
  'preference-learning':model('선호 쌍의 log-ratio 차이','u=선호 응답 log(π/πref), v=비선호 응답 log(π/πref). 유효 확률 비율에서 나온 값이라 가정합니다. 보상 모델이나 RL 루프 실행은 아닙니다.',[c('u','선호 log-ratio',1,-3,3),c('v','비선호 log-ratio',0,-3,3),c('beta','β',1,.1,3)],p=>{const z=p.beta*(p.u-p.v),prob=sigmoid(z),loss=Math.max(-z,0)+Math.log1p(Math.exp(-Math.abs(z)));return{metrics:[m('선호 비교 Sigmoid',prob),m('DPO 손실',loss),m('선호 u 미분',-p.beta*(1-prob))],steps:[`차이=u−v=${n(p.u-p.v)}`,`z=β×차이=${n(z)}`,`손실=−logσ(z)=${n(loss)}`,`미분 ∂L/∂u=−β(1−σ)=${n(-p.beta*(1-prob))}`]};},'두 응답의 log-ratio를 같은 만큼 올려도 차이와 손실은 같습니다.'),
  distillation:model('Teacher의 부드러운 분포를 비교하기','Teacher logits [2,1,0], Student [s,1,0], 정답 클래스 1. Soft loss는 τ²KL, hard loss는 온도 1의 CE입니다.',[c('s','Student 첫 logit',1,-2,4),c('temp','증류 온도 τ',2,.5,4,.1),c('alpha','Hard loss 가중치 α',.5,0,1,.01)],p=>{const t=softmax([2,1,0],p.temp),s=softmax([p.s,1,0],p.temp),kl=t.reduce((v,x,i)=>v+x*Math.log(x/s[i]),0),hard=-Math.log(softmax([p.s,1,0])[0]),soft=p.temp**2*kl;return{metrics:[m('KL',Math.max(0,kl)),m('Hard CE',hard),m('가중 전체 손실',p.alpha*hard+(1-p.alpha)*soft)],steps:[`Teacher=[${t.map(n)}], Student=[${s.map(n)}]`,`KL=ΣpTeacher log(pTeacher/pStudent)=${n(kl)}`,`Soft loss=τ²×KL=${n(soft)}`,`합=α×${n(hard)}+(1−α)×${n(soft)}`],matrix:{name:'행: Teacher / Student',values:[t,s]}};},'Teacher와 같은 logits이면 Soft loss는 0입니다. Hard loss까지 0이 되는지는 따로 확인하세요.'),
  retrieval:model('두 검색 신호의 순위 합치기','질문 q=[1,q₂], 문서 A=[1,0],B=[0,1],C=[1,1]. 키워드 순위 B,A,C를 고정하고 RRF 점수 1/(k+rank)를 합산합니다. 실제 임베딩은 아닙니다.',[c('q','질문 두 번째 성분',0,-2,2),c('k','RRF 상수 k',10,1,60,1)],p=>{const vectors=[[1,0],[0,1],[1,1]],scores=vectors.map(v=>cosine([1,p.q],v)),ranks=scores.map((score,i)=>({score,i})).sort((a,b)=>b.score-a.score),keyword=[2,1,3],rrf=scores.map((_,i)=>1/(p.k+ranks.findIndex(v=>v.i===i)+1)+1/(p.k+keyword[i]));return{metrics:[m('A cosine',scores[0]),m('B cosine',scores[1]),m('C cosine',scores[2])],steps:[`벡터 점수=[${scores.map(n)}]`,`벡터 순위=${ranks.map(v=>['A','B','C'][v.i]).join(' → ')}`,'키워드 순위 B → A → C',`RRF 두 순위 합=[${rrf.map(n)}]`],bars:rrf.map((value,i)=>({label:`${['A','B','C'][i]} RRF`,value}))};},'키워드 점수와 cosine의 숫자 크기를 직접 더하는 방식 대신 순위를 결합할 수 있습니다.'),
  rag:model('관련도와 근거 토큰 예산','고정된 네 문서의 수작업 4차원 특징 벡터를 검색합니다. 실제 LLM 생성은 없으며 예산을 넘는 후보는 건너뜁니다.',[c('q','캐시 관련 질문 성분',3,0,5),c('k','검색 후보 수',2,1,4,1),c('budget','근거 예산',300,0,600,10)],p=>{const r=retrieve([1,0,p.q,0],p.k,p.budget),selected=r.candidates.filter(v=>v.included);return{metrics:[m('포함 근거 수',selected.length),m('사용 토큰',r.spent),m('남은 예산',p.budget-r.spent)],steps:[`질문=[1,0,${n(p.q)},0]`,`관련도 순위=${r.ranked.map(v=>`${v.id}:${n(v.score)}`).join(' → ')}`,`상위 ${p.k}개에서 예산이 허용하는 근거=${selected.map(v=>v.id).join(', ')||'없음'}`,`합계 ${r.spent}토큰. 이 숫자는 답변의 정확도를 의미하지 않습니다.`],bars:r.ranked.map(v=>({label:`${v.id} cosine`,value:v.score}))};},'top-k를 늘려도 예산 때문에 포함 근거 수가 그대로일 수 있습니다. 본문 아래 문서 내용을 확인할 수 있습니다.'),
  ontology:model('관계 방향과 OWL 타입 추론','worksFor의 domain=Person, range=Organization, Company⊑Organization. 민수와 A회사의 관계 방향을 선택하며 입력 검증을 자동 수행하는 규칙은 아닙니다.',[choice('reverse','관계 방향',0,['민수 worksFor A회사','A회사 worksFor 민수']),choice('declared','A회사 명시 타입',0,['Company','알려진 타입 없음'])],p=>{const reversed=Boolean(p.reverse),explicit=!p.declared;return{metrics:[m('관계에서 추론한 타입 사실 수',2),m('명시 Company의 상위 타입 추론',Number(explicit))],steps:[`관계: ${reversed?'A회사 → 민수':'민수 → A회사'} (worksFor)`,`domain에 의해 ${reversed?'A회사':'민수'}는 Person으로 추론`,`range에 의해 ${reversed?'민수':'A회사'}는 Organization으로 추론`,explicit?'Company(A회사) → Organization(A회사)도 추론':'명시 Company 사실은 없습니다. 모르는 사실을 거짓이라고 결론 내리지 않습니다.'],warning:reversed?'관계를 뒤집어도 OWL domain·range는 타입을 추론합니다. 업무상 잘못된 방향을 거절하려면 SHACL 같은 검증 규칙을 별도로 정의해야 합니다.':undefined};},'의미를 추론하는 규칙과 데이터를 거절하는 제약을 구분하세요. Person과 Organization을 disjoint로 선언했는지도 결과에 영향을 줍니다.'),
  graphrag:model('관계 경로로 연결된 근거 찾기','고정 지식 그래프 A회사—B회사—C회사, A회사—제품X, C회사—연구Y. 무방향 BFS 예제이며 실제 GraphRAG의 개체 추출·커뮤니티 요약은 본문에서 설명합니다.',[c('depth','탐색 hop 한도',1,0,4,1),choice('start','출발 개체',0,['A회사','C회사'])],p=>{const names=['A회사','B회사','C회사','제품X','연구Y'],edges=[[0,1],[1,2],[0,3],[2,4]],start=p.start?2:0,dist=names.map(()=>Infinity);dist[start]=0;const queue=[start];while(queue.length){const at=queue.shift()!;for(const [a,b] of edges){const next=a===at?b:b===at?a:-1;if(next>=0&&dist[next]===Infinity){dist[next]=dist[at]+1;queue.push(next);}}}const selected=names.filter((_,i)=>dist[i]<=p.depth);return{metrics:[m('연결된 개체 수',selected.length),m('출발 외 근거 개체',selected.length-1)],steps:[`출발=${names[start]}`,`최단 hop=[${dist}]`,`hop≤${p.depth}인 개체=${selected.join(', ')}`,`관계의 원문 출처를 함께 확인해야 합니다. hop 수는 문서 신뢰도나 답의 정확도가 아닙니다.`],matrix:{name:'그래프 인접 행렬: A,B,C,X,Y',values:names.map((_,i)=>names.map((_,j)=>Number(edges.some(([a,b])=>a===i&&b===j||a===j&&b===i))))}};},'질문이 직접 협력사를 묻는지 간접 연결까지 묻는지에 따라 필요한 hop이 달라집니다.'),
  'llm-wiki':model('새 자료가 기존 주장과 충돌할 때','Wiki에는 source-v1의 직원 수 100을 저장했다고 가정합니다. 새 자료의 값·버전을 비교하고 이 화면에서 갱신 정책만 시뮬레이션합니다.',[c('value','새 자료 직원 수',120,50,200,1),choice('version','출처 버전',1,['같은 버전 v1','새 버전 v2'])],p=>{const conflict=p.value!==100,revision=p.version===1;return{metrics:[m('값 충돌',Number(conflict)),m('새 버전',Number(revision)),m('갱신 후 유효 값',revision?p.value:100)],steps:['기존: 직원 수=100, 출처 source-v1',`새 자료: ${p.value}, 출처 source-v${p.version+1}`,conflict?'두 주장의 값이 다릅니다. 출처와 시점을 보존해 검토합니다.':'주장 값은 같습니다. 출처 확인 기록을 추가할 수 있습니다.',revision?`예제 정책: v2를 최신으로 채택하고 v1의 100은 이력에 보존`:'예제 정책: 같은 버전의 모순은 자동 덮어쓰기하지 않고 검토 상태로 둡니다.'],warning:conflict&&!revision?'같은 출처 버전의 값 충돌. 출처 확인이 필요합니다.':undefined};},'문서 요약을 반복해서 덮어쓰는 것과 출처·개체·갱신 이력을 유지하는 지식베이스는 다릅니다.'),
  'knowledge-strategies':model('갱신 비용이 서로 다른 지식 경로','순수 비용 예제: 질문마다 Prompt 600토큰, RAG 근거 1200토큰, Wiki 근거 500토큰. Wiki 구축·갱신은 변경마다 5000토큰. 같은 품질을 가정하거나 평가하지 않습니다.',[c('queries','질문 횟수',10,1,100,1),c('updates','자료 변경 횟수',1,0,20,1)],p=>({metrics:[m('직접 Prompt 입력',p.queries*600,'토큰'),m('RAG 근거 입력',p.queries*1200,'토큰'),m('Wiki 구축·근거 입력',p.updates*5000+p.queries*500,'토큰')],steps:[`Prompt 비용=${p.queries}×600`,`RAG 비용=${p.queries}×1200 (색인 비용 제외)`,`Wiki 비용=${p.updates}×5000+${p.queries}×500`,`Fine-tuning은 학습 비용과 파라미터 갱신이 추가됩니다. 이 토큰 비교만으로 선택을 결정할 수 없습니다.`]}),'질의 수와 갱신 빈도를 따로 바꾸세요. 최신성·출처 추적·표현 형식은 비용과 함께 검토할 기준입니다.'),
  'tools-agents':model('검사한 인수를 도구에 전달하기','로컬 add(a,b) 계산기만 실행합니다. 두 숫자를 가진 호출과 문자열 인수를 가진 잘못된 호출을 비교합니다. LLM이나 외부 도구는 호출하지 않습니다.',[c('a','인수 a',2,-10,10,1),c('b','인수 b',3,-10,10,1),choice('type','b 전달 형식',0,['number','문자열: 잘못된 타입'])],p=>({metrics:[m('스키마 검사 통과',Number(!p.type)),m('도구 결과',p.type?null:p.a+p.b)],steps:[`제안: add(${p.a},${p.type?`"${p.b}"`:p.b})`,`스키마: a,b 모두 number여야 함`,p.type?'검사 실패 → 실행하지 않고 오류를 반환':`검사 통과 → 실제 덧셈 결과 ${p.a+p.b}`,p.type?'호출 인수를 수정한 뒤 재시도해야 합니다.':'구조화한 결과를 다음 모델 입력에 넣고 종료 여부를 결정합니다.'],warning:p.type?'잘못된 인수 타입으로 실행을 차단했습니다.':undefined}),'도구 제안, 인수 검증, 실행, 결과 관찰은 각각의 단계입니다.'),
  mcp:model('JSON-RPC 요청과 결과의 연결','초기화와 tools/list를 마친 연결에서 tools/call의 id와 계산기 결과를 표시합니다. MCP 네트워크 구현이나 실제 서버 연결은 아닙니다.',[c('id','요청 id',1,1,20,1),c('a','계산기 a',2,-10,10,1),c('b','계산기 b',3,-10,10,1)],p=>({metrics:[m('도구 결과',p.a+p.b),m('응답 id',p.id)],steps:['Host가 Client를 관리하고 Client는 Server와 기능을 협상합니다.','tools/list에서 add 도구와 인수 스키마를 조회했다고 가정합니다.',`요청 {jsonrpc:"2.0",id:${p.id},method:"tools/call",params:{name:"add",arguments:{a:${p.a},b:${p.b}}}}`,`응답 id=${p.id}, result.content의 텍스트="${p.a+p.b}". id로 요청과 응답을 연결합니다.`]}),'도구가 사용하는 계산과 MCP가 정하는 연결·메시지 규칙의 역할을 구분하세요.'),
  harness:model('실패 횟수와 실행 한도를 관리하기','하나의 도구 작업은 처음 f회 실패한 뒤 성공한다고 가정합니다. 한도는 최초 실행을 포함한 최대 시도 수입니다. 실제 네트워크나 모델 재시도는 없습니다.',[c('failures','성공 전 실패 횟수 f',2,0,6,1),c('limit','최대 시도 수',3,1,6,1),c('cost','시도당 비용',100,10,500,10)],p=>{const success=p.failures<p.limit,attempts=Math.min(p.failures+1,p.limit);return{metrics:[m('실행 시도 수',attempts),m('작업 성공',Number(success)),m('사용 비용',attempts*p.cost)],steps:[`초기 상태: 도구 작업 대기, 최대 ${p.limit}번 실행`].concat(Array.from({length:attempts},(_,i)=>`시도 ${i+1}: ${i<p.failures?'실패 → 로그·상태 기록':'성공 → 결과 기록'}`)).concat(success?'종료 상태: 완료':'종료 상태: 한도 소진. 실패와 재개에 필요한 상태 보존')};},'한도를 늘리면 이번 예제의 성공 조건은 바뀌지만 비용도 증가합니다. 실제 실패가 재시도로 해결 가능한지도 확인해야 합니다.'),
  'llm-evaluation':model('평가 성공률과 비용을 분리하기','동일 조건의 독립 작업 N개 중 S개 성공. 입력은 S≤N으로 제한해 집계합니다. 95% Wilson 구간은 이 이진 성공률의 통계적 불확실성입니다.',[c('total','평가 작업 N',20,1,100,1),c('success','성공 작업 S',17,0,100,1),c('tokens','작업당 토큰',500,50,2000,50)],p=>{const s=Math.min(p.success,p.total),rate=s/p.total,z=1.96,den=1+z*z/p.total,center=(rate+z*z/(2*p.total))/den,half=z*Math.sqrt(rate*(1-rate)/p.total+z*z/(4*p.total**2))/den;return{metrics:[m('성공률',rate),m('95% Wilson 하한',center-half),m('95% Wilson 상한',center+half),m('전체 토큰',p.total*p.tokens)],steps:[`사용 성공 수=min(S,N)=${s}`,`성공률=${s}/${p.total}=${n(rate)}`,`Wilson 구간=[${n(center-half)},${n(center+half)}]`,`토큰=N×작업당 토큰=${p.total*p.tokens}. 정답성·근거 충실성·검색 품질은 별도로 측정해야 합니다.`],warning:p.success>p.total?'성공 수가 전체 수보다 커서 계산에는 N개까지만 사용했습니다.':undefined};},'같은 성공률이라도 평가 표본 수에 따라 불확실성 구간은 달라집니다.'),
};
