import { c, m, n, average, variance, type LessonModel } from './lessonModelTypes';
import { matmul } from './math';
export const mathModels: Record<string, LessonModel> = {
  vectors: { title: '내적과 실제 투영 벡터', assumption: '평면의 두 벡터 a=[a₁,2],b=[2,b₂]. 같은 단위의 직교 좌표입니다.', controls: [c('a','a₁',1,-4,4),c('b','b₂',1,-4,4)], observe: 'a·b의 부호와 b 방향으로 남는 투영을 비교하세요. 길이와 방향의 효과를 구분해 봅시다.', calculate: p=>{const a=[p.a,2],b=[2,p.b],dot=a[0]*b[0]+a[1]*b[1],scale=dot/(4+p.b**2);return {metrics:[m('내적',dot),m('코사인',dot/Math.hypot(...a)/Math.hypot(...b)),m('투영 계수',scale)],steps:[`내적 = ${n(p.a)}×2+2×${n(p.b)}=${n(dot)}`,`b 길이 제곱=4+${n(p.b**2)}`,`투영 계수=${n(dot)}/${n(4+p.b**2)}=${n(scale)}`,`투영 후 남은 성분의 b 내적은 0입니다.`],matrix:{name:'행 1:a / 행 2:b / 행 3:투영 a',values:[a,b,[2*scale,p.b*scale]]}};} },
  matrices: {title:'격자가 바뀌는 선형변환',assumption:'A=[[scale,shear],[0,1]],입력 [1,3] 및 단위 축을 실제로 곱합니다.',controls:[c('scale','가로축 배율',1,-3,3),c('shear','기울임 계수',2,-3,3)],observe:'기울임과 배율의 역할을 따로 바꾸세요. scale=0에서 정보가 사라지는 이유를 확인합니다.',calculate:p=>{const a=[[p.scale,p.shear],[0,1]],out=matmul(a,[[1],[3]]);return{metrics:[m('출력 x',out[0][0]),m('출력 y',out[1][0]),m('행렬식',p.scale)],steps:[`첫 행 내적=${n(p.scale)}×1+${n(p.shear)}×3=${n(out[0][0])}`,'둘째 행=0×1+1×3=3',`기저 (1,0)→(${n(p.scale)},0), (0,1)→(${n(p.shear)},1)`,p.scale===0?'행렬식 0:입력 가로 정보가 사라져 역행렬 없음':'행렬식이 0이 아니어서 이 예제는 가역'],matrix:{name:'변환 A',values:a},warning:p.scale===0?'특이행렬입니다. 모든 입력을 한 직선으로 보내 원본을 유일하게 복구할 수 없습니다.':undefined};}},
  'eigen-svd':{title:'축별 확대와 rank-1 근사',assumption:'대각 행렬 diag(a,b)의 고유값·특이값을 계산하고 가장 큰 특이값 축을 남깁니다.',controls:[c('a','첫 축 배율',3,-4,4),c('b','둘째 축 배율',1,-4,4)],observe:'음수 배율에서는 방향이 뒤집히지만 특이값은 음수가 아닙니다. 버리는 방향의 제곱 오차를 비교하세요.',calculate:p=>{const sv=[Math.abs(p.a),Math.abs(p.b)].sort((a,b)=>b-a);return{metrics:[m('가장 큰 특이값',sv[0]),m('둘째 특이값',sv[1]),m('rank-1 제곱오차',sv[1]**2)],steps:[`축 고유값은 ${n(p.a)},${n(p.b)}`,`특이값은 절댓값을 정렬한 [${sv.map(n)}]`,`큰 축만 보존하면 버린 특이값 ${n(sv[1])}의 제곱이 오차입니다.`],matrix:{name:'A의 대각 구조',values:[[p.a,0],[0,p.b]]}};}},
  derivatives:{title:'할선에서 접선으로',assumption:'f(x)=(2x+1)². h는 0보다 크고 정확 미분과 전진차분 근사를 비교합니다.',controls:[c('x','관찰 위치 x',1,-3,3),c('h','입력 변화 h',.1,.001,1,.001)],observe:'h를 줄이면 할선 기울기가 접선 기울기에 접근합니다. x를 옮기면 기울기 자체가 달라집니다.',calculate:p=>{const f=(x:number)=>(2*x+1)**2,der=4*(2*p.x+1),slope=(f(p.x+p.h)-f(p.x))/p.h;return{metrics:[m('정확 미분',der),m('할선 기울기',slope),m('근사 오차',slope-der)],steps:[`f(x)=${n(f(p.x))},f(x+h)=${n(f(p.x+p.h))}`,`평균 변화율=출력차/h=${n(slope)}`,`연쇄법칙:2(2x+1)×2=${n(der)}`,`전진차분 오차는 이 다항식에서 4h=${n(4*p.h)}`]};}},
  gradients:{title:'2차원 Gradient의 방향',assumption:'L(x,y)=x²+2y²,학습률 η로 한 step. 원점이 최소입니다.',controls:[c('x','x',2,-3,3),c('y','y',1,-3,3),c('rate','학습률 η',.1,0,1,.01)],observe:'y 방향은 더 가파릅니다. 같은 학습률을 쓰더라도 두 성분의 이동량이 다릅니다.',calculate:p=>{const g=[2*p.x,4*p.y],next=[p.x-p.rate*g[0],p.y-p.rate*g[1]],old=p.x**2+2*p.y**2,value=next[0]**2+2*next[1]**2;return{metrics:[m('이전 손실',old),m('다음 손실',value),m('Gradient norm',Math.hypot(...g))],steps:[`∂L/∂x=2x=${n(g[0])}`,`∂L/∂y=4y=${n(g[1])}`,`[x,y]새=[${next.map(n)}]`,`손실 변화=${n(value-old)}. 양수이면 이번 step이 과도했습니다.`],matrix:{name:'행 1:Gradient / 행 2:새 파라미터',values:[g,next]}};}},
  probability:{title:'동전 결과의 평균과 퍼짐',assumption:'0·1 결과의 Bernoulli 분포. p를 바꾸어 실제 확률 가중 평균을 계산합니다.',controls:[c('p','1의 확률 p',.3,0,1,.01)],observe:'p=0.5에서 분산이 가장 큽니다. 기대값은 실제 한 번의 결과와 같을 필요가 없습니다.',calculate:p=>({metrics:[m('평균',p.p),m('분산',p.p*(1-p.p)),m('표준편차',Math.sqrt(p.p*(1-p.p)))],steps:[`P(0)=${n(1-p.p)},P(1)=${n(p.p)}`,'평균=0×P(0)+1×P(1)',`분산=편차 제곱의 평균=${n(p.p*(1-p.p))}`],bars:[{label:'0',value:1-p.p},{label:'1',value:p.p}]})},
  statistics:{title:'표본평균·분산·표준오차',assumption:'세 독립 관측 [1,2,x]. 표본분산은 n−1,모집단식 분산은 n으로 나눕니다. 표준오차는 독립 표집 가정입니다.',controls:[c('x','세 번째 관측',3,-4,10)],observe:'이상치 하나가 평균·분산을 어떻게 바꾸는지 봅시다. 분모의 목적을 구분하세요.',calculate:p=>{const xs=[1,2,p.x],v=variance(xs),s=v*3/2;return{metrics:[m('표본평균',average(xs)),m('표본분산',s),m('모집단식 분산',v),m('평균 표준오차',Math.sqrt(s/3))],steps:[`합=${n(3+p.x)},평균=${n(average(xs))}`,`편차 제곱 합=${n(v*3)}`,`표본분산=합/2=${n(s)}`,`표준오차=√표본분산/√3=${n(Math.sqrt(s/3))}`],matrix:{name:'관측한 값',values:[xs]}};}},
  bayes:{title:'양성 집단 안의 진짜 양성',assumption:'1만 명의 기대 인원수. prior는 질병 비율,sensitivity는 진짜 양성률,false는 위양성률입니다.',controls:[c('prior','사전 비율',.01,.001,.5,.001),c('sens','민감도',.9,.1,1,.01),c('false','위양성률',.05,.001,.5,.001)],observe:'검사가 같아도 사전 비율에 따라 양성의 의미가 달라집니다.',calculate:p=>{const tp=10000*p.prior*p.sens,fp=10000*(1-p.prior)*p.false,post=tp/(tp+fp);return{metrics:[m('양성 후 확률',post),m('진짜 양성 기대 인원',tp),m('위양성 기대 인원',fp)],steps:[`환자=10000×prior=${n(10000*p.prior)}`,`진짜 양성=${n(tp)},위양성=${n(fp)}`,`양성 전체=${n(tp+fp)}`,`사후=${n(tp)}/${n(tp+fp)}=${n(post)}`],bars:[{label:'양성 중 환자',value:post},{label:'양성 중 비환자',value:1-post}]};}},
  'information-theory':{title:'이진 분포의 H·CE·KL',assumption:'p=[p,1−p],q=[q,1−q]. 자연로그 단위 nats. q는 0·1을 피합니다.',controls:[c('p','기준 p',.5,0,1,.01),c('q','예측 q',.8,.01,.99,.01)],observe:'q=p에서 KL=0입니다. p의 엔트로피와 q가 만드는 추가 비용을 구분하세요.',calculate:p=>{const ps=[p.p,1-p.p],qs=[p.q,1-p.q],h=-ps.reduce((s,v)=>s+(v?v*Math.log(v):0),0),ce=-ps.reduce((s,v,i)=>s+v*Math.log(qs[i]),0);return{metrics:[m('H(p)',h,'nats'),m('CE(p,q)',ce,'nats'),m('KL(p∥q)',Math.max(0,ce-h),'nats')],steps:[`기준=[${ps.map(n)}],예측=[${qs.map(n)}]`,`H=−Σp logp=${n(h)}`,`CE=−Σp logq=${n(ce)}`,`추가 비용=CE−H=${n(ce-h)}`],bars:ps.map((v,i)=>({label:`기준 결과 ${i}`,value:v}))};}},
};
