import { c, choice, m, n, average, variance, sigmoid, normal, type LessonModel } from './lessonModelTypes';
const model = (title:string, assumption:string, controls:LessonModel['controls'], calculate:LessonModel['calculate'], observe:string):LessonModel => ({title,assumption,controls,calculate,observe});
export function cluster1d(initial:number[], rounds:number) {
  const xs=[-3,-2,-1,2,3,4]; let centers=[...initial]; const history:number[]=[];
  const assign=()=>xs.map(x=>Math.abs(x-centers[0])<=Math.abs(x-centers[1])?0:1);
  for(let t=0;t<=rounds;t++){const labels=assign();history.push(xs.reduce((s,x,i)=>s+(x-centers[labels[i]])**2,0));if(t<rounds)centers=centers.map((old,k)=>{const group=xs.filter((_,i)=>labels[i]===k);return group.length?average(group):old;});}
  return {xs,centers,labels:assign(),history};
}
export const mlModels:Record<string,LessonModel>={
  'linear-regression':model('예측선과 잔차의 제곱','자료 x=[−1,0,1], y=[−1,1,3]. 선택한 차수의 마지막 항 계수만 바꿉니다. 자동 학습한 곡선이 아닙니다.',[c('w','계수 w',2,-4,4),c('b','절편 b',1,-3,3),choice('degree','입력 특성',0,['x: 선형','x²: 이차'])],p=>{const xs=[-1,0,1],ys=[-1,1,3],features=xs.map(x=>p.degree?x*x:x),pred=features.map(x=>p.w*x+p.b),err=pred.map((v,i)=>v-ys[i]);return{metrics:[m('MSE',average(err.map(v=>v*v))),m('∂L/∂w',2*average(err.map((v,i)=>v*features[i]))),m('∂L/∂b',2*average(err))],steps:[`특성=[${features.map(n)}], 예측=[${pred.map(n)}]`,`잔차=예측−정답=[${err.map(n)}]`,`잔차 제곱을 더해 3으로 나눕니다.`,`계수 미분은 잔차×특성의 평균에 2를 곱합니다.`],matrix:{name:'행: 입력 / 정답 / 예측 / 잔차',values:[xs,ys,pred,err]}};},'직선을 정확히 맞춘 뒤 이차 특성으로 바꿔보세요. 비선형 입력 변환과 파라미터에 대한 선형성을 구분합니다.'),
  'ridge-lasso':model('규제가 바꾸는 최적 계수','1차원 손실 ½(w−t)²에 Ridge는 ½λw², Lasso는 λ|w|를 더합니다. 본문의 MSE 표기와 상수 배율을 구분하세요.',[c('t','규제 없는 최적값 t',2,-4,4),c('lambda','규제 λ',1,0,4)],p=>{const ridge=p.t/(1+p.lambda),lasso=Math.sign(p.t)*Math.max(0,Math.abs(p.t)-p.lambda);return{metrics:[m('Ridge 최적 w',ridge),m('Lasso 최적 w',lasso)],steps:[`Ridge 미분=(w−${n(p.t)})+${n(p.lambda)}w=0`,`w=t/(1+λ)=${n(ridge)}`,`Lasso는 t의 크기에서 λ를 빼되 0 아래로 내려가지 않습니다.`,`w=sign(t)max(|t|−λ,0)=${n(lasso)}`],bars:[{label:'규제 없음',value:p.t},{label:'Ridge',value:ridge},{label:'Lasso',value:lasso}]};},'λ가 |t|에 도달할 때 Lasso 계수가 정확히 0이 됩니다. Ridge는 어떻게 다른가요?'),
  'logistic-regression':model('확률과 판단 임계값','z=wx+1, x=1. 이진 정답 y를 선택합니다. 임계값은 손실 계산과 별개의 판단 기준입니다.',[c('w','가중치 w',1,-6,6),choice('y','실제 정답',1,['0','1']),c('threshold','판단 임계값',.5,.05,.95,.01)],p=>{const z=p.w+1,prob=sigmoid(z),loss=Math.max(z,0)-z*p.y+Math.log1p(Math.exp(-Math.abs(z)));return{metrics:[m('양성 확률',prob),m('BCE',loss),m('예측 클래스',Number(prob>=p.threshold)),m('∂L/∂w',prob-p.y)],steps:[`z=w×1+1=${n(z)}`,`p=1/(1+exp(−z))=${n(prob)}`,`정답 ${p.y}의 손실=${n(loss)}`,`p≥임계값 ${n(p.threshold)}이면 양성. 임계값을 바꿔도 BCE는 같습니다.`]};},'정답을 뒤집고 기울기 부호를 보세요. 확률 추정과 클래스 결정은 서로 다른 단계입니다.'),
  'naive-bayes':model('조건부 가능도에서 사후확률로','관측 특성 두 개. 클래스 A의 가능도는 [a,0.2], B는 [0.3,0.6]. 특성의 조건부 독립을 가정합니다.',[c('prior','A 사전확률',.4,.01,.99,.01),c('a','A에서 첫 특성의 가능도',.5,.01,.99,.01)],p=>{const a=p.prior*p.a*.2,b=(1-p.prior)*.3*.6;return{metrics:[m('A 비정규화 점수',a),m('B 비정규화 점수',b),m('A 사후확률',a/(a+b))],steps:[`A 점수=prior×${n(p.a)}×0.2=${n(a)}`,`B 점수=(1−prior)×0.3×0.6=${n(b)}`,`두 점수 합=${n(a+b)}`,`A 사후=점수/합=${n(a/(a+b))}`],bars:[{label:'A 사후',value:a/(a+b)},{label:'B 사후',value:b/(a+b)}]};},'사전확률과 가능도가 각각 결론을 어떻게 바꾸는지 따로 확인하세요.'),
  knn:model('가까운 이웃의 투표','1차원 위치 [−3,−1,0,2,4], 클래스 [0,0,1,1,1]. 거리가 같으면 원래 표본 순서를 사용합니다.',[c('x','질문 위치',1,-4,5),choice('k','이웃 수',1,['1개','3개','5개'])],p=>{const xs=[-3,-1,0,2,4],ys=[0,0,1,1,1],k=[1,3,5][p.k],rank=xs.map((x,i)=>({x,y:ys[i],d:Math.abs(x-p.x)})).sort((a,b)=>a.d-b.d),vote=rank.slice(0,k).reduce((s,v)=>s+v.y,0);return{metrics:[m('클래스 1 투표 비율',vote/k),m('예측 클래스',Number(vote>k/2))],steps:[`모든 점과의 거리를 계산합니다.`,`가까운 순서: ${rank.map(v=>`${v.x}(거리 ${n(v.d)})`).join(' → ')}`,`첫 ${k}개 중 클래스 1은 ${vote}개`,`이 비율은 단순 이웃 투표이며 보정된 확률을 보장하지 않습니다.`],matrix:{name:'행: 가까운 위치 / 거리 / 클래스',values:[rank.map(v=>v.x),rank.map(v=>v.d),rank.map(v=>v.y)]}};},'k가 커지면 근처의 세밀한 변화와 전체 집단의 경향 중 무엇이 강조되나요?'),
  svm:model('마진 폭과 Hinge 위반','1차원 분리 w·x, bias=0, 표본 하나 x=1,y=+1. w>0. 전체 데이터 학습을 대신하지 않는 목적함수 조각입니다.',[c('w','가중치 w',2,.1,4),c('cost','위반 벌점 C',1,0,4)],p=>{const hinge=Math.max(0,1-p.w);return{metrics:[m('양쪽 마진 폭',2/p.w),m('Hinge loss',hinge),m('목적함수',.5*p.w**2+p.cost*hinge)],steps:[`서명 점수 ywx=${n(p.w)}`,`마진 위반=max(0,1−점수)=${n(hinge)}`,`마진 폭=2/|w|=${n(2/p.w)}`,`목적함수=½w²+C×위반=${n(.5*p.w**2+p.cost*hinge)}`]};},'w를 작게 하면 마진은 넓어지지만 위반이 생깁니다. C가 이 균형에 주는 효과를 보세요.'),
  'decision-tree':model('분할이 줄이는 불순도','x=[1,2,3,4,5,6], y=[0,0,1,0,1,1]. x≤t는 왼쪽. 한 분할을 계산하며 자동으로 최적 트리를 만들지는 않습니다.',[c('t','분할 임계값',2.5,.5,6.5,.5)],p=>{const y=[0,0,1,0,1,1],left=y.filter((_,i)=>i+1<=p.t),right=y.filter((_,i)=>i+1>p.t),g=(a:number[])=>a.length?2*average(a)*(1-average(a)):0,weighted=(left.length*g(left)+right.length*g(right))/6;return{metrics:[m('부모 Gini',.5),m('가중 자식 Gini',weighted),m('감소량 gain',.5-weighted)],steps:[`왼쪽 클래스=[${left}], 오른쪽=[${right}]`,`각 Gini는 2p(1−p). 왼쪽 ${n(g(left))}, 오른쪽 ${n(g(right))}`,`자식 가중 평균=(${left.length}×${n(g(left))}+${right.length}×${n(g(right))})/6`,`gain=0.5−${n(weighted)}=${n(.5-weighted)}`]};},'표본 수가 다른 자식의 Gini를 단순 평균하면 왜 안 되는지 확인하세요.'),
  ensembles:model('평균과 잔차 보정은 다른 계산','Bagging 예측은 [2,3,4]. Boosting은 시작 예측 3, 정답 5를 고정하고 제곱오차의 잔차를 완벽히 맞추는 이상적인 weak learner를 가정합니다.',[c('rate','Boosting 학습률',.3,0,1,.01),c('rounds','보정 횟수',3,0,10,1),c('rho','Bagging 오차 상관계수',.2,0,1,.01)],p=>{let value=3;const history=[value];for(let i=0;i<p.rounds;i++){value+=p.rate*(5-value);history.push(value);}return{metrics:[m('Bagging 평균',3),m('Boosting 최종 예측',value),m('평균 오차 분산',p.rho+(1-p.rho)/3)],steps:[`Bagging=(2+3+4)/3=3`,`Boosting: 이전 값+η(5−이전 값)`,`예측 경로=[${history.map(n)}]`,`각 모델 오차 분산 1, 공통 상관 ρ이면 평균 분산=ρ+(1−ρ)/3`],bars:history.map((value,i)=>({label:`보정 ${i}`,value}))};},'상관이 1인 모델을 평균해도 분산은 줄지 않습니다. Boosting 보정은 이 평균과 다른 원리입니다.'),
  kmeans:model('할당 후 평균으로 중심 이동','표본 [−3,−2,−1,2,3,4], k=2. 거리가 같으면 첫 중심, 빈 군집은 이전 중심을 유지합니다.',[c('a','첫 초기 중심',-3,-5,5),c('b','둘째 초기 중심',1,-5,5),c('rounds','갱신 횟수',1,0,5,1)],p=>{const r=cluster1d([p.a,p.b],p.rounds);return{metrics:[m('첫 중심',r.centers[0]),m('둘째 중심',r.centers[1]),m('목적 J',r.history.at(-1)!)],steps:[`초기 중심=[${n(p.a)},${n(p.b)}]`,`최종 할당=[${r.labels}]`,`할당된 표본 평균으로 중심=[${r.centers.map(n)}]`,`각 단계 J=[${r.history.map(n)}]. 이 절차의 J는 증가하지 않습니다.`],matrix:{name:'행: 표본 / 군집 번호',values:[r.xs,r.labels]},bars:r.history.map((value,i)=>({label:`단계 ${i}`,value}))};},'초기 중심을 같은 쪽에 두고 결과를 비교하세요. 중심 번호의 순서 자체에는 의미가 없습니다.'),
  'gmm-em':model('하드 할당 대신 책임도','두 1차원 Gaussian 평균 −2,+2, 공통 표준편차 σ. 한 점의 E-step을 계산합니다. 밀도는 확률값과 달리 1보다 클 수 있습니다.',[c('x','관찰 위치',0,-5,5),c('std','표준편차 σ',1,.2,3),c('mix','첫 성분 가중치',.5,.01,.99,.01)],p=>{const a=p.mix*normal(p.x,-2,p.std),b=(1-p.mix)*normal(p.x,2,p.std);return{metrics:[m('혼합 밀도',a+b),m('첫 성분 책임도',a/(a+b)),m('둘째 성분 책임도',b/(a+b))],steps:[`첫 가중 밀도=π₁N(x;−2,σ²)=${n(a)}`,`둘째 가중 밀도=(1−π₁)N(x;2,σ²)=${n(b)}`,`책임도=각 가중 밀도/밀도 합`,`M-step에서는 모든 점의 책임도를 가중치로 사용해 평균·분산·혼합비를 다시 계산합니다.`],bars:[{label:'첫 책임도',value:a/(a+b)},{label:'둘째 책임도',value:b/(a+b)}]};},'평균 사이에서 두 책임도가 함께 커지는 조건과 혼합 가중치의 효과를 보세요.'),
  'hierarchical-dbscan':model('이웃의 밀도가 만드는 Core','1차원 표본 [0,0.2,0.4,1.2,3]. 자신의 ε 이웃을 포함합니다. core와 core에 직접 인접한 border, 그 밖의 noise를 계산합니다.',[c('epsilon','반경 ε',.3,.1,2,.1),c('minimum','최소 이웃 수',3,1,5,1)],p=>{const xs=[0,.2,.4,1.2,3],counts=xs.map(x=>xs.filter(y=>Math.abs(x-y)<=p.epsilon+1e-9).length),core=counts.map(v=>v>=p.minimum),types=xs.map((x,i)=>core[i]?2:xs.some((y,j)=>core[j]&&Math.abs(x-y)<=p.epsilon+1e-9)?1:0);return{metrics:[m('Core 개수',types.filter(v=>v===2).length),m('Border 개수',types.filter(v=>v===1).length),m('Noise 개수',types.filter(v=>v===0).length)],steps:[`자신 포함 이웃 수=[${counts}]`,`이웃 수 ≥ ${p.minimum}이면 Core`,`Core가 아닌 점 중 Core의 반경 안이면 Border`,`나머지 점은 Noise. 군집은 Core 사이의 이웃 연결로 이어집니다.`],matrix:{name:'행: 위치 / 이웃 수 / 2 Core·1 Border·0 Noise',values:[xs,counts,types]}};},'반경을 늘리는 것과 최소 이웃 수를 늘리는 것의 효과는 반대 방향일 수 있습니다.'),
  'dimensionality-reduction':model('투영 방향과 보존 분산','중심화된 네 점 [−3,−1],[−3,1],[3,−1],[3,1]. 공분산은 diag(9,1). PCA와 선택한 축의 투영을 비교하며 t-SNE·UMAP 실행은 아닙니다.',[c('angle','투영 각도',0,0,180,1)],p=>{const a=p.angle*Math.PI/180,u=[Math.cos(a),Math.sin(a)],points=[[-3,-1],[-3,1],[3,-1],[3,1]],z=points.map(v=>v[0]*u[0]+v[1]*u[1]),v=variance(z);return{metrics:[m('보존 분산',v),m('설명 분산 비율',v/10),m('평균 복원 제곱거리',10-v)],steps:[`단위 축=[${u.map(n)}]`,`각 점의 투영 좌표=[${z.map(n)}]`,`투영 분산=9cos²θ+sin²θ=${n(v)}`,`PCA의 첫 축 θ=0°는 전체 분산 10 중 9를 보존합니다.`],matrix:{name:'투영 좌표 한 행',values:[z]}};},'90° 회전하면 보존되는 정보가 얼마나 바뀌나요? 분산의 보존이 분류에 필요한 정보의 보존과 같지는 않습니다.'),
  'density-anomaly':model('커널을 더한 밀도 곡선','표본 [−1,0,1], Gaussian KDE. 임계값은 예시로 설정하며 이상 정답 레이블이나 오탐률을 가정하지 않습니다.',[c('x','평가 위치',2,-4,4),c('h','Bandwidth',.7,.1,2,.1),c('threshold','밀도 임계값',.1,.01,.5,.01)],p=>{const parts=[-1,0,1].map(v=>normal(p.x,v,p.h)/3),density=parts.reduce((a,b)=>a+b,0);return{metrics:[m('KDE 밀도',density),m('이상 표시',Number(density<p.threshold))],steps:[`각 표본에 표준편차 h=${n(p.h)}인 Gaussian을 둡니다.`,`표본별 기여=[${parts.map(n)}]`,`밀도는 세 기여의 합=${n(density)}`,`밀도 < ${n(p.threshold)}이면 이 실험에서 이상 표시. 실제 성능은 정답으로 평가해야 합니다.`],bars:parts.map((value,i)=>({label:`표본 ${i+1} 기여`,value}))};},'작은 h의 뾰족한 밀도와 큰 h의 매끄러운 밀도를 비교하세요. 높이는 확률 질량이 아닙니다.'),
  recommendation:model('잠재벡터로 관측 평점 예측','사용자 p=[1,u], 아이템 q=[0.5,i]. 전역 평균·bias를 합친 값을 b로 설정. 정답 4인 관측 쌍 하나만의 손실입니다.',[c('u','사용자 두 번째 성분',2,-3,3),c('i','아이템 두 번째 성분',1,-3,3),c('b','평균과 bias 합',0,-2,2)],p=>{const dot=.5+p.u*p.i,pred=dot+p.b;return{metrics:[m('내적',dot),m('예측 평점',pred),m('관측 제곱오차',(pred-4)**2)],steps:[`내적=1×0.5+u×i=${n(dot)}`,`예측=내적+b=${n(pred)}`,`관측된 정답 4와 잔차=${n(pred-4)}`,`미관측 쌍을 실제 0점 정답으로 추가하지 않습니다.`]};},'두 잠재벡터와 bias가 각각 예측에 주는 효과를 보세요. 계산된 평점은 서비스의 표시 범위를 넘을 수도 있습니다.'),
  'semi-supervised':model('의사 레이블을 쓸 표본 선택','무레이블 세 표본의 최대 확률 [0.95,0.6,0.85]. 임계값 통과 표본의 −log(최대 확률)을 평균합니다. 지도 손실은 0.4로 고정합니다.',[c('threshold','신뢰도 임계값',.9,.5,.99,.01),c('lambda','무레이블 손실 가중치',1,0,3)],p=>{const conf=[.95,.6,.85],selected=conf.filter(v=>v>=p.threshold),loss=selected.length?average(selected.map(v=>-Math.log(v))):0;return{metrics:[m('채택 표본 수',selected.length),m('의사 레이블 평균 손실',loss),m('전체 손실',.4+p.lambda*loss)],steps:[`최대 확률 ≥ ${n(p.threshold)}인 표본을 고릅니다.`,`통과 확률=[${selected.map(n)}]`,`채택 표본이 없으면 이 실험의 무레이블 손실은 0`,`전체=0.4+λ×평균 손실=${n(.4+p.lambda*loss)}`],bars:conf.map((value,i)=>({label:`표본 ${i+1} 신뢰도`,value}))};},'임계값을 올리면 표본은 줄어듭니다. 남은 표본의 높은 확률이 정답성을 증명하지는 않습니다.'),
};
