import { c, choice, m, n, type LessonModel } from './lessonModelTypes';
import { matmul, softmax } from './math';
const model=(title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});
export const pytorchModels:Record<string,LessonModel>={
  'torch-tensors':model('Shape와 dtype의 저장량','shape=[B,3,D]. 순수 Tensor 원소 저장량만 계산하며 device 관리·할당자 메모리는 제외합니다.',[c('batch','Batch B',2,1,16,1),c('d','Feature D',4,1,32,1),choice('dtype','dtype',0,['float32: 4 bytes','float16: 2 bytes','int64: 8 bytes'])],p=>{const num=p.batch*3*p.d,bytes=[4,2,8][p.dtype];return{metrics:[m('Rank',3),m('원소 수 numel',num),m('원소 저장량',num*bytes,'bytes')],steps:[`shape=[${p.batch},3,${p.d}]`,`축은 3개이므로 rank=3`,`원소 수=${p.batch}×3×${p.d}=${num}`,`한 원소 ${bytes} bytes → ${num*bytes} bytes. 숫자 개수는 dtype 변경으로 달라지지 않습니다.`]};},'rank·각 축의 크기·총 원소 수를 각각 구분하고 dtype을 바꿔보세요.'),
  'torch-operations':model('원소별 곱과 행렬곱 비교','A=[[1,a],[3,4]], B=[[2,0],[1,2]]. 두 입력은 모두 [2,2]지만 곱의 의미가 다릅니다.',[c('a','A[0,1]',2,-4,4),choice('op','연산',0,['A @ B: 행렬곱','A * B: 원소별 곱'])],p=>{const a=[[1,p.a],[3,4]],b=[[2,0],[1,2]],out=p.op?a.map((row,i)=>row.map((v,j)=>v*b[i][j])):matmul(a,b);return{metrics:[m('결과 [0,0]',out[0][0]),m('결과 [0,1]',out[0][1])],steps:[`A=[[1,${n(p.a)}],[3,4]]`,`B=[[2,0],[1,2]]`,p.op?'동일 위치의 두 원소를 곱합니다.':'결과 위치마다 A의 행과 B의 열 내적을 계산합니다.',`출력 shape [2,2]. 첫 행=[${out[0].map(n)}]`],matrix:{name:p.op?'원소별 곱':'행렬곱',values:out}};},'출력 shape가 같아도 값과 의미는 다릅니다. a를 바꾸면 어떤 칸들이 달라지나요?'),
  'torch-module':model('등록한 두 Linear의 파라미터','모델 Linear(4,H)→ReLU→Linear(H,2), Bias 포함. Batch는 모델 파라미터 수에 영향을 주지 않습니다.',[c('h','숨은 차원 H',8,1,64,1),c('batch','Batch B',2,1,16,1)],p=>{const first=4*p.h+p.h,second=2*p.h+2;return{metrics:[m('첫 Linear',first),m('둘째 Linear',second),m('총 파라미터',first+second),m('출력 원소 수',p.batch*2)],steps:[`입력=[${p.batch},4]`,`첫 weight=[${p.h},4], bias=[${p.h}] → ${first}개`,`ReLU는 shape [${p.batch},${p.h}]를 보존`,`둘째 weight=[2,${p.h}], bias=[2] → ${second}개, 출력=[${p.batch},2]`]};},'Batch와 숨은 차원을 따로 변경해 파라미터와 활성값의 크기를 구분하세요.'),
  'torch-functional':model('F.linear에 전달하는 Weight 방향','입력 x=[1,2], weight=[[w,0],[1,−1]], bias=[1,0]. F.linear(x,W,b)는 xWᵀ+b입니다.',[c('w','첫 출력의 가중치',3,-4,4),c('x','입력 두 번째 값',2,-4,4)],p=>{const out=[p.w+1,1-p.x];return{metrics:[m('첫 출력',out[0]),m('둘째 출력',out[1])],steps:[`x=[1,${n(p.x)}], weight shape=[2,2]`,`첫 행과 x 내적+1=${n(p.w)}×1+0×x₂+1=${n(out[0])}`,`둘째 행과 x 내적=1×1−1×${n(p.x)}=${n(out[1])}`,`같은 weight·bias를 가진 nn.Linear의 순전파 결과와 같습니다.`],matrix:{name:'Weight: 행은 출력 feature',values:[[p.w,0],[1,-1]]}};},'weight의 행이 어떤 출력에 대응하는지 확인하세요. functional은 학습 가능한 weight를 자동으로 등록하지 않습니다.'),
  'torch-autograd':model('새 Forward의 backward가 누적하는 값','leaf x에서 매번 새 y=x²를 만든 뒤 backward합니다. zero_grad를 매번 수행할지 선택합니다. 동일 그래프를 재사용하는 상황은 아닙니다.',[c('x','Leaf x',2,-4,4),c('calls','새 forward/backward 수',2,1,6,1),choice('zero','Gradient 초기화',0,['처음만 초기화','매번 초기화']),choice('detach','출력 연결',0,['연결 유지','y.detach: 미분 연결 없음'])],p=>{const per=2*p.x,grad=p.detach?null:per*(p.zero?1:p.calls);return{metrics:[m('한 번의 dy/dx',per),m('최종 leaf.grad',grad)],steps:[`순전파마다 y=${n(p.x**2)}, 미분=2x=${n(per)}`,p.detach?'y.detach()에는 grad_fn이 없으므로 이 출력의 backward는 실행할 수 없습니다.':`새 그래프 ${p.calls}개에서 각각 backward`,p.zero?'매 backward 전에 grad를 초기화합니다.':'초기화하지 않은 grad에는 이전 값을 더합니다.',`최종 grad=${grad===null?'생성되지 않음':n(grad)}`],warning:p.detach?'detach한 결과만으로 backward를 호출하면 gradient 연결이 없어 실패합니다.':undefined};},'그래프 보존과 leaf의 Gradient 누적은 서로 다른 문제입니다.'),
  'torch-data':model('마지막 배치를 포함할까요?','표본 N개를 Batch B로 묶습니다. shuffle은 순서를 바꾸지만 배치 수는 바꾸지 않습니다.',[c('n','표본 N',10,1,40,1),c('batch','Batch B',4,1,16,1),choice('drop','마지막 불완전 배치',0,['포함: drop_last=False','제외: drop_last=True'])],p=>{const full=Math.floor(p.n/p.batch),rest=p.n%p.batch,batches=Array.from({length:full},()=>p.batch);if(rest&&!p.drop)batches.push(rest);return{metrics:[m('배치 수',batches.length),m('사용 표본 수',batches.reduce((a,b)=>a+b,0)),m('제외 표본 수',p.drop?rest:0)],steps:[`완전 배치=floor(N/B)=${full}`,`나머지=N mod B=${rest}`,`배치별 크기=[${batches}]`,`표본 순서와 배치 크기는 구분합니다. 마지막 배치를 제외하면 일부 표본이 해당 epoch에서 빠집니다.`],bars:batches.map((value,i)=>({label:`배치 ${i+1}`,value}))};},'N보다 큰 Batch를 설정하면 drop_last=True에서 배치가 아예 없는 경우도 생깁니다.'),
  'torch-losses':model('정답 형식에 맞는 손실','CE: logits [z,1,0], 정답 ID 0. BCE: 이진 logit z, 정답 1. MSE: 예측 z, 정답 1. 서로 다른 문제이므로 손실 크기로 우열을 비교하지 않습니다.',[c('z','예측 입력 z',2,-4,4),choice('kind','손실 종류',0,['CrossEntropyLoss','BCEWithLogitsLoss','MSELoss'])],p=>{const prob=softmax([p.z,1,0]),loss=p.kind===0?-Math.log(prob[0]):p.kind===1?Math.max(p.z,0)-p.z+Math.log1p(Math.exp(-Math.abs(p.z))):(p.z-1)**2;return{metrics:[m('선택한 손실',loss)],steps:[p.kind===0?'CE 입력은 클래스 logits [1,3], target은 long ID [1]':p.kind===1?'BCE 입력은 logit와 같은 shape의 실수 0·1 target':'MSE 입력과 연속 정답은 같은 shape',p.kind===0?`정답 클래스 확률=${n(prob[0])}`:p.kind===1?`Sigmoid 확률=${n(1/(1+Math.exp(-p.z)))}`:`잔차=${n(p.z-1)}`,`선택 손실=${n(loss)}`,p.kind===0?'CE 앞에 Softmax를 또 넣지 않습니다.':p.kind===1?'BCEWithLogitsLoss는 내부에서 안정적인 Sigmoid+BCE를 계산합니다.':'MSE는 확률이나 클래스 ID를 요구하지 않습니다.']};},'출력 숫자의 의미가 연속 예측인지 logit인지부터 결정해야 합니다.'),
  'torch-loop':model('초기화·미분·갱신을 반복하기','L(w)=w², SGD. 시작 w=1에서 실제 반복 업데이트합니다. Gradient 누적을 끄거나 의도치 않게 유지한 결과를 비교합니다.',[c('rate','SGD 학습률',.1,0,.6,.01),c('steps','학습 step 수',3,0,8,1),choice('zero','zero_grad',0,['매 step 수행','누락'])],p=>{let w=1,grad=0;const values=[w];for(let i=0;i<p.steps;i++){if(!p.zero)grad=0;grad+=2*w;w-=p.rate*grad;values.push(w);}return{metrics:[m('최종 w',w),m('최종 손실',w*w),m('마지막 Gradient',grad)],steps:[`초기 w=1, loss=w²`,`각 backward의 Gradient는 현재 2w`,`zero_grad ${p.zero?'누락: 이전 Gradient에 계속 더함':'수행: 이번 Gradient만 사용'}`,`w 경로=[${values.map(n)}]`],bars:values.map((value,i)=>({label:`step ${i}`,value}))};},'Gradient 누적을 의도한 경우와 매 배치 초기화를 빠뜨린 경우를 구분하세요.'),
  'torch-modes':model('Module 모드와 미분 기록의 두 스위치','Dropout p=0.5, 입력 x. 모드별 이론적 평균·분산을 계산하며 난수 표본을 뽑지는 않습니다. 입력은 requires_grad=True라고 가정합니다.',[c('x','입력 x',2,-4,4),choice('mode','Module 모드',0,['train','eval']),choice('grad','Autograd 기록',0,['활성','no_grad'])],p=>({metrics:[m('출력 기대값',p.x),m('출력 분산',p.mode?0:p.x**2),m('미분 그래프 기록',Number(!p.grad))],steps:[p.mode?'eval: Dropout 출력은 x':'train: 출력은 확률 0.5로 0 또는 2x',`평균=${n(p.x)}, 분산=${n(p.mode?0:p.x**2)}`,p.grad?'no_grad: 연산을 그래프에 기록하지 않음':'미분 기록 활성: 모드가 eval이어도 그래프를 기록할 수 있음','BatchNorm의 running 통계 동작도 Module 모드에 따라 달라집니다.']}),'train+no_grad와 eval+grad_enabled 조합을 비교하세요.'),
  'torch-checkpoints':model('Momentum 상태까지 복원하기','같은 저장 가중치 w=1, 다음 Gradient g=2, β=0.9. 이전 momentum v를 복원할지 선택합니다. 실제 파일 저장·로드를 수행하지 않습니다.',[c('v','저장 Momentum v',3,-4,6),c('rate','다음 학습률',.1,0,.5,.01),choice('restore','복원 범위',0,['가중치와 optimizer 상태','가중치만'])],p=>{const old=p.restore?0:p.v,next=.9*old+2,w=1-p.rate*next;return{metrics:[m('복원된 Momentum',old),m('새 Momentum',next),m('다음 가중치',w)],steps:[`복원 가중치 w=1, optimizer v=${n(old)}`,`새 v=0.9×${n(old)}+2=${n(next)}`,`w새=1−lr×새 v=${n(w)}`,'같은 가중치여도 optimizer 상태·진행 step 등이 다르면 학습 재개 결과가 달라집니다.']};},'가중치만 저장한 모델로 예측하는 것과 학습을 이어가는 것에 필요한 상태를 비교하세요.'),
};
