import { c, choice, m, n, sigmoid, type LessonModel } from './lessonModelTypes';
import { qUpdate } from './experiments';
const model=(title:string,assumption:string,controls:LessonModel['controls'],calculate:LessonModel['calculate'],observe:string):LessonModel=>({title,assumption,controls,calculate,observe});
export const rlModels:Record<string,LessonModel>={
  'rl-basics':model('미래 보상을 현재 기준으로 합산','보상 [1,2,r₃]. 세 단계 뒤 종료하는 결정적 경로 하나의 Return입니다. 기대 Return은 여러 경로의 확률까지 고려합니다.',[c('gamma','할인율 γ',.5,0,1,.01),c('reward','세 번째 보상',3,-5,10)],p=>{const parts=[1,2*p.gamma,p.reward*p.gamma**2];return{metrics:[m('Return',parts.reduce((a,b)=>a+b,0))],steps:[`첫 보상 기여=1`,`다음 기여=γ×2=${n(parts[1])}`,`세 번째 기여=γ²×r₃=${n(parts[2])}`,`합=${n(parts.reduce((a,b)=>a+b,0))}`],bars:parts.map((value,i)=>({label:`보상 ${i+1} 기여`,value}))};},'γ=0이면 미래 보상은 제외됩니다. γ=1과 비교해 보세요.'),
  bandits:model('탐색 확률과 표본평균 갱신','K개 행동에서 greedy 행동이 하나로 정해져 있습니다. ε 탐색은 greedy를 포함한 전체 행동에서 균등하게 선택합니다.',[c('epsilon','탐색률 ε',.1,0,1,.01),c('k','행동 수 K',2,2,8,1),c('reward','새 보상',1,0,2),c('count','기존 관측 수',4,1,20,1)],p=>{const old=.5,newMean=old+(p.reward-old)/(p.count+1),greedy=1-p.epsilon+p.epsilon/p.k;return{metrics:[m('Greedy 선택 확률',greedy),m('각 다른 행동 확률',p.epsilon/p.k),m('새 가치 추정',newMean)],steps:[`Greedy 선택=(1−ε)+ε/K=${n(greedy)}`,`각 다른 행동=ε/K=${n(p.epsilon/p.k)}`,`기존 평균 0.5, 관측 ${p.count}개에 보상 ${n(p.reward)} 추가`,`새 평균=0.5+(보상−0.5)/(${p.count}+1)=${n(newMean)}`],bars:Array.from({length:p.k},(_,i)=>({label:i===0?'Greedy':`행동 ${i+1}`,value:i===0?greedy:p.epsilon/p.k}))};},'탐색을 시작했다고 greedy 행동이 배제되는 것은 아닙니다. 표본 수가 커지면 새 보상의 영향이 작아집니다.'),
  bellman:model('전이 확률을 가중한 다음 가치','보상 1, 다음 상태 가치 [2,6]. 첫 상태로 갈 확률 p. 종료를 선택하면 미래 가치를 제외합니다.',[c('p','첫 상태 전이 확률',.5,0,1,.01),c('gamma','할인율',.9,0,1,.01),choice('terminal','전이 종류',0,['이어지는 전이','종료 전이'])],p=>{const next=p.p*2+(1-p.p)*6,target=1+(p.terminal?0:p.gamma*next);return{metrics:[m('다음 가치 기대값',next),m('Bellman 목표',target)],steps:[`E[V다음]=p×2+(1−p)×6=${n(next)}`,`현재 보상=1`,`종료 여부=${p.terminal?'종료: 미래 항은 0':'계속: 미래 항을 유지'}`,`목표=1+${p.terminal?'0':`${n(p.gamma)}×${n(next)}`}=${n(target)}`],bars:[{label:'첫 전이 확률',value:p.p},{label:'둘째 전이 확률',value:1-p.p}]};},'가치 자체와 해당 상태로 전이할 확률을 구분해 보세요.'),
  qlearning:model('TD 오차로 가치표 수정','현재 Q=2, 다음 행동 Q=[4,1]. Q-learning은 max=4, SARSA는 실제 선택한 둘째 행동 Q=1을 사용합니다.',[choice('method','업데이트 규칙',0,['Q-learning','SARSA']),c('reward','관측 보상',1,-3,5),c('rate','갱신 비율 α',.5,0,1,.01),c('gamma','할인율 γ',.9,0,1,.01),choice('terminal','종료 여부',0,['계속','종료'])],p=>{const next=p.method?1:4,r=qUpdate(2,p.reward,next,p.rate,p.gamma,Boolean(p.terminal));return{metrics:[m('TD 목표',r.target),m('TD 오차',r.error),m('새 Q',r.value)],steps:[`다음에 쓰는 Q=${next} (${p.method?'실제 다음 행동':'최대 행동'})`,`목표=r+γQ다음=${n(r.target)}${p.terminal?' (종료: 미래 항 제외)':''}`,`TD 오차=목표−현재 2=${n(r.error)}`,`새 Q=2+α×오차=${n(r.value)}`]};},'같은 경험에서도 다음 행동을 실제로 따르는지 최대값을 쓰는지에 따라 목표가 달라집니다.'),
  dqn:model('Target network가 정하는 학습 목표','현재 네트워크 예측 q, Target network의 다음 최대값 4. 목표는 역전파에서 상수로 취급합니다. 한 전이의 손실을 계산합니다.',[c('q','현재 예측',2,-2,7),c('reward','보상',1,-2,5),c('gamma','할인율',.9,0,1,.01),choice('terminal','전이 종류',0,['계속','종료'])],p=>{const target=p.reward+(p.terminal?0:p.gamma*4),error=p.q-target,a=Math.abs(error),huber=a<=1?.5*error**2:a-.5;return{metrics:[m('분리된 목표',target),m('제곱 손실',error**2),m('Huber δ=1',huber),m('제곱 손실 미분',2*error)],steps:[`Target 값=보상+${p.terminal?'0':'γ×4'}=${n(target)}`,`예측−목표=${n(error)}`,`제곱 손실=${n(error**2)}. 목표에 gradient를 흘리지 않습니다.`,`Huber는 |오차|≤1에서 ½오차², 밖에서는 |오차|−½입니다.`]};},'큰 TD 오차에서 제곱 손실과 Huber의 증가율을 비교하세요. Replay와 Target network는 서로 다른 안정화 장치입니다.'),
  'policy-gradient':model('좋았던 행동의 확률을 높이는 신호','이진 정책 π(행동1)=sigmoid(z). 행동1을 관측했고 Return G, 행동과 독립인 baseline b를 사용합니다. 손실은 −(G−b)logπ입니다.',[c('z','정책 logit',0,-4,4),c('return','관측 Return',5,-2,8),c('baseline','Baseline',3,-2,8)],p=>{const prob=sigmoid(p.z),adv=p.return-p.baseline;return{metrics:[m('행동1 확률',prob),m('Advantage',adv),m('손실 미분 ∂L/∂z',-adv*(1-prob))],steps:[`π=sigmoid(z)=${n(prob)}`,`A=G−b=${n(adv)}`,`d logπ/dz=1−π=${n(1-prob)}`,`손실 미분=−A(1−π)=${n(-adv*(1-prob))}. 경사하강은 이 부호 반대로 이동합니다.`]};},'보상이 양수여도 baseline보다 낮으면 행동 확률을 줄이는 신호가 될 수 있습니다.'),
  'actor-critic-ppo':model('Clipped surrogate의 두 항','한 표본의 Advantage A와 정책 확률 비율 r를 입력합니다. 비율이 실제 확률에서 나온다고 가정하며 전체 정책의 KL을 계산하는 실험은 아닙니다.',[c('ratio','확률 비율 r',1.5,.1,2.5,.01),c('adv','Advantage A',2,-4,4),c('epsilon','허용 폭 ε',.2,.01,.5,.01)],p=>{const clip=Math.max(1-p.epsilon,Math.min(1+p.epsilon,p.ratio)),raw=p.ratio*p.adv,clipped=clip*p.adv;return{metrics:[m('rA',raw),m('clip(r)A',clipped),m('최대화할 surrogate',Math.min(raw,clipped))],steps:[`허용 구간=[${n(1-p.epsilon)},${n(1+p.epsilon)}]`,`비율 clipping=${n(clip)}`,`두 항은 ${n(raw)}, ${n(clipped)}`,`작은 항=${n(Math.min(raw,clipped))}. 음수 A에서는 순서가 뒤집힐 수 있습니다.`],bars:[{label:'원래 항',value:raw},{label:'Clip 항',value:clipped}]};},'A 부호를 뒤집고 r를 0.5와 1.5로 비교하세요. clipping은 항상 비율을 해당 구간에 강제로 고정하는 규칙이 아닙니다.'),
};
