import { useState } from 'react';
import { activationNames,activationEquations,activationValue,activationDerivative } from '../lib/learningMath';
import { n } from '../lib/lessonModelTypes';
import { Formula, Slider } from './UI';
export default function ActivationDerivation() {
 const [mode,setMode]=useState(0),[x,setX]=useState(1),[upstream,setUpstream]=useState(1);
 const px=(v:number)=>52+(v+5)*47,py=(v:number)=>232-(v+1.5)*32;
 const curve=(derivative:boolean)=>{let pen=false;return Array.from({length:301},(_,i)=>{const x=i/30-5,y=derivative?activationDerivative(mode,x):activationValue(mode,x);if(y===null){pen=false;return'';}const segment=`${pen?'L':'M'}${px(x)},${py(y)}`;pen=true;return segment;}).join(' ');};
 const derivative=activationDerivative(mode,x),equation=activationEquations[mode];
 return <section className="topic-experiment activation-derivation"><span className="reading-label">함수에서 역전파로</span><h2>활성화 함수는 어떻게 미분할까요?</h2><p>선택한 함수의 전개와 미분 곡선을 함께 보세요. 모든 함수는 원소별로 적용하며 shape를 보존합니다. GELU는 tanh 근사를 사용합니다.</p><label className="standalone-select">활성화 함수<select aria-label="미분할 활성화 함수" value={mode} onChange={e=>setMode(Number(e.target.value))}>{activationNames.map((name,i)=><option key={name} value={i}>{name}</option>)}</select></label><Formula>{equation[0]}</Formula><h3>미분 과정</h3><Formula>{equation[1]}</Formula><p>{equation[2]}</p>
 <svg viewBox="0 0 580 310" role="img" aria-label={`${activationNames[mode]}의 함수와 해석적 미분 곡선`}><title>보라 함수값, 초록 미분값</title>{[-1,0,1,2,3,4,5].map(v=><g key={v}><line x1="52" x2="522" y1={py(v)} y2={py(v)} stroke="#e9e1ef"/><text x="44" y={py(v)+4} textAnchor="end">{v}</text></g>)}<line x1={px(0)} x2={px(0)} y1="18" y2="280" stroke="#b9a9c9"/><path d={curve(false)} stroke="#7561b8" fill="none" strokeWidth="3"/><path d={curve(true)} stroke="#488d7d" fill="none" strokeWidth="2.5"/>{mode<2&&[mode===0?0:.1,1].map(y=><circle key={y} cx={px(0)} cy={py(y)} r="4" fill="white" stroke="#488d7d" strokeWidth="2"/>)}<circle cx={px(x)} cy={py(activationValue(mode,x))} r="5" fill="#7561b8"/>{derivative!==null&&<circle cx={px(x)} cy={py(derivative)} r="5" fill="#488d7d"/>}{[-5,0,5].map(v=><text key={v} x={px(v)} y="303" textAnchor="middle">{v}</text>)}</svg><p className="curve-caption">가로 x · 보라 φ(x) · 초록 φ′(x) · 열린 점은 미분이 없는 위치</p><Slider label="미분할 입력 x" value={x} onChange={setX} min={-5} max={5} step={.1}/><Slider label="상류 gradient ∂L/∂h" value={upstream} onChange={setUpstream} min={-3} max={3} step={.1}/><div className="calculated-metrics"><div><span>φ(x)</span><strong>{n(activationValue(mode,x))}</strong></div><div><span>φ′(x)</span><strong>{derivative===null?'미분 없음':n(derivative)}</strong></div></div><Formula>∂L/∂x = (∂L/∂h) × φ′(x){'\n'}{derivative===null?'x=0의 고전적 미분이 없습니다. 구현에서 선택한 backward 값은 별도 규칙입니다.':`${n(upstream)} × ${n(derivative)} = ${n(upstream*derivative)}`}</Formula><p>상류 gradient가 활성화의 국소 미분을 통과해 아래층으로 전달됩니다. 큰 |x|에서 Sigmoid·tanh가 포화되면 이 경로의 gradient가 작아집니다.</p>
 <details><summary>여섯 함수의 미분을 한 번에 비교하기</summary>{activationNames.map((name,i)=><div key={name}><h3>{name}</h3><Formula>{activationEquations[i][1]}</Formula><p>{activationEquations[i][2]}</p></div>)}</details></section>;
}
