import { useState, type PointerEvent } from 'react';
import { type Topic } from '../data/curriculum';
import { clamp, fmt, gelu, softmax, sum } from '../lib/math';
import { computeShapes, defaultLayers, newLayer, type LayerKind } from '../lib/shapes';
import { documents, ganLoss, ganStep, initialGan, qUpdate, retrieve } from '../lib/experiments';
import { Bars, Card, Choice, Formula, Matrix, Metric, Note, Plot, PlotGrid, Slider } from './UI';

const sigmoid = (x: number) => 1 / (1 + Math.exp(-x));
const activations = { ReLU: (x: number) => Math.max(0, x), 'Leaky ReLU': (x: number) => x >= 0 ? x : .1 * x, tanh: Math.tanh, Sigmoid: sigmoid, GELU: gelu, SiLU: (x: number) => x * sigmoid(x) };
export function ActivationLab({ topic }: { topic: Topic }) {
  const [mode, setMode] = useState<'scalar' | 'softmax'>(['softmax', 'llm-basics', 'llm-generation', 'torch-losses', 'contrastive-learning', 'numerical-stability'].includes(topic.id) ? 'softmax' : 'scalar');
  const [name, setName] = useState<keyof typeof activations>('ReLU'), [input, setInput] = useState(1);
  const [logits, setLogits] = useState([2, 1, 0]), [temperature, setTemperature] = useState(1);
  const fn = activations[name], output = fn(input), derivative = (fn(input + 1e-4) - fn(input - 1e-4)) / 2e-4;
  const probabilities = softmax(logits, temperature);
  return <><Choice label="활성화 실험" value={mode} onChange={setMode} options={[{ value: 'scalar', label: '함수와 미분' }, { value: 'softmax', label: 'Logits → 확률' }]} />
    {mode === 'scalar' ? <div className="experiment-grid"><Card title="활성화와 변화율"><Choice label="활성화 함수" value={name} onChange={setName} options={Object.keys(activations).map(value => ({ value: value as keyof typeof activations, label: value }))} /><Plot label={`${name} 출력과 미분 곡선`}><PlotGrid />{[false, true].map(gradient => <path key={String(gradient)} d={Array.from({ length: 200 }, (_, i) => { const x = i / 199 * 8 - 4, y = gradient ? (fn(x + .0001) - fn(x - .0001)) / .0002 : fn(x); return `${i ? 'L' : 'M'}${300 + x * 65},${clamp(140 - y * 32, 15, 265)}`; }).join(' ')} fill="none" stroke={gradient ? '#488d7d' : '#7561b8'} strokeWidth="2" />)}<circle cx={300 + input * 65} cy={clamp(140 - output * 32, 15, 265)} r="6" fill="#7561b8" /></Plot><p className="micro">보라색: 함수 · 초록색: 수치 미분 · x 범위 −4 ~ 4</p><Slider label="입력 x" value={input} onChange={setInput} min={-4} max={4} step={.1} /></Card><Card title="입력 → 출력 → 미분"><div className="metrics"><Metric value={fmt(output, 3)} label={`${name}(${fmt(input)})`} /><Metric value={name.includes('ReLU') && input === 0 ? '미정의' : fmt(derivative, 3)} label="입력에 대한 변화율" /></div><Formula>z = xW+b{'\n'}h = φ(z){'\n'}∂ℒ/∂z = (∂ℒ/∂h) · φ′(z)</Formula><Note>미분 곡선은 중앙 차분 근사입니다. ReLU의 x=0 미분은 정의되지 않으며 구현체는 보통 특정 값을 선택합니다. 이 실험은 단일 함수의 계산으로, 학습된 결정경계는 아닙니다.</Note></Card></div>
      : <div className="experiment-grid"><Card title="세 후보의 Logits">{logits.map((value, i) => <Slider key={i} label={`logit ${i + 1}`} value={value} onChange={next => setLogits(current => current.map((v, j) => j === i ? next : v))} min={-5} max={5} step={.1} />)}<Slider label="온도 τ" value={temperature} onChange={setTemperature} min={.1} max={3} step={.1} /><Bars values={probabilities} labels={['후보 A', '후보 B', '후보 C']} /><Formula>pᵢ = exp((zᵢ−max z)/τ) / Σⱼ exp((zⱼ−max z)/τ)</Formula></Card><Card title="확률과 손실"><Matrix values={[probabilities]} name="Softmax 확률" probability /><div className="metrics"><Metric value={fmt(sum(probabilities), 6)} label="확률 합" /><Metric value={fmt(-Math.log(probabilities[0]), 3)} label="A가 정답일 때 −log p(A)" /></div><Note>세 후보에 대한 작은 수치 예제입니다. 온도·Logit을 바꾸면 실제 확률과 손실이 갱신됩니다. 최대값을 빼서 큰 exp를 피합니다.</Note></Card></div>}</>;
}
export function ShapeLab() {
  const [input, setInput] = useState([1, 3, 32, 32]), [layers, setLayers] = useState(defaultLayers);
  const [kind, setKind] = useState<LayerKind>('linear');
  const results = computeShapes(input, layers), valid = results.every(r => !r.error), params = sum(results.map(r => r.params));
  const update = (id: number, field: string, value: number) => setLayers(current => current.map(layer => layer.id === id ? { ...layer, [field]: value } : layer));
  const code = layers.map((layer, i) => {
    const r = results[i];
    if (r.error) return `# 레이어 ${i + 1}: ${r.error}`;
    switch (layer.kind) {
      case 'conv': return `nn.Conv2d(${r.input[1]}, ${layer.out}, ${layer.kernel}, stride=${layer.stride}, padding=${layer.padding}, dilation=${layer.dilation}),`;
      case 'pool': return `nn.MaxPool2d(${layer.kernel}, stride=${layer.stride}, padding=${layer.padding}, dilation=${layer.dilation}),`;
      case 'flatten': return 'nn.Flatten(start_dim=1),';
      case 'linear': return `nn.Linear(${r.input.at(-1)}, ${layer.out}),`;
      case 'relu': return 'nn.ReLU(),';
      default: return `# ${layer.kind === 'add' ? 'Residual Add' : 'Concat'}: 별도의 forward 구현 필요 (source=${layer.from + 1})`;
    }
  }).join('\n    ');
  const hasBranch = layers.some(layer => layer.kind === 'add' || layer.kind === 'concat');
  return <div className="shape-lab"><Card title="입력 텐서 · [B,C,H,W]" action={<button className="button small" onClick={() => { setInput([1, 3, 32, 32]); setLayers(defaultLayers()); }}>초기화</button>}><div className="number-fields">{['Batch', 'Channel', 'Height', 'Width'].map((label, i) => <label key={label}>{label}<input type="number" min="1" max={i === 0 ? 128 : 512} value={input[i]} onChange={e => setInput(current => current.map((v, j) => j === i ? clamp(Math.round(Number(e.target.value)) || 1, 1, i === 0 ? 128 : 512) : v))} /></label>)}</div></Card>
    <div className="shape-layers">{layers.map((layer, i) => <section key={layer.id} className={`shape-layer ${results[i].error ? 'error' : ''}`}><div className="shape-layer-title"><span className="step-number">{i + 1}</span><h3>{({ conv: 'Conv2d', pool: 'MaxPool2d', flatten: 'Flatten', linear: 'Linear', relu: 'ReLU', add: 'Residual Add', concat: 'Concat (dim=1)' })[layer.kind]}</h3><button className="icon-button" aria-label={`레이어 ${i + 1} 삭제`} onClick={() => setLayers(current => current.filter(l => l.id !== layer.id).map(l => ({ ...l, from: l.from >= i ? -1 : l.from })))}>×</button></div>
      <div className="number-fields compact">{(layer.kind === 'conv' || layer.kind === 'linear') && <label>출력 feature<input type="number" min="1" max="1024" value={layer.out} onChange={e => update(layer.id, 'out', clamp(Math.round(Number(e.target.value)) || 1, 1, 1024))} /></label>}{(layer.kind === 'conv' || layer.kind === 'pool') && ['kernel', 'stride', 'padding', 'dilation'].map(field => <label key={field}>{field}<input type="number" min={field === 'padding' ? 0 : 1} max="32" value={layer[field as 'kernel']} onChange={e => update(layer.id, field, clamp(Math.round(Number(e.target.value)) || (field === 'padding' ? 0 : 1), field === 'padding' ? 0 : 1, 32))} /></label>)}{(layer.kind === 'add' || layer.kind === 'concat') && <label>연결할 출력<select value={layer.from} onChange={e => update(layer.id, 'from', Number(e.target.value))}><option value={-1}>원본 입력</option>{layers.slice(0, i).map((_, index) => <option key={index} value={index}>레이어 {index + 1}</option>)}</select></label>}</div>
      <div className="shape-flow"><code>[{results[i].input.join(', ')}]</code><span>→</span><code>[{results[i].output.join(', ')}]</code><small>{results[i].params.toLocaleString()} params</small></div>{results[i].error ? <p role="alert" className="error-message">{results[i].error}</p> : <p className="micro">{results[i].formula}</p>}</section>)}</div>
    <div className="controls"><label className="inline-label">추가할 레이어<select aria-label="추가할 레이어" value={kind} onChange={e => setKind(e.target.value as LayerKind)}>{(['conv', 'pool', 'flatten', 'linear', 'relu', 'add', 'concat'] as const).map(v => <option key={v} value={v}>{v}</option>)}</select></label><button className="button" disabled={layers.length >= 16} onClick={() => setLayers(current => [...current, newLayer(Math.max(-1, ...current.map(l => l.id)) + 1, kind)])}>＋ 레이어 추가</button></div>
    <div className="two-cards"><Card title="설계 요약"><div className="metrics"><Metric value={valid ? params.toLocaleString() : '오류 확인'} label="총 학습 파라미터 · Bias 포함" /><Metric value={valid ? `${(params * 4 / 1024 ** 2).toFixed(2)} MiB` : '—'} label="FP32 가중치 원소 메모리" /></div><Note>Conv는 groups=1, 정사각 커널, Bias 사용 기준입니다. 입력 공간·배치를 바꿔도 Conv 파라미터 수는 변하지 않습니다. Flatten 이후 Linear 파라미터 수는 공간 크기에 따라 변합니다. Pool은 ceil_mode=False이며 Padding은 PyTorch에서 kernel/2 이하로 제한됩니다.</Note>{layers.some(l => l.kind === 'pool' && l.padding > Math.floor(l.kernel / 2)) && <p className="error-message">MaxPool padding이 kernel/2를 초과합니다. shape 공식과 별개로 실제 PyTorch 호출은 오류가 납니다.</p>}</Card><Card title={hasBranch ? 'PyTorch 레이어 정의 참고' : 'PyTorch 모델 코드'}><pre><code>{`import torch.nn as nn\n\n${hasBranch ? '# 분기는 nn.Module.forward에서 직접 연결합니다.\n# 아래는 각 레이어 정의입니다.\n' : 'model = nn.Sequential(\n    '}${code}${hasBranch ? '' : '\n)'}`}</code></pre></Card></div></div>;
}

export function VectorLab() {
  const [a, setA] = useState([1, 2]), [b, setB] = useState([2, 1]), [moving, setMoving] = useState<'a' | 'b' | null>(null);
  const dot = a[0] * b[0] + a[1] * b[1], na = Math.hypot(...a), nb = Math.hypot(...b), cosine = na && nb ? dot / na / nb : null;
  const move = (e: PointerEvent<SVGSVGElement>) => { if (!moving || !e.currentTarget.hasPointerCapture(e.pointerId)) return; const r = e.currentTarget.getBoundingClientRect(), vector = [clamp(((e.clientX - r.left) / r.width * 600 - 300) / 65, -4, 4), clamp((140 - (e.clientY - r.top) / r.height * 280) / 30, -4, 4)]; (moving === 'a' ? setA : setB)(vector); };
  return <div className="experiment-grid"><Card title="두 벡터를 움직여 보세요"><svg className="plot interactive-plot" viewBox="0 0 600 280" role="img" aria-label="두 벡터의 끝점을 드래그. 아래 슬라이더로도 조절 가능" onPointerDown={e => { const name = (e.target as Element).getAttribute('data-vector'); if (name === 'a' || name === 'b') { e.preventDefault(); setMoving(name); e.currentTarget.setPointerCapture(e.pointerId); } }} onPointerMove={move} onPointerUp={() => setMoving(null)} onPointerCancel={() => setMoving(null)}><PlotGrid />{[a, b].map((v, i) => <g key={i}><path d={`M300 140L${300 + v[0] * 65} ${140 - v[1] * 30}`} stroke={i ? '#488d7d' : '#7561b8'} strokeWidth="3" /><circle data-vector={i ? 'b' : 'a'} cx={300 + v[0] * 65} cy={140 - v[1] * 30} r="10" fill={i ? '#488d7d' : '#7561b8'} stroke="white" strokeWidth="3" /><text x={315 + v[0] * 65} y={135 - v[1] * 30}>{i ? 'b' : 'a'}</text></g>)}</svg>{[a, b].map((v, i) => v.map((value, j) => <Slider key={`${i}-${j}`} label={`${i ? 'b' : 'a'}${j + 1}`} value={value} onChange={next => (i ? setB : setA)(current => current.map((old, k) => j === k ? next : old))} min={-4} max={4} step={.1} />))}</Card><Card title="내적과 각도"><Formula>{`${fmt(a[0])} × ${fmt(b[0])} + ${fmt(a[1])} × ${fmt(b[1])} = ${fmt(dot)}`}</Formula><div className="metrics"><Metric value={fmt(dot)} label="내적 a·b" /><Metric value={cosine === null ? '미정의' : fmt(cosine, 3)} label="Cosine similarity" /><Metric value={cosine === null ? '—' : `${(Math.acos(clamp(cosine, -1, 1)) * 180 / Math.PI).toFixed(1)}°`} label="두 벡터의 각도" /><Metric value={fmt(Math.hypot(a[0] - b[0], a[1] - b[1]))} label="Euclidean distance" /></div><Note>축별 화면 스케일은 가독성을 위해 다릅니다. 숫자로 계산한 각도가 기준이며 0 벡터의 코사인·각도는 정의되지 않습니다.</Note></Card></div>;
}
export function GradientLab({ topic }: { topic: Topic }) {
  const [start, setStart] = useState(2), [rate, setRate] = useState(.2), [steps, setSteps] = useState(0);
  const history = [start]; for (let i = 0; i < steps; i++) history.push(history.at(-1)! * (1 - rate));
  const value = history.at(-1)!, clip = topic.id === 'training-stability';
  return <div className="experiment-grid"><Card title="1차원 손실 함수에서 이동하기"><Plot label="이차 손실과 Gradient descent 경로"><PlotGrid /><path d={Array.from({ length: 100 }, (_, i) => { const x = i / 99 * 8 - 4; return `${i ? 'L' : 'M'}${300 + x * 65},${250 - x * x * 12}`; }).join(' ')} fill="none" stroke="#7561b8" strokeWidth="2" />{history.map((x, i) => <circle key={i} cx={300 + clamp(x, -4, 4) * 65} cy={clamp(250 - x * x * 12, 15, 265)} r={i === steps ? 7 : 3} fill={i === steps ? '#488d7d' : '#b8acd7'} />)}</Plot><Slider label="시작점 x₀" value={start} onChange={v => { setStart(v); setSteps(0); }} min={-3} max={3} step={.1} /><Slider label="학습률 η" value={rate} onChange={v => { setRate(v); setSteps(0); }} min={.05} max={2.5} step={.05} /><div className="controls"><button className="button primary" disabled={steps >= 20} onClick={() => setSteps(v => v + 1)}>한 단계 이동</button><button className="button" onClick={() => setSteps(0)}>초기화</button></div></Card><Card title="손실 · Gradient · Update"><Formula>ℒ(x) = x²/2{'\n'}gradient = x{'\n'}xnext = x − ηx</Formula><div className="metrics"><Metric value={fmt(value, 4)} label={`${steps}단계 후 x`} /><Metric value={fmt(value * value / 2, 4)} label="손실" /></div>{clip && <><Formula>g=[3,4], c=2 → gclip=[1.2,1.6]</Formula><p>Clipping은 gradient 노름을 제한합니다. 위 실험은 clipping 전의 기본 경사하강을 보여줍니다.</p></>}<Note>이 이차함수에서는 0&lt;η&lt;2일 때 수렴합니다. 그래프 범위를 벗어난 점은 가장자리에 표시하며 수치 값은 그대로 계산합니다. 신경망·일반 손실의 수렴 보장은 아닙니다.</Note></Card></div>;
}
export function ProbabilityLab() {
  const [p, setP] = useState(.3), [q, setQ] = useState(.5), [n, setN] = useState(20);
  const entropy = -(p * Math.log(p) + (1 - p) * Math.log(1 - p)), ce = -(p * Math.log(q) + (1 - p) * Math.log(1 - q));
  return <div className="experiment-grid"><Card title="두 Bernoulli 분포 비교"><Slider label="분포 p · 성공 확률" value={p} onChange={setP} min={.01} max={.99} step={.01} /><Slider label="모델 q · 성공 확률" value={q} onChange={setQ} min={.01} max={.99} step={.01} /><Bars values={[p, 1 - p]} labels={['p · 성공', 'p · 실패']} /><Bars values={[q, 1 - q]} labels={['q · 성공', 'q · 실패']} /><Slider label="표본 수 n" value={n} onChange={setN} min={5} max={200} /><Formula>Var(X) = p(1−p){'\n'}SD(표본평균) = √(p(1−p)/n)</Formula></Card><Card title="확률과 정보량"><div className="metrics"><Metric value={fmt(p)} label="기댓값 E[X]" /><Metric value={fmt(p * (1 - p), 4)} label="분산" /><Metric value={fmt(entropy, 4)} label="엔트로피 H(p) · nats" /><Metric value={fmt(ce - entropy, 4)} label="KL(p∥q) · nats" /><Metric value={fmt(ce, 4)} label="교차엔트로피 CE(p,q)" /><Metric value={fmt(Math.sqrt(p * (1 - p) / n), 4)} label="표본평균의 표준편차" /></div><Note>독립이고 같은 p를 갖는 Bernoulli 표본의 이론값입니다. 표본평균의 표준편차와 개별 표본의 분산은 다릅니다. 실제 무작위 표집이나 다중 클래스 증류 전체를 실행하는 실험은 아닙니다.</Note></Card></div>;
}
export function RegressionLab() {
  const [slope, setSlope] = useState(1), [bias, setBias] = useState(0), [ys, setYs] = useState([-1, 1, 3]);
  const xs = [-1, 0, 1], predictions = xs.map(x => slope * x + bias), loss = sum(ys.map((y, i) => (y - predictions[i]) ** 2)) / 3;
  return <div className="experiment-grid"><Card title="직선과 잔차"><Plot label="회귀선과 세 표본의 잔차"><PlotGrid /><path d={`M40 ${200 - (-2 * slope + bias) * 30}L560 ${200 - (2 * slope + bias) * 30}`} stroke="#7561b8" strokeWidth="2" />{xs.map((x, i) => <g key={x}><path d={`M${300 + x * 130} ${200 - ys[i] * 30}V${200 - predictions[i] * 30}`} stroke="#c1775b" strokeDasharray="4 3" /><circle cx={300 + x * 130} cy={200 - ys[i] * 30} r="7" fill="#488d7d" /></g>)}</Plot><Slider label="기울기 w" value={slope} onChange={setSlope} min={-3} max={3} step={.1} /><Slider label="절편 b" value={bias} onChange={setBias} min={-2} max={2} step={.1} />{ys.map((value, i) => <Slider key={i} label={`표본 x=${xs[i]}의 y`} value={value} onChange={next => setYs(current => current.map((v, j) => j === i ? next : v))} min={-2} max={4} step={.1} />)}</Card><Card title="오차가 어떻게 달라질까?"><Formula>ŷ = wx+b{'\n'}MSE = Σ(yᵢ−ŷᵢ)²/3</Formula><Metric value={fmt(loss, 4)} label="Mean squared error" /><div className="matrix-scroll"><div className="matrix-line"><Matrix values={[ys]} name="y · 정답" color="green" /><Matrix values={[predictions]} name="ŷ · 예측" /></div></div><Note>세 표본의 훈련 오차만 보여줍니다. 일반화 성능은 별도 검증 자료로 평가해야 합니다. 잔차의 부호와 제곱오차를 구분하세요.</Note></Card></div>;
}
const clusterPoints = [[-.9, -.5], [-1.8, .8], [-1.4, -.2], [.9, .6], [1.6, -.5], [2.2, .7]];
export function ClusterLab() {
  const [centers, setCenters] = useState([[-1, 1], [1, -1]]), [steps, setSteps] = useState(0);
  const assignments = clusterPoints.map(point => Math.hypot(point[0] - centers[0][0], point[1] - centers[0][1]) <= Math.hypot(point[0] - centers[1][0], point[1] - centers[1][1]) ? 0 : 1);
  const cost = sum(clusterPoints.map((p, i) => sum(p.map((v, j) => (v - centers[assignments[i]][j]) ** 2))));
  function step() { setCenters(current => current.map((center, i) => { const members = clusterPoints.filter((_, index) => assignments[index] === i); return members.length ? [0, 1].map(dim => sum(members.map(p => p[dim])) / members.length) : center; })); setSteps(v => v + 1); }
  return <div className="experiment-grid"><Card title="할당 → 중심 갱신"><Plot label="두 군집과 중심점"><PlotGrid />{clusterPoints.map((p, i) => <circle key={i} cx={300 + p[0] * 85} cy={140 - p[1] * 65} r="7" fill={assignments[i] ? '#488d7d' : '#7561b8'} />)}{centers.map((p, i) => <g key={i}><rect x={292 + p[0] * 85} y={132 - p[1] * 65} width="16" height="16" fill={i ? '#488d7d' : '#7561b8'} stroke="white" strokeWidth="2" /><text x={312 + p[0] * 85} y={145 - p[1] * 65}>μ{i + 1}</text></g>)}</Plot>{centers.map((center, i) => center.map((value, j) => <Slider key={`${i}-${j}`} label={`중심 ${i + 1} · ${j ? 'y' : 'x'}`} value={value} onChange={next => { setCenters(current => current.map((p, k) => k === i ? p.map((v, d) => d === j ? next : v) : p)); setSteps(0); }} min={-3} max={3} step={.1} />))}<div className="controls"><button className="button primary" onClick={step}>중심 갱신</button><button className="button" onClick={() => { setCenters([[-1, 1], [1, -1]]); setSteps(0); }}>초기화</button></div></Card><Card title="k-means 목적함수"><Formula>J = Σᵢ ‖xᵢ−μcᵢ‖²</Formula><div className="metrics"><Metric value={fmt(cost, 4)} label="군집 내 제곱거리 합" /><Metric value={steps} label="중심 갱신 횟수" /></div><Matrix values={centers} name="μ · 중심" /><Note>2차원 6개 점과 k=2의 실제 k-means 계산입니다. 동률은 첫 군집에 할당하고 빈 군집은 이전 중심을 유지합니다. 매 갱신 후 가까운 중심으로 다시 할당합니다.</Note></Card></div>;
}

export function RagLab() {
  const [query, setQuery] = useState([1, 0, 0, 0]), [k, setK] = useState(2), [budget, setBudget] = useState(300);
  const result = retrieve(query, k, budget), included = result.candidates.filter(d => d.included);
  return <div className="experiment-grid"><Card title="질문 벡터 → 청크 검색">{['어텐션', '차원', '캐시', '학습'].map((word, i) => <Slider key={word} label={`질문 · ${word}`} value={query[i]} onChange={next => setQuery(current => current.map((v, j) => j === i ? next : v))} min={0} max={3} step={.1} />)}<Slider label="검색 Top-k" value={k} onChange={setK} min={1} max={4} /><Slider label="근거 토큰 예산" value={budget} onChange={setBudget} min={100} max={600} step={50} />
    <div className="retrieval-results">{result.ranked.map((doc, index) => { const candidate = result.candidates.find(d => d.id === doc.id); return <div className={`retrieval-row ${candidate?.included ? 'included' : ''}`} key={doc.id}><span>{index + 1}</span><div><b>{doc.title}</b><small>{doc.tokens} 가정 토큰 · [{doc.vector.join(', ')}]</small></div><output>{fmt(doc.score, 3)}</output><small>{candidate ? candidate.included ? '문맥 포함' : '예산 초과' : 'Top-k 밖'}</small></div>; })}</div><Formula>score = cos(query, document)</Formula></Card><Card title="모델에 전달할 근거 문맥"><div className="metrics"><Metric value={included.length} label="포함 청크" /><Metric value={`${result.spent} / ${budget}`} label="가정 토큰 사용" /></div>{included.length ? included.map(doc => <blockquote key={doc.id}><b>[{doc.id}] {doc.title}</b><p>{doc.text}</p></blockquote>) : <p className="empty-state">예산 안에 들어오는 근거가 없습니다.</p>}<Note>실제 LLM 호출 없이 검색과 문맥 구성을 실행합니다. 벡터는 단어별 가중치로 만든 예제이며 학습된 의미 임베딩이 아닙니다. 토큰 수는 고정한 가정값입니다. 0 벡터는 유사도 0으로 처리하며 동률은 문서 순서를 유지합니다.</Note><details><summary>전체 예제 청크</summary>{documents.map(doc => <p key={doc.id}>[{doc.id}] {doc.text}</p>)}</details></Card></div>;
}
const flowModels: Record<string, { names: string[]; payloads: string[] }> = {
  prompting: { names: ['지시', '예시', '자료', '질문', '문맥 구성'], payloads: ['형식: 한 문장으로 답하기', '예시: 내적은 방향의 정렬 정도를 측정한다.', '참고 자료: 벡터의 정의', '질문: 내적이란?', '지시와 자료의 역할을 분리한 입력 문맥'] },
  cot: { names: ['문제', '풀이 후보', '답 비교', '검산'], payloads: ['3 × (2 + 2)의 값은?', '후보 답변: 12 / 12 / 15', '다수결 후보 12', '3 × 4 = 12 · 외부 계산으로 확인'] },
  ontology: { names: ['타입', '관계 정의', '사실 추가', '타입 추론'], payloads: ['민수: Person, A회사: Company ⊑ Organization', 'worksFor: domain Person / range Organization', '민수 worksFor A회사', 'domain·range로 Person·Organization을 추론 · 입력 검증은 별도 규칙'] },
  graphrag: { names: ['원본 문서', '개체·관계', '커뮤니티 요약', '검색', '근거 구성'], payloads: ['A회사와 B회사가 협력한다. B회사는 C분야를 연구한다.', 'A—협력→B—연구→C', 'A·B·C를 묶은 예제 커뮤니티 요약', 'A회사 관련 부분 그래프 검색', '직접 관계와 관련 요약을 함께 구성'] },
  'llm-wiki': { names: ['원본 보존', '정보 추출', '개념 페이지', '링크·출처', '갱신 기록'], payloads: ['원본 A: 모델은 4개 헤드를 사용한다.', '개체: 모델 · 속성: head_count=4', '모델 페이지에 출처 A와 함께 기록', '관련 Attention 페이지와 연결', '새 자료가 8개 헤드라고 하면 충돌과 날짜를 기록'] },
  'knowledge-strategies': { names: ['질문 분류', '자료 선택', '전략 선택', '실행', '평가'], payloads: ['최신 수치? 응답 형식? 관계 탐색?', '수치의 최신 원본과 신뢰도 확인', '외부 근거 검색 + 출력 형식 예시', '선택한 방법은 함께 결합할 수 있음', '정답·출처·비용을 각각 확인'] },
  'tools-agents': { names: ['요청', '호출 제안', '인수 검사', '도구 실행', '결과 반환'], payloads: ['2 + 3을 계산해줘', 'add({a:2,b:3})', 'a,b가 숫자인지 확인', '실제 계산: 2 + 3', 'result: 5'] },
  mcp: { names: ['Host', 'Client', 'Server 기능 조회', '도구 호출', '결과'], payloads: ['애플리케이션이 연결을 관리', '서버와 프로토콜 통신', 'tools/list → add 도구와 schema', 'tools/call → {name:add, arguments:{a:2,b:3}}', '서버 계산 결과 5를 Host에 제공'] },
  harness: { names: ['실행 상태', '문맥 구성', '모델 호출', '도구·권한 검사', '상태·로그 저장'], payloads: ['task: 2+3 계산, step:0', '질문과 도구 schema를 입력에 구성', '도구 호출 제안 add(2,3)', '입력을 검사하고 허용된 계산 실행', 'result:5, done:true · 종료 조건 충족'] },
  'llm-evaluation': { names: ['평가 사례', '실행', '정답 확인', '근거 확인', '지표 집계'], payloads: ['정답이 5인 도구 작업', 'add(2,3) → 5', '도구 결과와 정답 일치', '결과와 답변이 연결되는지 확인', '성공률·모델 호출 수·재시도 수 기록'] },
};
export function FlowLab({ topic }: { topic: Topic }) {
  const model = flowModels[topic.id] ?? flowModels.harness;
  const [step, setStep] = useState(0), [scenario, setScenario] = useState<'normal' | 'failure'>('normal'), [retries, setRetries] = useState(0), [limit, setLimit] = useState(2);
  const supportsRetry = ['mcp', 'harness', 'tools-agents', 'llm-evaluation'].includes(topic.id), atTool = step === model.names.length - 2;
  const failed = supportsRetry && scenario === 'failure' && atTool && retries >= limit;
  const next = () => { if (supportsRetry && scenario === 'failure' && atTool) setRetries(r => Math.min(limit, r + 1)); else setStep(s => Math.min(model.names.length - 1, s + 1)); };
  const reset = () => { setStep(0); setRetries(0); };
  return <div className="experiment-grid"><Card title="흐름을 한 단계씩 따라가기"><div className="workflow">{model.names.map((name, i) => <button key={name} className={step === i ? 'active' : step > i ? 'visited' : ''} onClick={() => { setStep(i); setRetries(0); }} aria-current={step === i ? 'step' : undefined}><span>{String(i + 1).padStart(2, '0')}</span><b>{name}</b><small>{step > i ? '완료' : step === i ? '현재 단계' : '대기'}</small></button>)}</div>{supportsRetry && <><Choice label="도구 실행 시나리오" value={scenario} onChange={value => { setScenario(value); reset(); }} options={[{ value: 'normal', label: '정상 응답' }, { value: 'failure', label: '도구 실패' }]} /><Slider label="재시도 한도" value={limit} onChange={v => { setLimit(v); reset(); }} min={1} max={3} /></>}<div className="controls"><button className="button primary" disabled={step === model.names.length - 1 || failed} onClick={next}>{supportsRetry && scenario === 'failure' && atTool ? '도구 재시도' : '한 단계 진행'}</button><button className="button" onClick={reset}>처음부터</button></div></Card><Card title={model.names[step]}><pre className="payload"><code>{supportsRetry && scenario === 'failure' && atTool ? `tool_error: 예제 도구 응답 실패\nretry: ${retries}/${limit}\n${failed ? 'status: 중단 · 오류 상태와 로그 보존' : 'status: 재시도 대기'}` : model.payloads[step]}</code></pre>{supportsRetry && <div className="metrics"><Metric value={retries} label="실패 후 재시도 횟수" /><Metric value={failed ? '중단' : step === model.names.length - 1 ? '완료' : '진행'} label="실행 상태" /></div>}<Note>구조와 메시지를 이해하기 위한 로컬 시뮬레이션입니다. 실제 LLM·MCP 서버를 호출하지 않으며, 단계 선택은 흐름을 탐색하는 기능입니다. 실패 시 재시도 한도에 따라 상태가 실제로 바뀝니다.</Note></Card></div>;
}
export function GanLab() {
  const [state, setState] = useState(initialGan), [rate, setRate] = useState(.1);
  const d = ganLoss(state);
  return <div className="experiment-grid"><Card title="Generator와 Discriminator 교대 업데이트"><Plot label="실제와 생성한 1차원 표본, 판별자의 확률"><PlotGrid /><path d={Array.from({ length: 100 }, (_, i) => { const x = i / 99 * 8 - 4; return `${i ? 'L' : 'M'}${300 + x * 65},${235 - sigmoid(state.a * x + state.b) * 185}`; }).join(' ')} fill="none" stroke="#7561b8" strokeWidth="2" />{[d.real, d.fake].map((xs, group) => xs.map((x, i) => <circle key={`${group}-${i}`} cx={300 + clamp(x, -4, 4) * 65} cy={group ? 250 : 235} r="5" fill={group ? '#c1775b' : '#488d7d'} />))}<text x="35" y="25">곡선 D(x) · 초록: 진짜 · 주황: 생성</text></Plot><Slider label="학습률" value={rate} onChange={setRate} min={.01} max={.5} step={.01} /><div className="controls"><button className="button" onClick={() => setState(s => ganStep(s, 'd', rate))}>D 업데이트</button><button className="button primary" onClick={() => setState(s => ganStep(s, 'g', rate))}>G 업데이트</button><button className="button" onClick={() => setState(initialGan())}>초기화</button></div><Formula>G(z)=μ+sz{'\n'}D(x)=sigmoid(ax+b)</Formula></Card><Card title="실제로 계산한 손실"><div className="metrics"><Metric value={fmt(d.dLoss, 4)} label="Discriminator loss" /><Metric value={fmt(d.gLoss, 4)} label="Generator loss" /><Metric value={fmt(state.mean, 3)} label="생성 평균 μ · 실제 1.5" /><Metric value={fmt(state.scale, 3)} label="생성 스케일 s · 기준 0.6" /></div><Metric value={state.steps} label="파라미터 업데이트 횟수" /><Note>고정된 7개 z 표본에서 두 모델의 손실 미분을 계산합니다. G 업데이트는 D를 고정하고 D 업데이트는 G를 고정합니다. 1차원 선형 생성자는 여러 mode를 표현할 수 없으며 실제 이미지 GAN의 학습·수렴을 재현하지 않습니다.</Note></Card></div>;
}
export function QLearningLab() {
  const [q, setQ] = useState(2), [reward, setReward] = useState(1), [nextQ, setNextQ] = useState(4), [rate, setRate] = useState(.5), [discount, setDiscount] = useState(.9), [terminal, setTerminal] = useState(false), [steps, setSteps] = useState(0);
  const d = qUpdate(q, reward, nextQ, rate, discount, terminal);
  return <div className="experiment-grid"><Card title="하나의 전이에서 Q값 갱신"><div className="dimension-path"><span>상태 s · Q={fmt(q)}</span>→<span>행동 a · r={reward}</span>→<span>상태 s′ · max Q={nextQ}</span></div><Slider label="보상 r" value={reward} onChange={setReward} min={-3} max={3} step={.1} /><Slider label="다음 최대 Q" value={nextQ} onChange={setNextQ} min={-5} max={5} step={.1} /><Slider label="학습률 α" value={rate} onChange={setRate} min={.05} max={1} step={.05} /><Slider label="할인율 γ" value={discount} onChange={setDiscount} min={0} max={1} step={.05} /><label className="check"><input type="checkbox" checked={terminal} onChange={e => setTerminal(e.target.checked)} />종료 상태 · 미래 가치 0</label><div className="controls"><button className="button primary" onClick={() => { setQ(d.value); setSteps(s => s + 1); }}>Q 업데이트</button><button className="button" onClick={() => { setQ(2); setSteps(0); }}>Q 초기화</button></div></Card><Card title="TD 목표와 오차"><Formula>target = r + γ max Q(s′,a′){'\n'}δ = target − Q(s,a){'\n'}Qnext = Q + αδ</Formula><div className="metrics"><Metric value={fmt(d.target, 3)} label="TD 목표" /><Metric value={fmt(d.error, 3)} label="TD 오차" /><Metric value={fmt(d.value, 3)} label="다음 Q" /><Metric value={steps} label="업데이트 횟수" /></div><Note>하나의 전이를 반복 갱신하는 계산 예제입니다. 환경 탐색·정책 학습 전체를 실행하지는 않습니다. 종료 상태에서는 γ 값과 무관하게 target=r입니다.</Note></Card></div>;
}
export function Lab({ topic }: { topic: Topic }) {
  switch (topic.lab) {
    case 'activation': return <ActivationLab topic={topic} />;
    case 'shape': return <ShapeLab />;
    case 'vectors': return <VectorLab />;
    case 'gradient': return <GradientLab topic={topic} />;
    case 'probability': return <ProbabilityLab />;
    case 'regression': return <RegressionLab />;
    case 'clustering': return <ClusterLab />;
    case 'rag': return <RagLab />;
    case 'flow': return <FlowLab topic={topic} />;
    case 'gan': return <GanLab />;
    case 'qlearning': return <QLearningLab />;
    default: return null;
  }
}
