import type { Calculation } from '../lib/lessonModelTypes';
import { n, normal } from '../lib/lessonModelTypes';

export default function TopicScene({topicId,p,result}:{topicId:string;p:Record<string,number>;result:Calculation}) {
  if(topicId==='graphrag'){
    const names=['A회사','B회사','C회사','제품X','연구Y'],edges=[[0,1],[1,2],[0,3],[2,4]],positions=[[80,80],[230,80],[380,80],[80,220],[380,220]],start=p.start?2:0,dist=[Infinity,Infinity,Infinity,Infinity,Infinity];dist[start]=0;const queue=[start];while(queue.length){const at=queue.shift()!;for(const [a,b] of edges){const next=a===at?b:b===at?a:-1;if(next>=0&&dist[next]===Infinity){dist[next]=dist[at]+1;queue.push(next);}}}
    return <figure className="topic-scene"><svg viewBox="0 0 460 290" role="img" aria-label="탐색 hop 안에 들어오는 지식 그래프 개체">{edges.map(([a,b],i)=><line key={i} x1={positions[a][0]} y1={positions[a][1]} x2={positions[b][0]} y2={positions[b][1]} stroke={dist[a]<=p.depth&&dist[b]<=p.depth?'#a088bf':'#dfd6e7'} strokeWidth="3"/>)}{names.map((name,i)=><g key={name}><circle cx={positions[i][0]} cy={positions[i][1]} r="30" fill={i===start?'#dbc9ed':dist[i]<=p.depth?'#dfeee6':'#f2edf6'} stroke={dist[i]<=p.depth?'#a088bf':'#ded4e7'}/><text x={positions[i][0]} y={positions[i][1]+5} textAnchor="middle">{name}</text><text x={positions[i][0]} y={positions[i][1]+50} textAnchor="middle">{dist[i]} hop</text></g>)}</svg><figcaption>보라: 출발 개체 · 초록: hop 한도 안의 개체. 선은 고정 자료에 기록된 관계입니다. 실제 GraphRAG는 개체·관계 추출과 커뮤니티 요약의 원문 근거도 관리해야 합니다.</figcaption></figure>;
  }
  if(topicId==='gnn'){
    return <figure className="topic-scene"><svg viewBox="0 0 460 250" role="img" aria-label="이웃 연결이 중앙 노드 표현에 전달하는 값"><line x1="100" y1="70" x2="230" y2="165" stroke="#9e87b8" strokeWidth="3"/>{p.count>0&&<line x1="360" y1="70" x2="230" y2="165" stroke="#9e87b8" strokeWidth="3"/>}{[[100,70,'이웃 2'],[360,70,`이웃 ${n(p.x)}`],[230,165,`자신 1 → ${n(result.metrics[1].value!)}`]].map(([x,y,label],i)=><g key={i}><rect x={Number(x)-66} y={Number(y)-22} width="132" height="44" rx="12" fill={i===2?'#e1eee6':'#eee6f6'} stroke="#d6c8e2"/><text x={x} y={Number(y)+5} textAnchor="middle">{label}</text></g>)}</svg><figcaption>연결된 이웃만 집계합니다. 자기 값에 집계를 더하고 ReLU를 적용한 중앙의 새 값이 표시됩니다. 이 예제의 weight는 모두 1입니다.</figcaption></figure>;
  }
  if(topicId==='neural-network'){
    const stages=[['입력 x',p.x],['선형 z=xw+1',p.x*p.w+1],['Sigmoid h',result.metrics[0].value!],['손실 L',result.metrics[1].value!]];
    return <figure className="topic-scene"><div className="computed-flow">{stages.map(([label,value],i)=><div key={i}><span>{label}</span><strong>{n(Number(value))}</strong>{i<stages.length-1&&<i aria-hidden>→</i>}</div>)}</div><figcaption>순전파는 왼쪽에서 오른쪽으로 값을 계산합니다. 역전파는 각 화살표의 국소 미분을 곱해 손실에서 weight까지 거꾸로 전달합니다.</figcaption></figure>;
  }
  if(topicId==='ontology'){
    return <figure className="topic-scene"><div className="computed-flow ontology-flow"><div><span>주어: {p.reverse?'A회사':'민수'}</span><strong>Person</strong><i aria-hidden>→</i></div><div><span>관계</span><strong>worksFor</strong><i aria-hidden>→</i></div><div><span>목적어: {p.reverse?'민수':'A회사'}</span><strong>Organization</strong></div></div><figcaption>화살표 방향의 주어에 domain, 목적어에 range 타입을 추론합니다. 자동으로 오류를 거절하는 입력 검사와는 다른 규칙입니다.</figcaption></figure>;
  }
  const planeIds=['vectors','matrices','eigen-svd','dimensionality-reduction'];
  if(planeIds.includes(topicId)){
    const point=(x:number,y:number)=>[230+x*30,175-y*30];
    const line=(a:number[],b:number[],color:string,key:string,dash=false)=>{const from=point(...a as [number,number]),to=point(...b as [number,number]);return <line key={key} x1={from[0]} y1={from[1]} x2={to[0]} y2={to[1]} stroke={color} strokeWidth={dash?1.5:3} strokeDasharray={dash?'5 5':undefined}/>;};
    let marks:React.ReactNode,caption:string;
    if(topicId==='vectors'){const rows=result.matrix!.values;marks=<>{line([0,0],rows[0],'#8d68b6','a')}{line([0,0],rows[1],'#5d9d8e','b')}{line([0,0],rows[2],'#c68b57','projection')}{line(rows[0],rows[2],'#b59bc5','perpendicular',true)}{rows.map((row,i)=>{const [x,y]=point(row[0],row[1]);return <g key={i}><circle cx={x} cy={y} r="5" fill={['#8d68b6','#5d9d8e','#c68b57'][i]}/><text x={x+7} y={y-8}>{['a','b','a의 투영'][i]}</text></g>;})}</>;caption='보라: a · 초록: b · 주황: a를 b 방향에 투영 · 점선: 투영 후 남은 수직 성분. 오른쪽이 x, 위쪽이 y입니다.';}
    else if(topicId==='matrices'||topicId==='eigen-svd'){const a=topicId==='matrices'?[[p.scale,p.shear],[0,1]]:[[p.a,0],[0,p.b]],apply=(v:number[])=>[a[0][0]*v[0]+a[0][1]*v[1],a[1][0]*v[0]+a[1][1]*v[1]];marks=<>{[-2,-1,0,1,2].map(i=><g key={i}>{line(apply([i,-2]),apply([i,2]),'#b899ce',`v${i}`,true)}{line(apply([-2,i]),apply([2,i]),'#b899ce',`h${i}`,true)}</g>)}{line([0,0],apply([1,0]),'#8d68b6','e1')}{line([0,0],apply([0,1]),'#5d9d8e','e2')}<text x="22" y="28">보라: 변환된 (1,0) · 초록: 변환된 (0,1)</text></>;caption='회색은 원래 좌표축, 점선은 A를 적용한 격자입니다. 행렬의 두 열은 두 단위 축이 이동한 결과입니다. 그림 범위를 넘어서는 선은 잘립니다.';}
    else {const angle=p.angle*Math.PI/180,u=[Math.cos(angle),Math.sin(angle)],points=[[-3,-1],[-3,1],[3,-1],[3,1]];marks=<>{line(u.map(v=>-5*v),u.map(v=>5*v),'#5d9d8e','axis')}{points.map((v,i)=>{const z=v[0]*u[0]+v[1]*u[1],projected=u.map(x=>x*z),a=point(v[0],v[1]),b=point(projected[0],projected[1]);return <g key={i}>{line(v,projected,'#beabc9',`p${i}`,true)}<circle cx={a[0]} cy={a[1]} r="6" fill="#8d68b6"/><circle cx={b[0]} cy={b[1]} r="5" fill="#c68b57"/></g>;})}</>;caption='보라: 원래 점 · 초록: 선택한 투영 축 · 주황: 1차원 좌표로부터 복원한 점. 점선 길이가 버린 정보의 거리입니다.';}
    return <figure className="topic-scene"><svg viewBox="0 0 460 350" role="img" aria-label={`${topicId}의 현재 입력에 대한 좌표 시각화`}><defs><clipPath id={`clip-${topicId}`}><rect x="8" y="8" width="444" height="330"/></clipPath></defs><g clipPath={`url(#clip-${topicId})`}>{[-5,-4,-3,-2,-1,0,1,2,3,4,5].map(v=><g key={v}><line x1={point(v,0)[0]} x2={point(v,0)[0]} y1="20" y2="330" stroke={v===0?'#b6a6c5':'#eee8f2'}/><line x1="15" x2="445" y1={point(0,v)[1]} y2={point(0,v)[1]} stroke={v===0?'#b6a6c5':'#eee8f2'}/></g>)}{marks}<text x="433" y="169">x</text><text x="237" y="22">y</text><text x="235" y="193">0</text></g></svg><figcaption>{caption}</figcaption></figure>;
  }
  if(topicId==='derivatives'||topicId==='linear-regression'){
    const f=topicId==='derivatives'?(x:number)=>(2*x+1)**2:(x:number)=>p.w*(p.degree?x*x:x)+p.b;
    const xmin=topicId==='derivatives'?p.x-1.2:-1.5,xmax=topicId==='derivatives'?p.x+1.2:1.5,xs=Array.from({length:121},(_,i)=>xmin+(xmax-xmin)*i/120),dots=topicId==='derivatives'?[[p.x,f(p.x)],[p.x+p.h,f(p.x+p.h)]]:[[-1,-1],[0,1],[1,3]],ys=xs.map(f).concat(dots.map(v=>v[1])),min=Math.min(...ys)-1,max=Math.max(...ys)+1,px=(x:number)=>40+(x-xmin)/(xmax-xmin)*440,py=(y:number)=>255-(y-min)/(max-min)*210,path=xs.map((x,i)=>`${i?'L':'M'}${px(x)},${py(f(x))}`).join(' '),tangent=(x:number)=>f(p.x)+4*(2*p.x+1)*(x-p.x),secant=(x:number)=>f(p.x)+(f(p.x+p.h)-f(p.x))/p.h*(x-p.x);
    return <figure className="topic-scene"><svg viewBox="0 0 520 300" role="img" aria-label={topicId==='derivatives'?'관찰 점의 접선과 두 점의 할선':'예측선과 관측 표본의 잔차'}><defs><clipPath id={`curve-${topicId}`}><rect x="40" y="40" width="440" height="220"/></clipPath></defs><g clipPath={`url(#curve-${topicId})`}><path d={path} fill="none" stroke="#8d68b6" strokeWidth="3"/>{topicId==='derivatives'?<><line x1={px(xmin)} x2={px(xmax)} y1={py(tangent(xmin))} y2={py(tangent(xmax))} stroke="#579786" strokeWidth="2"/><line x1={px(xmin)} x2={px(xmax)} y1={py(secant(xmin))} y2={py(secant(xmax))} stroke="#c59057" strokeWidth="2" strokeDasharray="6 4"/></>:dots.map(([x,y],i)=><line key={i} x1={px(x)} x2={px(x)} y1={py(y)} y2={py(f(x))} stroke="#c59057" strokeWidth="2" strokeDasharray="5 4"/>)}{dots.map(([x,y],i)=><circle key={i} cx={px(x)} cy={py(y)} r="5" fill="#c59057"/>)}</g><line x1="40" x2="480" y1="260" y2="260" stroke="#b0a2bd"/><text x="40" y="284">x={n(xmin)}</text><text x="480" y="284" textAnchor="end">x={n(xmax)}</text><text x="40" y="22">세로축: {topicId==='derivatives'?'f(x)':'예측값 y'}</text></svg><figcaption>{topicId==='derivatives'?'보라: 실제 함수 · 초록: 정확 접선 · 주황 점선: x와 x+h 사이의 할선. h를 줄이면 두 기울기가 가까워집니다.':'보라: 현재 모델의 예측 · 주황 점: 실제 정답 · 수직 점선: 잔차. 오차는 이 수직 거리의 제곱으로 계산합니다.'}</figcaption></figure>;
  }
  if(['kmeans','hierarchical-dbscan','knn'].includes(topicId)){
    const xs=topicId==='kmeans'?result.matrix!.values[0]:topicId==='knn'?[-3,-1,0,2,4]:[0,.2,.4,1.2,3],labels=topicId==='kmeans'?result.matrix!.values[1]:topicId==='knn'?[0,0,1,1,1]:result.matrix!.values[2],xmin=-5,xmax=5,px=(x:number)=>35+(x-xmin)/(xmax-xmin)*450;
    return <figure className="topic-scene"><svg viewBox="0 0 520 180" role="img" aria-label="표본의 실제 위치와 군집 또는 클래스"><line x1="35" x2="485" y1="95" y2="95" stroke="#bcaacb"/>{Array.from({length:11},(_,i)=>i-5).map(x=><g key={x}><line x1={px(x)} x2={px(x)} y1="90" y2="100" stroke="#bcaacb"/><text x={px(x)} y="127" textAnchor="middle">{x}</text></g>)}{xs.map((x,i)=><g key={i}><circle cx={px(x)} cy={65-(i%2)*10} r="7" fill={['#bea5ce','#62a594','#bd8951'][labels[i]]}/><text x={px(x)} y={45-(i%2)*10} textAnchor="middle">{n(x)}</text></g>)}{topicId==='kmeans'?result.metrics.slice(0,2).map((m,i)=><g key={i}><path d={`M${px(m.value!)} 85l-7 14h14z`} fill={i?'#62a594':'#bea5ce'}/><text x={px(m.value!)} y="157" textAnchor="middle">μ{i+1}={n(m.value!)}</text></g>):topicId==='knn'?<><line x1={px(p.x)} x2={px(p.x)} y1="55" y2="110" stroke="#c27e4f"/><text x={px(p.x)} y="157" textAnchor="middle">질문 {n(p.x)}</text></>:null}</svg><figcaption>{topicId==='kmeans'?'점 색은 가장 가까운 중심에 대한 할당, 삼각형은 현재 중심입니다. 갱신 횟수를 늘려 중심이 평균으로 옮겨가는 과정을 보세요.':topicId==='knn'?'점 색은 클래스, 주황 세로선은 질문 위치입니다. 가장 가까운 k개의 점이 투표합니다.':'보라: Noise · 초록: Border · 주황: Core. 점들의 실제 거리를 확인하면서 반경과 최소 이웃 수를 바꿔보세요.'}</figcaption></figure>;
  }
  if(topicId==='gmm-em'||topicId==='density-anomaly'){
    const density=(x:number)=>topicId==='gmm-em'?p.mix*normal(x,-2,p.std)+(1-p.mix)*normal(x,2,p.std):[-1,0,1].reduce((s,v)=>s+normal(x,v,p.h)/3,0),xs=Array.from({length:141},(_,i)=>-5+i/14),max=Math.max(...xs.map(density)),px=(x:number)=>40+(x+5)*44,py=(y:number)=>245-y/max*190,path=xs.map((x,i)=>`${i?'L':'M'}${px(x)},${py(density(x))}`).join(' ');
    return <figure className="topic-scene"><svg viewBox="0 0 520 290" role="img" aria-label="현재 설정의 분포 밀도"><path d={path} fill="none" stroke="#8d68b6" strokeWidth="3"/><line x1={px(p.x)} x2={px(p.x)} y1="50" y2="245" stroke="#c59057" strokeDasharray="6 4"/><circle cx={px(p.x)} cy={py(density(p.x))} r="5" fill="#c59057"/><text x="40" y="25">밀도: 최고 {n(max)}</text><text x="40" y="273">x=−5</text><text x="480" y="273" textAnchor="end">x=5</text></svg><figcaption>보라: 현재 설정에서 계산한 전체 밀도 · 주황: 관찰 위치. 밀도 높이 자체는 한 점의 확률이 아닙니다. 가로축 구간의 넓이를 적분한 것이 구간 확률입니다.</figcaption></figure>;
  }
  return null;
}
