import { useEffect,useState } from 'react';
import { initialNetwork,networkBatch,networkForward,networkStep,trainingInputs,trainingTargets,type NetworkParameters } from '../lib/learningMath';
import { n } from '../lib/lessonModelTypes';
import { Formula,Slider } from './UI';
import { href } from '../lib/route';
const phases=['순전파','손실 계산','역전파','가중치 갱신'];
type Run={p:NetworkParameters;phase:number;history:number[];error:string};
const initial=():Run=>{const p=initialNetwork();return{p,phase:0,history:[networkBatch(p).loss],error:''};};
function advance(run:Run,rate:number):Run {if(run.error||run.history.length>120)return run;if(run.phase<3)return{...run,phase:run.phase+1};const p=networkStep(run.p,rate),loss=networkBatch(p).loss;if(!Number.isFinite(loss)||loss>1e6)return{...run,error:'손실이 너무 커져 반복을 중단했습니다. 학습률을 낮추고 초기화해 다시 비교하세요.'};return{p,phase:0,history:[...run.history,loss],error:''};}
export default function TrainingLoop() {
 const [run,setRun]=useState(initial),[rate,setRate]=useState(.15),[playing,setPlaying]=useState(false),[sample,setSample]=useState(0);
 useEffect(()=>{if(!playing||run.error||run.history.length>120)return;const timer=window.setInterval(()=>setRun(r=>advance(r,rate)),650);return()=>window.clearInterval(timer);},[playing,rate,run.error,run.history.length]);
 const batch=networkBatch(run.p),s=batch.samples[sample],p=run.p,g=batch.gradient,epoch=run.history.length-1;
 const params=[['w₁₀',p.w1[0],g.w1[0]],['w₁₁',p.w1[1],g.w1[1]],['b₁₀',p.b1[0],g.b1[0]],['b₁₁',p.b1[1],g.b1[1]],['w₂₀',p.w2[0],g.w2[0]],['w₂₁',p.w2[1],g.w2[1]],['b₂',p.b2,g.b2]] as [string,number,number][];
 const stop=()=>setPlaying(false),step=()=>{stop();setRun(r=>advance(r,rate));},repeat=()=>{stop();setRun(r=>{let out=r;for(let i=0;i<20;i++)for(let phase=0;phase<4;phase++)out=advance(out,rate);return out;});};
 return <section className="topic-experiment training-loop"><span className="reading-label">계산을 이어서 학습하기</span><h2>순전파와 역전파를 반복하면 가중치는 어떻게 바뀔까요?</h2><p>1 → 2 → 1 신경망이 세 표본 x=[−1,0,1], y=[1,0,1]을 맞춥니다. 은닉층은 tanh, 출력은 Linear이며 7개 파라미터를 배치 SGD로 실제 갱신합니다. 작은 훈련 예제의 손실 감소가 새 데이터의 성능을 보장하지는 않습니다.</p><Formula>zⱼ=w₁ⱼx+b₁ⱼ; hⱼ=tanh(zⱼ){'\n'}ŷ=w₂₀h₀+w₂₁h₁+b₂{'\n'}Lbatch=(1/3)Σ표본 (ŷ−y)²/2</Formula>
 <ol className="training-phases">{phases.map((label,i)=><li key={label} className={run.phase===i?'active':''} aria-current={run.phase===i?'step':undefined}><span>{i+1}</span>{label}</li>)}</ol><div className="training-actions"><button className="button primary" onClick={step} disabled={Boolean(run.error)||epoch>=120}>다음 단계</button><button className="button" aria-pressed={playing&&epoch<120&&!run.error} disabled={Boolean(run.error)||epoch>=120} onClick={()=>setPlaying(v=>!v)}>{playing&&epoch<120?'일시 정지':'자동 반복'}</button><button className="button" onClick={repeat} disabled={Boolean(run.error)||epoch>=120}>20회 업데이트</button><button className="button" onClick={()=>{stop();setRun(initial());}}>학습 초기화</button></div><Slider label="SGD 학습률 η" value={rate} onChange={v=>{stop();setRate(v);}} min={.01} max={2} step={.01}/><label className="standalone-select">그림에서 볼 표본<select aria-label="학습 그림 표본" value={sample} onChange={e=>setSample(Number(e.target.value))}>{trainingInputs.map((x,i)=><option key={x} value={i}>x={x}, 정답={trainingTargets[i]}</option>)}</select></label>
 <div className="training-network-scroll"><svg className="training-network" viewBox="0 0 650 250" role="img" aria-label={`현재 가중치의 순전파와 선택 표본 역전파, ${phases[run.phase]}`}><title>입력 → tanh 은닉 두 개 → 선형 출력 → 손실; 역전파는 반대 방향</title>{[70,170].map((y,j)=><g key={j}><path d={`M85 120L260 ${y}L450 120`} fill="none" stroke={run.phase===2?'#488d7d':'#bba6d2'} strokeWidth={run.phase===2?3:2}/><text x="150" y={j===0?70:180}>{`w₁${j}=${n(p.w1[j])}`}</text><text x="325" y={j===0?70:180}>{`w₂${j}=${n(p.w2[j])}`}</text><circle cx="260" cy={y} r="25" fill="#efe8f8" stroke="#7561b8"/><text x="260" y={y+5} textAnchor="middle">{n(s.h[j])}</text></g>)}<circle cx="70" cy="120" r="25" fill="#fff" stroke="#7561b8"/><text x="70" y="125" textAnchor="middle">{s.x}</text><circle cx="450" cy="120" r="30" fill="#eee7f8" stroke="#7561b8"/><text x="450" y="125" textAnchor="middle">{n(s.prediction)}</text><path d="M480 120H550" stroke="#bba6d2" strokeWidth="2"/><rect x="550" y="92" width="83" height="57" rx="10" fill="#fbf1e5" stroke="#c69a65"/><text x="591" y="113" textAnchor="middle">표본 L</text><text x="591" y="136" textAnchor="middle">{n(s.error*s.error/2)}</text><text x="70" y="207" textAnchor="middle">입력 x</text><text x="260" y="207" textAnchor="middle">tanh(z)</text><text x="450" y="207" textAnchor="middle">예측 ŷ</text><text x="325" y="238" textAnchor="middle" fill={run.phase===2?'#488d7d':'#7561b8'}>{run.phase===2?'← 손실의 gradient를 두 경로로 전달':'→ 현재 가중치로 값을 전달'}</text></svg></div>
 <div className="training-description" aria-live="polite"><b>{epoch}회 업데이트 · 현재 {phases[run.phase]}</b><p>{['현재 가중치로 세 표본의 예측을 다시 계산합니다. 이전 라운드의 출력은 새 가중치의 출력과 다를 수 있습니다.','표본별 제곱 오차를 1/2로 나누고 세 표본의 평균을 구합니다. 그림의 표본 손실과 배치 손실을 구별하세요.','선택 표본의 연쇄법칙을 아래에서 보고, 실제 갱신에는 세 표본에서 얻은 gradient의 평균을 사용합니다.','아직 가중치를 바꾸지 않았습니다. 다음 단계를 누르면 표의 갱신 예정값을 적용하고 새 순전파로 돌아갑니다.'][run.phase]}</p></div>
 <Formula>선택 표본 e=ŷ−y={n(s.error)}{'\n'}∂Lsample/∂w₂ⱼ=e hⱼ; ∂Lsample/∂b₂=e{'\n'}δⱼ=e w₂ⱼ(1−hⱼ²)=[{s.dz.map(n).join(', ')}]{'\n'}∂Lsample/∂w₁ⱼ=δⱼx; ∂Lsample/∂b₁ⱼ=δⱼ{'\n'}g=(1/3)Σ표본∇Lsample; θnext=θ−ηg</Formula>
 <div className="matrix-table-scroll"><table className="parameter-table"><thead><tr><th>파라미터</th><th>현재 값</th><th>배치 gradient</th><th>갱신 예정 θ−ηg</th></tr></thead><tbody>{params.map(([label,value,gradient])=><tr key={label}><th>{label}</th><td>{n(value)}</td><td>{n(gradient)}</td><td>{n(value-rate*gradient)}</td></tr>)}</tbody></table></div><div className="training-charts"><figure><svg viewBox="0 0 380 235" role="img" aria-label="업데이트 횟수에 따른 배치 손실"><title>매 업데이트 뒤 다시 계산한 손실</title>{(()=>{const max=Math.max(...run.history,1e-6);return <><line x1="46" x2="355" y1="190" y2="190" stroke="#b9aac7"/><text x="8" y="28">{n(max)}</text><text x="22" y="190">0</text><path d={run.history.map((v,i)=>`${i?'L':'M'}${46+i/Math.max(epoch,1)*309},${190-v/max*160}`).join(' ')} fill="none" stroke="#7561b8" strokeWidth="3"/>{epoch===0&&<circle cx="46" cy="30" r="4" fill="#7561b8"/>}<text x="46" y="219">0</text><text x="355" y="219" textAnchor="end">{epoch}회</text></>;})()}</svg><figcaption>가로 업데이트 수 · 세로 배치 손실 {n(batch.loss)} · 전체 기록 기준 자동 축</figcaption></figure><figure><svg viewBox="0 0 380 235" role="img" aria-label="현재 신경망의 예측과 세 훈련 정답"><title>보라 현재 신경망, 주황 훈련 정답</title>{(()=>{const xs=Array.from({length:101},(_,i)=>i/50-1),ys=xs.map(x=>networkForward(p,x).prediction),lo=Math.min(0,...ys),hi=Math.max(1,...ys),span=hi-lo,py=(y:number)=>185-(y-lo)/span*150;return <><line x1="46" x2="355" y1={py(0)} y2={py(0)} stroke="#b9aac7"/><path d={ys.map((v,i)=>`${i?'L':'M'}${46+i/100*309},${py(v)}`).join(' ')} fill="none" stroke="#7561b8" strokeWidth="3"/>{trainingInputs.map((x,i)=><circle key={x} cx={46+(x+1)/2*309} cy={py(trainingTargets[i])} r="5" fill="#c18748"/>)}<text x="12" y="40">{n(hi)}</text><text x="12" y="185">{n(lo)}</text><text x="46" y="219">−1</text><text x="200" y="219">0</text><text x="355" y="219">1</text></>;})()}</svg><figcaption>가로 x · 세로 ŷ · 주황은 훈련 정답, 보라는 현재 예측</figcaption></figure></div>{(run.error||epoch>=120)&&<p className="calculation-warning">{run.error||'120회 업데이트에 도달했습니다. 초기화하면 다시 비교할 수 있습니다.'}</p>}<p>역전파는 미분을 계산하고, <a href={href('/lesson/optimizers')}>옵티마이저</a>는 파라미터를 바꿉니다. <a href={href('/lesson/torch-loop')}>PyTorch 학습 루프</a>의 backward와 step도 이 역할을 나눕니다. 높은 학습률에서 손실이 증가할 수 있습니다.</p></section>;
}
