import { useEffect, useState, type PointerEvent } from 'react';
import { attention, clamp, fmt, layerNorm, positionEncoding, sum, type Matrix as MatrixType } from '../lib/math';
import { attentionData, cacheData, cacheInput, cacheWords, ffnData, FW1, FW2, headsData, initialX, project, tokens, WK, WQ, WV, WO } from '../lib/transformer';
import TransformerExplanation from './TransformerExplanation';
import { Bars, Card, Choice, Formula, Matrix, Metric, Note, Slider } from './UI';

type NodeId = 'embed' | 'attention' | 'masked' | 'cross' | 'norm' | 'ffn' | 'output';
const nodeDetails: Record<NodeId, { title: string; copy: string; formula: string; dimension: string }> = {
  embed: { title: 'Embedding + Position', copy: '토큰 ID를 벡터로 바꾸고 순서 정보를 더합니다. 위치 정보가 없는 self-attention은 순서 자체를 알 수 없습니다.', formula: 'X = √D · E(token) + PE', dimension: '입력 토큰 n개 → [n,D]' },
  attention: { title: 'Multi-head Self-attention', copy: '각 토큰이 다른 토큰의 관련도를 계산하고 Value를 모읍니다. Encoder의 양방향 self-attention은 미래 위치도 참조합니다.', formula: 'Attention = softmax(QKᵀ / √dₖ + M)V', dimension: '관련도 [n,n] · 출력 [n,D]' },
  masked: { title: 'Masked Self-attention', copy: '생성할 때 미래 토큰을 볼 수 없도록 현재 위치보다 뒤인 점수에 −∞를 더합니다. Softmax 이후 미래 위치의 확률은 0입니다.', formula: 'Mᵢⱼ = 0 (j ≤ i), −∞ (j > i)', dimension: '행은 Query · 열은 Key' },
  cross: { title: 'Cross-attention', copy: 'Query는 Decoder, Key와 Value는 Encoder 출력에서 가져옵니다. 원문의 정보를 생성 중인 표현에 전달합니다.', formula: 'Q = Hdec WQ; K = Henc WK; V = Henc WV', dimension: '관련도 [ntarget,nsource]' },
  norm: { title: 'Residual + LayerNorm', copy: '입력 신호의 직접 경로를 더하고 토큰별 feature를 정규화합니다. 원 논문은 Post-LN, 여기의 Decoder-only 도식은 Pre-LN입니다.', formula: 'Post-LN: LN(x + Sublayer(x))\nPre-LN: x + Sublayer(LN(x))', dimension: '입출력 shape 동일 [n,D]' },
  ffn: { title: 'Position-wise Feed-forward', copy: '모든 토큰에 같은 가중치로 MLP를 독립 적용합니다. 중간 차원을 확장하고 비선형 변환 후 원래 차원으로 투영합니다.', formula: 'FFN(x) = φ(xW₁+b₁)W₂+b₂', dimension: '원 논문: 512 → 2048 → 512' },
  output: { title: 'Linear + Softmax', copy: '마지막 표현을 어휘 개수만큼의 logit으로 투영합니다. 학습 때 정답 다음 토큰의 확률이 커지도록 cross-entropy를 줄입니다.', formula: 'p = softmax(hWvocab+b)\nℒ = −Σₜ log p(yₜ | y<ₜ,x)', dimension: '표현 [n,D] → logits [n,V]' },
};
function SectionTitle({ title, copy }: { title: string; copy: string }) { return <div className="experiment-intro"><h2>{title}</h2><p>{copy}</p></div>; }

export default function Transformer() {
  const [arch, setArch] = useState<'original' | 'decoder'>('original');
  const [node, setNode] = useState<NodeId>('attention');
  const [x, setX] = useState<MatrixType>(() => initialX.map(row => [...row]));
  const [mask, setMask] = useState(false), [temperature, setTemperature] = useState(1);
  const [query, setQuery] = useState(2), [key, setKey] = useState(2);
  const [headCount, setHeadCount] = useState(2), [head, setHead] = useState(0);
  const [position, setPosition] = useState(3), [pair, setPair] = useState(0);
  const [normInput, setNormInput] = useState([1, 2, -1, .5]), [strength, setStrength] = useState(1);
  const [ffnInput, setFfnInput] = useState(1), [activation, setActivation] = useState<'relu' | 'gelu'>('relu');
  const [cache, setCache] = useState(() => ({ length: 4, k: project(initialX, WK), v: project(initialX, WV) }));
  const [playing, setPlaying] = useState(false), [memoryTokens, setMemoryTokens] = useState(1024);
  useEffect(() => {
    if (!playing || cache.length >= 12) return;
    const timer = window.setInterval(() => advanceCache(), 1300);
    return () => window.clearInterval(timer);
  }, [playing, cache.length]);
  useEffect(() => { if (cache.length >= 12) setPlaying(false); }, [cache.length]);
  function advanceCache() { setCache(current => current.length >= 12 ? current : { length: current.length + 1, k: [...current.k, ...project([cacheInput(current.length)], WK)], v: [...current.v, ...project([cacheInput(current.length)], WV)] }); }
  function editX(i: number, j: number, value: number) { setX(current => current.map((row, ri) => row.map((old, cj) => ri === i && cj === j ? value : old))); }
  const data = attentionData(x, mask, temperature);
  function editQ(q: number[]) { setX(current => current.map((row, i) => i === query ? [q[0] - .2 * row[2] - .1 * row[3], q[1] - .1 * row[2] + .2 * row[3], row[2], row[3]] : row)); }
  const extent = Math.max(2, Math.ceil(Math.max(...data.q.flat().map(Math.abs), ...data.k.flat().map(Math.abs))));
  function dragQuery(e: PointerEvent<SVGSVGElement>) {
    if (!e.currentTarget.hasPointerCapture(e.pointerId)) return;
    const bounds = e.currentTarget.getBoundingClientRect();
    const px = (e.clientX - bounds.left) / bounds.width * 360, py = (e.clientY - bounds.top) / bounds.height * 280;
    editQ([clamp((px - 180) / (105 / extent), -extent, extent), clamp((140 - py) / (105 / extent), -extent, extent)]);
  }
  function architectureNode(id: NodeId, label: string) { return <button className={`architecture-node node-${id} ${node === id ? 'picked' : ''}`} onClick={() => setNode(id)} aria-pressed={node === id}>{label}</button>; }
  const resetX = () => { setX(initialX.map(row => [...row])); setMask(false); setTemperature(1); };
  return <div className="transformer-lab">
    <section id="transformer-structure" className="continuous-experiment">
      <SectionTitle title="전체 구조를 한눈에" copy="레이어를 선택하고, 입력에서 다음 토큰까지 정보의 흐름을 따라가세요." />
      <TransformerExplanation section="structure" />
      <div className="experiment-grid architecture-grid"><Card title="Architecture map" action={<Choice label="모델 구조" value={arch} onChange={setArch} options={[{ value: 'original', label: 'Encoder–Decoder' }, { value: 'decoder', label: 'Decoder-only' }]} />}>
        <div className={`towers ${arch === 'decoder' ? 'single' : ''}`}>
          {arch === 'original' && <div className="tower"><h4>ENCODER</h4><div className="token-row"><span>나는</span><span>고양이를</span><span>좋아해</span></div><div className="down">↓</div>{architectureNode('embed', 'Embedding + Position')}<div className="down">↓</div><div className="layer-stack"><small>N ×</small>{architectureNode('attention', 'Multi-head Self-attention')}<div className="down">↓</div>{architectureNode('norm', 'Add & Norm')}<div className="down">↓</div>{architectureNode('ffn', 'Feed-forward')}<div className="down">↓</div>{architectureNode('norm', 'Add & Norm')}</div><div className="cross-connection">Encoder 출력 K, V → Cross-attention</div></div>}
          <div className="tower"><h4>{arch === 'original' ? 'DECODER' : 'DECODER-ONLY · PRE-LN'}</h4><div className="token-row"><span>&lt;BOS&gt;</span><span>I</span><span>like</span></div><div className="down">↓</div>{architectureNode('embed', 'Embedding + Position')}<div className="down">↓</div><div className="layer-stack"><small>N ×</small>{arch === 'decoder' && <>{architectureNode('norm', 'LayerNorm')}<div className="down">↓</div></>}{architectureNode('masked', 'Masked Self-attention')}<div className="down">↓</div>{architectureNode('norm', arch === 'original' ? 'Add & Norm' : 'Residual Add')}{arch === 'original' && <><div className="down">↓</div>{architectureNode('cross', 'Cross-attention · K,V ← Encoder')}<div className="down">↓</div>{architectureNode('norm', 'Add & Norm')}</>}<div className="down">↓</div>{arch === 'decoder' && <>{architectureNode('norm', 'LayerNorm')}<div className="down">↓</div></>}{architectureNode('ffn', 'Feed-forward')}<div className="down">↓</div>{architectureNode('norm', arch === 'original' ? 'Add & Norm' : 'Residual Add')}</div><div className="down">↓</div>{arch === 'decoder' && <>{architectureNode('norm', 'Final LayerNorm')}<div className="down">↓</div></>}{architectureNode('output', 'Linear + Softmax')}<div className="down">↓</div><span className="predicted-token">cats</span></div>
        </div><Note>화살표는 계산 순서를 나타냅니다. 각 sublayer의 Residual 연결은 Add에서 입력을 더합니다.</Note>
      </Card><Card title="선택한 레이어"><div className="eyebrow">LAYER DETAIL</div><h3 className="detail-title">{nodeDetails[node].title}</h3><p>{nodeDetails[node].copy}</p><Formula>{nodeDetails[node].formula}</Formula><div className="dimension-tag">{nodeDetails[node].dimension}</div><Note>학습에서는 shifted target과 causal mask로 여러 위치를 병렬 계산합니다. 생성에서는 다음 토큰을 하나씩 이어 붙입니다. Pre-LN은 정규화를 sublayer 앞에 둡니다.</Note></Card></div>
      <div className="three-cards"><Card title="Self-attention"><p>같은 시퀀스에서 Q·K·V를 얻습니다. 토큰 사이에서 표현을 섞습니다.</p></Card><Card title="Cross-attention"><p>Decoder의 Q가 Encoder의 K·V를 참조합니다. 두 시퀀스 길이는 달라도 됩니다.</p></Card><Card title="학습과 생성"><p>학습은 정답 다음 토큰의 손실을 줄이고, 생성은 예측된 토큰을 다음 입력으로 씁니다.</p></Card></div>
    </section>
    <section id="transformer-attention" className="continuous-experiment">
      <SectionTitle title="같은 입력, 세 가지 역할" copy="입력 셀을 위아래로 드래그하거나 방향키로 조절하세요. 모든 행렬이 실제로 다시 계산됩니다." />
      <TransformerExplanation section="attention" />
      <div className="experiment-grid"><Card title="Linear projections → Attention" action={<button className="button small" onClick={resetX}>초기화</button>}>
        <div className="matrix-scroll"><div className="matrix-line"><Matrix values={x} name="X · Input" onEdit={editX} /><span className="matrix-op">×</span><Formula>Q = XWQ{'\n'}K = XWK{'\n'}V = XWV</Formula></div></div><div className="matrix-scroll"><div className="matrix-line"><Matrix values={data.q} name="Q · Query" /><Matrix values={data.k} name="K · Key" color="blue" /><Matrix values={data.v} name="V · Value" color="green" /></div></div>
        <details><summary>고정된 투영 가중치 보기 · 각 W는 4 × 2</summary><div className="matrix-scroll"><div className="matrix-line"><Matrix values={WQ.map(row => row.slice(0, 2))} name="WQ" /><Matrix values={WK.map(row => row.slice(0, 2))} name="WK" color="blue" /><Matrix values={WV.map(row => row.slice(0, 2))} name="WV" color="green" /></div></div></details>
        <div className="controls"><label className="check"><input type="checkbox" checked={mask} onChange={e => setMask(e.target.checked)} />Causal mask</label><Slider label="온도 τ" value={temperature} onChange={setTemperature} min={.2} max={2} step={.1} /></div>
        <div className="matrix-scroll"><div className="matrix-line"><Matrix values={data.scores} name="S · Scaled scores" onSelect={(i, j) => { setQuery(i); setKey(j); }} selected={[query, key]} /><span className="matrix-op">→</span><Matrix values={data.weights} name="A · Softmax" probability onSelect={(i, j) => { setQuery(i); setKey(j); }} selected={[query, key]} /><span className="matrix-op">× V →</span><Matrix values={data.output} name="O · Context" color="green" /></div></div>
        <Note>행은 Query, 열은 Key입니다. Softmax는 각 행에 적용되어 행 합이 1입니다. 표시값을 반올림하면 합이 조금 달라 보일 수 있습니다.</Note>
      </Card><Card title="Query playground"><Choice label="Query 토큰" value={query} onChange={setQuery} options={tokens.map((label, value) => ({ value, label }))} />
        <svg className="query-plot" viewBox="0 0 360 280" role="img" aria-label="Query 벡터 드래그. 아래 슬라이더로도 변경할 수 있습니다." onPointerDown={e => { if ((e.target as Element).getAttribute('data-handle') === 'query') { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); } }} onPointerMove={dragQuery}>
          {[-extent, 0, extent].map(value => <g key={value}><path d={`M${180 + value * 105 / extent} 30V250 M40 ${140 - value * 105 / extent}H320`} stroke={value === 0 ? '#c1c8d5' : '#e8ebf0'} /><text x={180 + value * 105 / extent} y="270">{value}</text></g>)}
          {data.k.map((k, i) => <g key={i}><path d={`M180 140L${180 + k[0] * 105 / extent} ${140 - k[1] * 105 / extent}`} stroke="#5c89bc" opacity=".4" /><circle cx={180 + k[0] * 105 / extent} cy={140 - k[1] * 105 / extent} r="5" fill="#5c89bc" /><text x={186 + k[0] * 105 / extent} y={155 - k[1] * 105 / extent}>k{i + 1}</text></g>)}
          <path d={`M180 140L${180 + data.q[query][0] * 105 / extent} ${140 - data.q[query][1] * 105 / extent}`} stroke="#7561b8" strokeWidth="2" /><circle data-handle="query" cx={180 + data.q[query][0] * 105 / extent} cy={140 - data.q[query][1] * 105 / extent} r="10" fill="#7561b8" stroke="white" strokeWidth="3" /><text x="12" y="18">보라색: Q · 파란색: K · 범위 ±{extent}</text>
        </svg>
        <Slider label="q₁" value={data.q[query][0]} onChange={value => editQ([value, data.q[query][1]])} min={-extent} max={extent} step={.01} /><Slider label="q₂" value={data.q[query][1]} onChange={value => editQ([data.q[query][0], value])} min={-extent} max={extent} step={.01} />
        <p className="micro">Q를 바꾸면 X의 앞 두 feature를 역으로 조절하므로 K·V도 변합니다.</p><Bars values={data.weights[query]} labels={tokens} /><Formula>{`s${query + 1},${key + 1} = ${fmt(data.scores[query][key])}\na${query + 1},${key + 1} = ${fmt(data.weights[query][key])}\noᵢ = Σⱼ aᵢⱼvⱼ`}</Formula>
      </Card></div><Formula>Attention(Q,K,V) = softmax(QKᵀ / (√2 · τ) + M)V</Formula><Note>임의의 작은 입력과 가중치입니다. 실제 학습된 토큰 의미를 보여주는 모델은 아닙니다. τ는 분포 관찰용 추가 제어이며 표준 어텐션은 τ=1입니다.</Note>
    </section>
    <section id="transformer-heads" className="continuous-experiment">{(() => {
      const d = headsData(x, headCount, mask); return <>
        <SectionTitle title="여러 표현 공간에서 함께 보기" copy="헤드별 투영을 계산하고, 열을 연결한 다음 출력 투영으로 정보를 섞습니다." />
      <TransformerExplanation section="heads" />
        <div className="controls"><Choice label="헤드 수" value={headCount} onChange={value => { setHeadCount(value); setHead(0); }} options={[1, 2, 4].map(value => ({ value, label: `${value}개 헤드` }))} /><label className="check"><input type="checkbox" checked={mask} onChange={e => setMask(e.target.checked)} />Causal mask</label></div>
        <div className="dimension-path"><span>X: 4 × 4</span><b>→</b><span>{headCount} × Head: 4 × {4 / headCount}</span><b>→</b><span>Concat: 4 × 4</span><b>→</b><span>WO: 4 × 4</span></div>
        <div className="head-cards">{d.heads.map((h, i) => <button key={i} className={`head-card ${head === i ? 'selected' : ''}`} aria-pressed={head === i} onClick={() => setHead(i)}><h3>Head {i + 1} <small>dₖ = dᵥ = {4 / headCount}</small></h3><Matrix values={h.weights} name={`Head ${i + 1} · A`} probability /></button>)}</div>
        <div className="experiment-grid"><Card title={`Head ${head + 1}의 실제 계산`}><div className="matrix-scroll"><div className="matrix-line"><Matrix values={d.heads[head].q} name="Q" /><Matrix values={d.heads[head].k} name="K" color="blue" /><Matrix values={d.heads[head].v} name="V" color="green" /><Matrix values={d.heads[head].output} name="Head output" color="green" /></div></div><Formula>headᵢ = Attention(XWQᵢ,XWKᵢ,XWVᵢ)</Formula></Card><Card title="Concat와 출력 투영"><div className="matrix-scroll"><div className="matrix-line"><Matrix values={d.concat} name="Concat" /><span className="matrix-op">×</span><Matrix values={WO} name="WO" color="blue" /><span className="matrix-op">→</span><Matrix values={d.output} name="Output" color="green" /></div></div></Card></div><Note>같은 4×4 가중치의 열을 헤드별로 나누는 예제입니다. 헤드 수를 바꾸면 softmax를 계산하는 공간도 달라져 최종 출력이 달라집니다. 실제 모델의 헤드는 각각 학습된 투영을 사용합니다.</Note>
      </>;
    })()}</section>
    <section id="transformer-blocks" className="continuous-experiment">
      <SectionTitle title="어텐션만으로는 완성되지 않는 블록" copy="위치 정보, 직접 연결, 정규화, 비선형 변환을 연결합니다." />
      <TransformerExplanation section="blocks" />
      <div className="experiment-grid"><Card title="Sinusoidal positional encoding"><Slider label="위치 pos" value={position} onChange={setPosition} min={0} max={31} /><Slider label="차원 쌍 i" value={pair} onChange={setPair} min={0} max={3} />
        <svg className="position-plot" viewBox="0 0 600 260" role="img" aria-label="위치에 따른 sin cos 파형. 드래그하거나 위치 슬라이더로 이동" onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); const b = e.currentTarget.getBoundingClientRect(); setPosition(Math.round(clamp(((e.clientX - b.left) / b.width * 600 - 35) / 530 * 31, 0, 31))); }} onPointerMove={e => { if (e.currentTarget.hasPointerCapture(e.pointerId)) { const b = e.currentTarget.getBoundingClientRect(); setPosition(Math.round(clamp(((e.clientX - b.left) / b.width * 600 - 35) / 530 * 31, 0, 31))); } }}>
          {[-1, 0, 1].map(v => <g key={v}><path d={`M35 ${125 - 80 * v}H565`} stroke="#e3e7ed" /><text x="7" y={129 - 80 * v}>{v}</text></g>)}
          {[0, 1].map((s, i) => <path key={s} d={Array.from({ length: 250 }, (_, k) => { const pos = k / 249 * 31; return `${k ? 'L' : 'M'}${35 + pos / 31 * 530},${125 - positionEncoding(pos, 2 * pair + s) * 80}`; }).join(' ')} fill="none" stroke={i ? '#5c89bc' : '#7561b8'} strokeWidth="2" />)}
          <path d={`M${35 + position / 31 * 530} 25V225`} stroke="#ac9bda" strokeDasharray="4 4" />{[0, 1].map((s, i) => <circle key={s} cx={35 + position / 31 * 530} cy={125 - positionEncoding(position, 2 * pair + s) * 80} r="6" fill={i ? '#5c89bc' : '#7561b8'} />)}<text x="35" y="250">위치 pos →</text>
        </svg><div className="matrix-scroll"><Matrix values={[Array.from({ length: 8 }, (_, i) => positionEncoding(position, i))]} name={`PE(pos=${position})`} /></div><div className="matrix-scroll"><Matrix values={Array.from({ length: 8 }, (_, pos) => Array.from({ length: 8 }, (_, dim) => positionEncoding(pos, dim)))} name="첫 8개 위치 × 8차원" color="blue" /></div>
      </Card><Card title="순서도 정보입니다"><h3 className="detail-title">“고양이가 나를”<br />“내가 고양이를”</h3><p>위치 정보가 없으면 순서를 바꿀 때 출력도 같은 순서로 재배열됩니다. 위치 인코딩은 순서를 표현에 더합니다.</p><Formula>PE(pos,2i) = sin(pos / 10000^(2i/D)){'\n'}PE(pos,2i+1) = cos(pos / 10000^(2i/D))</Formula><div className="dimension-tag">D = 8 · 선택 차원 {2 * pair}, {2 * pair + 1}</div><Note>원 논문의 Sinusoidal 방식입니다. 다른 모델에는 학습된 위치 임베딩이나 Q·K를 회전하는 RoPE 등이 사용됩니다.</Note></Card></div>
      {(() => { const sublayer = normInput.map(v => strength * Math.tanh(v)), z = normInput.map((v, i) => v + sublayer[i]), d = layerNorm(z); return <div className="experiment-grid"><Card title="Residual → LayerNorm · Post-LN"><div className="dimension-path"><span>x</span>→<span>Sublayer(x)</span>→<span>+ x</span>→<span>LN</span></div>{normInput.map((value, i) => <Slider key={i} label={`x${i + 1}`} value={value} onChange={next => setNormInput(current => current.map((v, j) => j === i ? next : v))} min={-3} max={3} step={.1} />)}<Slider label="Sublayer 강도 α" value={strength} onChange={setStrength} min={0} max={2} step={.1} /><div className="matrix-scroll"><div className="matrix-line"><Matrix values={[normInput]} name="x" /><Matrix values={[sublayer]} name="α · tanh(x)" color="blue" /></div><div className="matrix-line"><Matrix values={[z]} name="z = x + Sublayer(x)" color="orange" /><Matrix values={[d.output]} name="LayerNorm(z)" color="green" /></div></div></Card><Card title="평균과 분산 확인"><Formula>z = x + Sublayer(x){'\n'}LN(z) = γ⊙(z−μ)/√(σ²+ε)+β</Formula><div className="metrics"><Metric value={fmt(d.mean)} label="z의 평균" /><Metric value={fmt(d.variance)} label="z의 분산" /><Metric value={fmt(sum(d.output) / 4)} label="정규화 후 평균" /><Metric value={fmt(sum(d.output.map(v => v * v)) / 4)} label="정규화 후 분산" /></div><Note>γ=1,β=0,ε=10⁻⁵. ε 때문에 출력 분산은 정확히 1보다 조금 작습니다. Sublayer는 변화 관찰용 α·tanh(x)이며 실제 모델에서는 Attention 또는 FFN입니다.</Note><Formula>Pre-LN: y = x + Sublayer(LN(x))</Formula></Card></div>; })()}
      {(() => { const d = ffnData(ffnInput, activation); return <div className="experiment-grid"><Card title="Expand → Activate → Project"><Slider label="입력 x₁" value={ffnInput} onChange={setFfnInput} min={-3} max={3} step={.1} /><Choice label="FFN 활성화" value={activation} onChange={setActivation} options={[{ value: 'relu', label: 'ReLU' }, { value: 'gelu', label: 'GELU' }]} /><div className="neural-flow">{[d.x, d.activated, d.output].map((values, layer) => <div key={layer}><small>{['입력 · 4', 'Hidden · 6', '출력 · 4'][layer]}</small>{values.map((v, i) => <span key={i} style={{ background: `color-mix(in srgb, ${layer === 1 ? '#488d7d' : '#7561b8'} ${Math.min(60, 8 + Math.abs(v) * 15)}%, white)` }}>{fmt(v)}</span>)}</div>)}</div><div className="matrix-scroll"><div className="matrix-line"><Matrix values={[d.z]} name="Pre-activation" /><Matrix values={[d.activated]} name={activation.toUpperCase()} color="green" /></div></div><details><summary>가중치와 Bias 보기</summary><div className="matrix-scroll"><div className="matrix-line"><Matrix values={FW1} name="W₁" /><Matrix values={FW2} name="W₂" color="blue" /></div></div><p>b₁=[0.1,−0.2,0.1,0,0.2,−0.1], b₂=[0,0,0,0]</p></details></Card><Card title="토큰별로 정보를 가공하기"><Formula>FFN(x) = φ(xW₁+b₁)W₂+b₂{'\n'}ReLU(z) = max(0,z){'\n'}GELU(z) ≈ ½z(1+tanh[√(2/π)(z+0.044715z³)])</Formula><p>어텐션은 토큰 사이의 정보를 모으고 FFN은 각 토큰의 feature를 같은 가중치로 독립 변환합니다. 활성화가 없으면 두 선형변환은 하나로 합쳐집니다.</p><div className="metrics"><Metric value="4 → 6 → 4" label="이 예제의 차원" /><Metric value="512 → 2048 → 512" label="원 논문의 차원" /></div><Note>가독성을 위한 고정 가중치입니다. ReLU는 원 논문, GELU는 다른 모델의 예시이며 여기서는 tanh 근사식을 계산합니다.</Note></Card></div>; })()}
    </section>
    <section id="transformer-cache" className="continuous-experiment">{(() => { const d = cacheData(cache.length), cached = attention(d.q, cache.k, cache.v), error = Math.max(...d.full.output[0].map((v, i) => Math.abs(v - cached.output[0][i]))), memory = 2 * 1 * 12 * 8 * memoryTokens * 64 * 2 / 1024 ** 2; return <>
      <SectionTitle title="이미 계산한 문맥을 기억하기" copy="Prefill 이후 토큰을 하나씩 처리하며 과거 K·V의 재계산과 캐시 재사용을 비교하세요." />
      <TransformerExplanation section="cache" />
      <div className="controls"><button className="button primary" disabled={cache.length >= 12} onClick={advanceCache}>＋ 다음 토큰 처리</button><button className="button" disabled={cache.length >= 12} onClick={() => setPlaying(v => !v)}>{playing ? '일시정지' : '자동 재생'}</button><button className="button" onClick={() => { setPlaying(false); setCache({ length: 4, k: project(initialX, WK), v: project(initialX, WV) }); }}>초기화</button><span className="micro">{cache.length === 4 ? 'Prefill · 4 tokens' : `Decode ${cache.length - 4} / 8 · context ${cache.length}`}</span></div>
      <div className="two-cards">{[false, true].map(isCached => <Card key={String(isCached)} title={isCached ? 'With KV cache' : 'Without cache'}><div className="token-row cache-tokens">{cacheWords.slice(0, cache.length).map((word, i) => <span key={i} className={isCached && i < cache.length - 1 && cache.length > 4 ? 'reused' : 'new-token'}>{word}</span>)}</div><p>{cache.length === 4 ? '초기 4개 토큰을 prefill로 계산합니다.' : isCached ? `과거 ${cache.length - 1}행은 저장된 결과를 쓰고 새 K·V만 계산합니다.` : `전체 ${cache.length}개 토큰의 K·V를 다시 계산합니다.`}</p><div className="matrix-scroll"><div className="matrix-line"><Matrix values={isCached ? cache.k : d.k} name={isCached ? 'K cache' : 'K = XWK'} color={isCached ? 'green' : 'orange'} /><Matrix values={isCached ? cache.v : d.v} name={isCached ? 'V cache' : 'V = XWV'} color={isCached ? 'green' : 'orange'} /></div></div><Formula>{isCached ? 'K₁:ₜ = [K₁:ₜ₋₁; kₜ]\nV₁:ₜ = [V₁:ₜ₋₁; vₜ]' : 'K₁:ₜ = X₁:ₜWK\nV₁:ₜ = X₁:ₜWV'}</Formula></Card>)}</div>
      <div className="metrics cache-metrics"><Metric value={d.baseCost} label="캐시 없이 · 누적 K·V 투영 벡터 수" /><Metric value={d.cacheCost} label="캐시 사용 · 누적 K·V 투영 벡터 수" /><Metric value={`${(100 * (1 - d.cacheCost / d.baseCost)).toFixed(0)}%`} label="절약된 투영 · 실제 지연시간 비율 아님" /></div>
      <div className="experiment-grid"><Card title="같은 Attention, 같은 출력"><Formula>oₜ = softmax(qₜK₁:ₜᵀ / √dₖ)V₁:ₜ</Formula><div className="matrix-scroll"><div className="matrix-line"><Matrix values={d.q} name="새 qₜ" /><Matrix values={d.full.output} name="Without cache" color="orange" /><Matrix values={cached.output} name="With cache" color="green" /></div></div><div className="equal-note">출력의 최대 절대 차이 = {error.toExponential(1)}</div><Note>과거 hidden 입력이 바뀌지 않는 causal 추론의 한 레이어·한 헤드 예제입니다. 실제 모델은 레이어마다 캐시를 둡니다. 토큰 시퀀스는 비교용으로 미리 정해져 있습니다. 새 Query는 모든 과거 Key와 여전히 비교합니다.</Note></Card><Card title="계산과 메모리의 교환"><Formula>Memory = 2 · B · L · HKV · t · dhead · bytes</Formula><Slider label="문맥 길이 t" value={memoryTokens} onChange={setMemoryTokens} min={128} max={8192} step={128} /><Metric value={`${memory.toFixed(1)} MiB`} label="K·V 텐서 메모리" /><p className="micro">B=1,L=12,HKV=8,dhead=64,FP16=2 bytes. 관리 오버헤드는 제외합니다.</p><Note>GQA·MQA는 KV 헤드 수를 줄여 캐시 크기를 줄입니다. 양방향 Encoder는 새 토큰 때문에 과거 표현이 바뀔 수 있어 같은 재사용을 그대로 적용할 수 없습니다.</Note></Card></div>
    </>; })()}</section>
  </div>;
}
